### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [exiftool/exiftool#1]
It is possible to migrate the personal account to organization?
https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by Neustradamus** [comment]
It was not done...
Why?

**Comment by boardhead** [comment]
Why do you want this?

**Comment by Neustradamus** [comment]
To be more pro ^^
And better to use it.

The personal account to exiftool-account, the creation of exiftool organization, the transfer of the project (not a fork), easy to manage it...

**Comment by boardhead** [comment]
Done.

**Comment by Neustradamus** [comment]
@boardhead Thanks!

You can name the organization to ExifTool instead of "Phil Harvey"
You can add a website link for the organization...
Add your personal account in the list of people (your account is not showed) ^^
On projects, you can add topics and website for a best visibility...

I hope that you will have more commits from people!

**Comment by Neustradamus** [comment]
:)

**Comment by Neustradamus** [comment]
@boardhead: Why you do not commit with your personal account?
You must to update the email address in your git settings :)
It will be better :)

Change your visibility from private to public here:
- https://github.com/orgs/exiftool/people

**Comment by boardhead** [comment]
Why does this matter?

**Comment by boardhead** [comment]
OK.  I see from your previous posts why you want me to do this.  But I don't see a real benefit in doing this, and even just thinking about this has wasted more time than I think this is worth. :(

I don't care about the project visibility.  In fact, a little less visible would be nice because I barely have enough time at the moment to deal with all of the questions/comments/suggestions that people have.

**Comment by Neustradamus** [comment]
The goal is to commit like the real author (you) instead of "exiftool".
And it will be in your graph; https://github.com/boardhead
Can you change your account visibility in the exiftool organization? It is currently private instead of public.

- You can see people here: https://github.com/orgs/GNOME/people, you are not showed in exiftool org but you think you are.
- It is not GNOME, the commiter: https://github.com/GNOME/gnome-shell/commits/master

To set your global username/email configuration, open the command line:

Set your username:
- git config --global user.name "FIRST_NAME LAST_NAME"

Set your email address:
- git config --global user.email "MY_NAME@example.com"

To set repository-specific username/email configuration, from the command line, change into the repository directory:
Set your username:
- git config user.name "FIRST_NAME LAST_NAME"

Set your email address:
- git config user.email "MY_NAME@example.com"

Note:
- "FIRST_NAME LAST_NAME" can be "boardhead"
- "MY_NAME@example.com", the email address that you have added in your GitHub account (you can hide your email address, please look https://github.com/settings/emails)

**Comment by Neustradamus** [comment]
Example: https://github.com/ncw with rclone:
- He has showed in public: https://github.com/rclone
- He commits with this personal account, look this history
