### ISSUE TITLE
DICOM IS (integer strings) are not parsed as integers

### ISSUE THREAD

**Issue by bersbersbers** [exiftool/exiftool#10]
In DICOM, `  "InstanceNumber" => "1 "` should probably be `  "InstanceNumber" => 1` (as an integer, not as a string).

Compare https://github.com/exiftool/exiftool/issues/9 for example data.

**Comment by boardhead** [comment]
This is solved by the resolution to issue #9.

**Comment by boardhead** [comment]
Resolved by ExifTool 11.29
