### ISSUE TITLE
New lens: Sigma 12-24mm F4 DG HSM Art for Nikon 

### ISSUE THREAD

**Issue by Sturmflut** [exiftool/exiftool#101]
Output of exiftool on raw files shot with a "Sigma 12-24mm F4 DG HSM Art" lens on Nikon D850 and D750:

Lens Type                       : E G
Lens                            : 12-24mm f/4
Lens Focus Function Buttons     : AF Lock Only
Lens Data Version               : 0204
Lens ID Number                  : 202
Lens F Stops                    : 5.00
Lens ID                         : Unknown (CA 3C 1F 37 30 30 4B 46)
Lens Spec                       : 12-24mm f/4 E G

**Comment by boardhead** [comment]
Great, thanks!  This will appear in 12.35.

- Phil

**Comment by boardhead** [comment]
Version 12.35 is now available.
