### ISSUE TITLE
website down, would you use github release for download?

### ISSUE THREAD

**Issue by yoyoys** [exiftool/exiftool#104]
Without website we can't download this awesome software :(

**Comment by IanWardell** [comment]
For now try way back machine https://web.archive.org/web/20211122235924/https://exiftool.org/

**Comment by IanWardell** [comment]
I came here to note that the website is down.

**Comment by robbiemorrison** [comment]
[Website](https://exiftool.org) still down.  Just posting this to record the timestamp, that is now 13&nbsp;hours down.

**Comment by tanrak** [comment]
Download is also possible at [SourceForge.net](https://sourceforge.net/projects/exiftool/files/).

**Comment by danielhoherd** [comment]
I also came here due to the website being down, hoping that releases were mirrored in Github or [Gitlab](https://gitlab.com/gitlab-org/build/omnibus-mirror/exiftool). If anybody needs help working on that feature I can help out.

**Comment by IvanDesuo** [comment]
> Download is also possible at [SourceForge.net](https://sourceforge.net/projects/exiftool/files/).

The forum, however, doesnt work even in this domain, there were so many good infos in that forum. Im kind worried. Do we know what happened to the site. Is Phil struggling with something?

**Comment by robbiemorrison** [comment]
It also looks like the domain name https://exiftool.org has bee relinquished.  Perhaps it should be secured?  I am afraid I cannot contribute to that effort.

**Comment by IanWardell** [comment]
It looks like Phil retired from Queen's University in Apr 2020, maybe retired the project? https://www.linkedin.com/in/phil-harvey-17806935/?originalSubdomain=ca ; either way not good for the project. Quick Google search found a Facebook with a Nov 28th post, so I believe he is alive. Which is good.

**Comment by CarbonV** [comment]
Just found out about this tool and was able to download it from SourceForge. However would love to access some of the forum posts. Most have not been stored in the WayBackMachine.

**Comment by robbiemorrison** [comment]
There was a lot of documentation on the https://exiftool.org website.  That included many large tables describing the supported metadata along with change logs and so forth.  What a tragedy if some or all of that of that information has been lost.  Looks like the fabled hit‑by‑bus factor in play?

**Comment by tanrak** [comment]
@robbiemorrison An old version (from the year 2007) of the website with all docs and tables can be found [here](http://web.mit.edu/graphics/src/Image-ExifTool-6.99/html/index.html).

**Comment by speich** [comment]
wow, this is a bummer

**Comment by hackerfactor** [comment]
Any update? Has anyone heard from Phil? (I'm wondering if he even knows it is down.)

**Comment by Sponsoredby** [comment]
today my AV has been going haywire detecting malware from cache-exiftool

**Comment by robbiemorrison** [comment]
AV = antivirus software

**Comment by hackerfactor** [comment]
Exiftool.org seems to be back up.

Q: Is the malware detection coming from software downloaded from Exiftool.org, or is it in your local copy of the code?

**Comment by robbiemorrison** [comment]
The https://exiftool.org website is indeed back up.  We could talk about moving the documentation (in basic HTML or something else) to some kind of repo.  That depends a little on how the website is indeed generated or (possibly) hand‑coded.

That site has version **12.36** listed as current.  My last admittedly last haphazard update was to **12.34** and I've had no problems.  Indeed, I am not going to change unless the integrity of the codebase can be confirmed.  There are techniques and practices for doing trusted builds, but these lie well outside my area of knowledge.

**Comment by boardhead** [comment]
The web site is back up again.  Explanation here:

https://exiftool.org/forum/index.php?topic=13078

- Phil

**Comment by Sponsoredby** [comment]
> Exiftool.org seems to be back up.
> 
> Q: Is the malware detection coming from software downloaded from Exiftool.org, or is it in your local copy of the code?

local copy in the /cache-exiftool-12.35/ folder offending file 25bbf886.dll

**Comment by boardhead** [comment]
> 2. It looks like Phil retired from Queen's University in Apr 2020, maybe retired the project? https://www.linkedin.com/in/phil-harvey-17806935/?originalSubdomain=ca ; either way not good for the project. Quick Google search found a Facebook with a Nov 28th post, so I believe he is alive. Which is good.

Yes, it is good that I am alive. :)

I did retire from Queen's in April last year, and moved the web site to DreamHost a few months prior to that.  I am still actively developing ExifTool.  It is DreamHost that has been the problem, and I'm trying to deal with that as best I can.

>  Is Phil struggling with something?

Not any more than anyone else. ;)  I was relaxing on a beach in Cuba for a week.  :)  I do take 1- and 2-week vacations a few times a year, and I try to put a notice in the ExifTool revision history page of the release prior to a vacation, but I didn't this time because it was a last-minute vacation deal.

- Phil

**Comment by danielhoherd** [comment]
Now would be a great time for a github.com/exiftool/exiftool to backfill all the recent releases of exiftool into GH releases

**Comment by timkatje** [comment]
@boardhead: Sorry if this has already been reported, but it looks like the site is totally down again.  In my case, I was attempting to run a chocolatey upgrade and the exiftool failed to update because of it.  If I were a pro user, the content might've been cached by chocolatey, but alas I no longer am.

Has there been any thought about just transferring all of the site data over here to GitHub Pages. Chocolatey would work great if all releases were just posted here, which could work in conjunction with an external website.  But migrating to GHPages might solve the site breaking every couple of years...

**Comment by danielhoherd** [comment]
In case the site goes down again...

> Note: If exiftool.org goes down, it is because of the crappy DreamHost web hosting which disables an "unlimited traffic" web site if a single bot hammers the site with a moderate load. An alternate ExifTool homepage is available at http://exiftool.sourceforge.net/

<img width="720" alt="Screenshot 2024-01-08 at 6 13 23 PM" src="https://github.com/exiftool/exiftool/assets/1323808/da546d74-e854-4d70-8c27-516e7d1bbec8">

**Comment by boardhead** [comment]
The site wasn't disabled again, and is back up now.  I don't know what happened, but I checked the server logs and it doesn't look like a site outage.

**Comment by Luuk34** [comment]
> The site wasn't disabled again, and is back up now. I don't know what happened, but I checked the server logs and it doesn't look like a site outage.

But that site no longer worked....

**Comment by StarGeekSpaceNerd** [comment]
There are websites that will check if a domain is down for everyone or just you.  For example, first google result for me is [IsItDownRightNow.com](https://www.isitdownrightnow.com/).

I refresh the forums many times during the day (helping people with exiftool problems is my Sudoku).  In the past week, there's been about two occasions where I've received a Server Load warning trying to view the forums and that disappeared when I tried again 10-15 minutes later.  It's been a much longer time since I've been unable to access the main page.

**Comment by danielhoherd** [comment]
The site is down again, and unfortunately the sourceforge mirror does not have the same file structure as exiftool.org. For instance, the download link listed at the top of https://exiftool.sourceforge.net/history.html does not work.

**Comment by danielhoherd** [comment]
@StarGeekSpaceNerd you're right. they must have blocked my IP address. shame on me for maintaining an exiftool ansible role.

**Comment by StarGeekSpaceNerd** [comment]
Phil will have to fix it.  The site blocks IPs that make too many requests

I'd say [see here](https://exiftool.org/forum/index.php?topic=15419.msg84167#msg84167), but you probably can't.

>I've implemented some limits to help deal with future attacks and misbehaving bots.

>With the current settings an automatic IP ban is applied to any non-member of the forum that exceeds 500 page loads or 50 MB of data in a 10 minute period.

>If you think you have been erroneously banned, send me an email (philharvey66 at gmail.com), but of course you will have trouble reading this post if that happened to you. :P

>Edit: I've also added a limit of 200 MB per day.

**Comment by boardhead** [comment]
A GPT bot was blocked 3 hours ago due to downloading 65.9 MB in 10 min, but that was the only ban added in the last few hours.  This ban will be automatically lifted tonight so if it was you it should work again tommorrow.

- Phil
