### ISSUE TITLE
-j flag strips information added by -ee

### ISSUE THREAD

**Issue by WookieMonkeys** [exiftool/exiftool#105]
When running `exiftool -ee ./file.mp4` i'm able to get multiple GPS points from the output; however, when running exiftool -ee -j ./file.mp4` only the first GPS point is recorded. Is this intended? Thanks.

**Comment by boardhead** [comment]
All field names in JSON must be unique.  Add -G3 to the command to include the document numbers in the field names if you want to see them all.

- Phil

**Comment by WookieMonkeys** [comment]
Thanks Phil. Exactly what I was looking for but couldn't find it in the docs. TY
