### ISSUE TITLE
New `5771` tag number in `%Image::ExifTool::Nikon::ZMenuSettings`

### ISSUE THREAD

**Issue by postscript-dev** [exiftool/exiftool#108]
Only a quick query. In the new [Nikon.pm](https://github.com/exiftool/exiftool/blob/d8fe987e32ed1c7659ed12f792ead936a4ad5b7f/lib/Image/ExifTool/Nikon.pm) file for the 12.37 release, is the [5771](https://github.com/exiftool/exiftool/blob/d8fe987e32ed1c7659ed12f792ead936a4ad5b7f/lib/Image/ExifTool/Nikon.pm#L8043) tag number correct? Based on the other tags above and below, I expected the tag number to be `577` or `577.1`.

**Comment by boardhead** [comment]
Great, thanks!  It should be 577.  This will be fixed in the next release.

- Phil

**Comment by postscript-dev** [comment]
Thanks Phil.

**Comment by boardhead** [comment]
Also, the name of this tag "MovieDiffrationCompensation" should have been "MovieDiffractionCompensation".  I'll fix this too.
