### ISSUE TITLE
Support for Zip:Comment

### ISSUE THREAD

**Issue by avolkov-astra** [exiftool/exiftool#109]
The Comment tag is claimed to be supported:
```
> exiftool -list -Zip:All
Available Zip tags:
  ArchivedFileName Comment CompressedSize Compression ExtraFlags Flags
  ...
```
But exiftool doesn't show it:
```
> cd /tmp
> echo "zip archive comment" > 1.txt
> zip --archive-comment 1.zip 1.txt < 1.txt
> zipinfo -z 1.zip
Archive:  1.zip
zip archive comment
...
> exiftool -Zip:Comment 1.zip
> 
```

P.S. Zip comment is sensitive metadata that can be removed by mat2.

**Comment by boardhead** [comment]
Good point.  ExifTool 12.39 will extract the zip file comments.

It showed up in the ZIP list only because it was available for other compressed-file formats (which are also in the ZIP group).

- Phil

**Comment by boardhead** [comment]
Note: In version 12.39, the comment will appear in the File group, not the ZIP group.

- Phil
