### ISSUE TITLE
Add Canon CRM colorspace metadata values

### ISSUE THREAD

**Issue by markreidvfx** [exiftool/exiftool#119]
Hi,
I've been working on adding CRM support to libraw and have identified a few metadata values that exiftool doesn't detect and are useful.  I'd submit a pull request myself but I don't know perl very well.

tag 0x4026 in the CMT3 atom,  36 bytes offset (last 12 bytes)
```
/* Has no effect on sensor data
     0 = BT.709  1 = BT.2020 2 = CinemaGamut 0x7fffffff = n/a*/
int32_t Colorspace;

/* Has no effect on sensor data
      0 = EOSOriginal 1 = Neutral  0x7fffffff = n/a*/
int32_t ColorMatrix;

/* CanonLog Version, Increases dynamic range of sensor data
      0 = OFF  1 = CLogV1 2 = CLogV2? 3 = CLogV3 */
int32_t CanonLog;
```

Also the [Quality ](https://exiftool.org/TagNames/Canon.html#CameraSettings) tag in camera settings can be used to tell the 
difference between StandardRaw and LightRaw

130 = LightRaw
131 = StandardRaw

here is collection of [samples files ](https://www.dropbox.com/sh/ty32q952xdzv3no/AAAIw1t7-ZRqH3TrpQoBfavMa?dl=0)

**Comment by boardhead** [comment]
Great, thanks!  Any suggestions for the name of the new 0x4026 data block?  Also, are "RAW Light" and "RAW Standard" OK for the Quality names?  And does it make sense that movies also show these values for Quality?

- Phil

**Comment by markreidvfx** [comment]
I think tag 0x4026 is the `Canon Log settings` menu on the r5. I've also just identify that Sharpness, Saturation and Hue are also in there and they part of the same menu. 
I'll report them here once I clarify their offsets.

canon DPP calls them `Standard(RAW)` and `Light(RAW)`. I've been calling them `StandardRaw` and `LightRaw`, but if you prefer your names better go ahead :p. 

I'm not sure if makes sense for non raw formats to show that, but the movie file would also have to have the` camera settings` tag. I haven't notice a non-raw movie with that tag, but I haven't been looking, could exist 🤷

**Comment by markreidvfx** [comment]
I checked and a non-raw mp4 from my camera and it seems to contain `camera settings` and the Quality tag.  Here is a example, so I guess it is possible

[2A5A3035.zip](https://github.com/exiftool/exiftool/files/7975361/2A5A3035.zip)

**Comment by markreidvfx** [comment]
```
int32_t Unknown0; // version? always seems to be 0x30
int32_t Unknown1; 
int32_t Unknown2; // always seems to be same value as Unknown1;
int32_t Unknown3; // reserved zero?

/*  0 = Editing (ALL-I)
    1 = Standard (IPB)
    2 = Light (IPB) 
    3 = Motion JPEG; 
    4 = RAW
        StandardRaw if Camera Settings Quailty == 131
        LightRaw    if Camera Settings Quailty == 130
*/
int32_t CompressionFormat; 

int32_t Unknown5; // reserved zero?

/* 0 -> 7 */
int32_t Sharpness;

/* -4 -> 4 */
int32_t Saturation;

/* -4 -> 4 */
int32_t Hue;

/* Has no effect on sensor data
     0 = BT.709  1 = BT.2020 2 = CinemaGamut 0x7fffffff = n/a*/
int32_t Colorspace;

/* Has no effect on sensor data
      0 = EOSOriginal 1 = Neutral  0x7fffffff = n/a*/
int32_t ColorMatrix;

/* CanonLog Version, Increases dynamic range of sensor data
      0 = OFF  1 = CLogV1 2 = CLogV2? 3 = CLogV3 */
int32_t CanonLog;
```

okay here is a update of what I've identified. I think CompressionFormat kind of solves the issue with using just the Quality tag.

**Comment by boardhead** [comment]
Great, thanks!!  I've updated my current version with your new additions and changed the Quality names to correspond with DPP.  I'm calling the new data block "LogInfo".

- Phil

**Comment by boardhead** [comment]
Looking at other Canon tags, the name ColorTone seems to be used instead of Hue.  So I'll use ColorTone to be consistent.

**Comment by markreidvfx** [comment]
Great! Thankyou!
