### ISSUE TITLE
Just a quick question for @StarGeekSpaceNerd

### ISSUE THREAD

**Issue by AshtonFM** [exiftool/exiftool#120]
The problem appears to be that you are trying to embed double quotes without escaping them.  Normally, you can escape a double quote by using a backslash `\"` or three double quotes `"""` but for some reason that double quote between the two semicolons is messing things up.

I'd suggest using the [`-E` (`-escapeHTML`) option](https://exiftool.org/exiftool_pod.html#E--ex--ec--escapeHTML--escapeXML--escapeC) and replace the double quotes with `&quot;`  

Example:    

```
C:\>exiftool -Comment="alert('$message');&quot;;} function_alert(&quot;Test&quot;); >;" -E  Y:\!temp\HashTest\Test.png 
    1 image files updated

C:\>exiftool -G1 -a -s -comment Y:\!temp\HashTest\Test.png
[PNG]           Comment                         : alert('$message');";} function_alert("Test"); >;
```

_Originally posted by @StarGeekSpaceNerd in https://github.com/exiftool/exiftool/issues/118#issuecomment-1019415172_

Do you have a discord or something I could contact you on in the future for help with exiftool?

**Comment by StarGeekSpaceNerd** [comment]
Sorry, no I don't.  But the [exiftool forum](https://exiftool.org/forum/) is the best place to get help.  I check it multiple times/day plus have several notifications for new stuff there.
