### ISSUE TITLE
"Error running more" error in command line upon installation

### ISSUE THREAD

**Issue by brianperlman** [exiftool/exiftool#121]
Hi there,

Longtime user of exiftool here. I'm having a problem installing exiftool on my Windows 10 machine. I followed the installation steps as outlined on the website exactly, but when I try to double click the exiftool(-k).exe file, I get this error on a popup Command Prompt:

`Error running more C:\Users\<my_username_here>\AppData\Local\Temp\par-75736d696c\cache-exiftool-12.39\exiftool_12.39_doc.txt`

Same issue when I change the filename to exiftool.exe. I run: `exiftool --version` in cmd, and it throws the same error:

`Error running more C:\Users\<my_username_here>\AppData\Local\Temp\par-75736d696c\cache-exiftool-12.39\exiftool_12.39_doc.txt`

Any help?

Thanks,
Brian

**Comment by StarGeekSpaceNerd** [comment]
First, try and delete the par directory in Temp (`%TEMP%\par-75736d696c` in this case).  Then try again.

If that doesn't work, check to see if your virus protection program is blocking exiftool.

You might also try [Oliver Betz's alternate build](https://oliverbetz.de/pages/Artikel/ExifTool-for-Windows) of exiftool.

**Comment by brianperlman** [comment]
Thanks for the quick response! Unfortunately, none of those things worked. I tried Oliver's build, and now I get an additional error when I try to run `exiftool --version` in the command prompt:

`Can't spawn "cmd.exe": No such file or directory at C:\Program Files\ExifTool\exiftool_files\exiftool.pl line 7186.
Error running more C:\Users\<my-user-name>\AppData\Local\Temp\exiftool_12.39_doc.txt`

Something must be very wrong, but I have no idea what. :(

**Comment by StarGeekSpaceNerd** [comment]
It looks like something beyond a normal exiftool problem.  Exiftool is, at its core, a Perl program.  While it isn't specifically about exiftool, [this StackOverflow](https://stackoverflow.com/a/27869684/3525475) answer has some possible solutions based that might fix the inability for Perl to call CMD.

**Comment by boardhead** [comment]
It may be that ExifTool works fine, but that it can't display the inline documentation.  The option to return the version number is "-ver".  Using "--version" will cause the documentation to be displayed since it isn't a valid option.

**Comment by brianperlman** [comment]
Many thanks, @StarGeekSpaceNerd and @boardhead (Phil), for your help! By some miracle, everything appears to be working now. No idea how I fixed it?    `¯\_ (ツ)_/¯`   Anyway, thanks again and hope you both have a great week!
