### ISSUE TITLE
Error 'Improperly enclosed XMP property', but 'exiftool -b -xmp' shows no output

### ISSUE THREAD

**Issue by QuantumLibet** [exiftool/exiftool#124]
Hello,

exiftool: v12.30
on macOS: 10.15.7 19H1715

The command

    exiftool '-AllDates=1980:01:01 10:00:00' filename.svg

fails with error:

    Error: [minor] Improperly enclosed XMP property: svg/image/xlink:href - filename.svg

Since the command works for all other files (jpeg's, heic's), I assumed a problem with the file.

<br>

Trying to show all properties:

    exiftool -b -xmp filename.svg

outputs nothing. Huh.

Trying to change the FileModifyDate with:

    exiftool '-FileModifyDate=1980:01:01 10:00:00+01:00' filename.svg

works fine. <br>

It seems to be just the '-AllDates' command, that fails. But why does the error point to the XMP properties?

An example file: https://user-images.githubusercontent.com/76904954/156145920-df16d3c1-af82-4c94-b044-15bb2586d655.svg

**Comment by QuantumLibet** [comment]
My bad. Closed. I forgot to check the supported filetypes list. SVG is listed explicitly as read only.
Sorry.

**Comment by boardhead** [comment]
WIth ExifTool 12.40 you get a more meaningful message:

`Error: ExifTool does not yet support writing of SVG images`

- Phil
