### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by thedroiddiv** [exiftool/exiftool#129]
Is there currently Android support?
If yes can anyone please tell me? 
I searched a lot for an alternative Android Library but found no one as useful as these. I really love using it on PC, but I need to embed it on Android. If there is any workaround, please share it here as well.

**Comment by StarGeekSpaceNerd** [comment]
There's probably not going to be any official support  but there's at least [one port for android](https://play.google.com/store/apps/details?id=com.exiftool.free).

**Comment by StarGeekSpaceNerd** [comment]
Alternatively, you could find a Android port of Perl and use that to run exiftool.  That's probably what is at the core of the above app.

**Comment by divyansh-dxn** [comment]
That is a great alternative. It works, but the issue is with API level > 28, Android doesn't allow to run of executables through the system process. But still, it is working now.
