### ISSUE TITLE
After cleaning metadata, size of PDF file increased

### ISSUE THREAD

**Issue by karam72** [exiftool/exiftool#130]
Hi,

I have a PDF file. It is a simple file because I scan a paper from my scanner device. It created me a PDF file.

My system:
- Fedora 35 - 64 bit
- Exiftool 12.40
- Perl 5.34.0

Command:

> exiftool -d -all= '/path/to/file.pdf'

Output

```
ExifTool Version Number         : 12.40
File Name                       : file.pdf
Directory                       : /path/to
File Size                       : 247 KiB
File Modification Date/Time     : -all=
File Access Date/Time           : -all=
File Inode Change Date/Time     : -all=
File Permissions                : -rw-r--r--
File Type                       : PDF
File Type Extension             : pdf
MIME Type                       : application/pdf
PDF Version                     : 1.4
Linearized                      : No
Page Count                      : 1
Create Date                     : -all=
```

When I want to remove metadata using below command:

> exiftool -v -all= '/path/to/file.pdf'

The output shows that the file changed:

```
======= /path/to/file.pdf
Rewriting /path/to/file.pdf...
  Editing tags in: * AFCP APP0 APP1 APP10 APP11 APP12 APP13 APP14 APP15 APP2 APP3 APP4 APP5 APP6 APP7 APP8 APP9 CIFF CanonVRD Comment Ducky ExifIFD FlashPix FotoStation GPS ICC_Profile IFD0 IPTC Insta360 ItemList JFIF Jpeg2000 Keys MIE MPF MakerNotes MetaIFD Microsoft NikonApp NikonCapture PDF PNG PNG-pHYs PhotoMechanic Photoshop PrintIM QuickTime RMETA RSRC Trailer UserData XML XML-* XMP 
  Deleting PDF Info dictionary
  (XMP not changed -- still empty)
  Warning = [minor] ExifTool PDF edits are reversible. Deleted tags may be recovered!
Warning: [minor] ExifTool PDF edits are reversible. Deleted tags may be recovered! - /path/to/file.pdf
    1 image files updated
```

But the above output with the new file is same. Nothing seems changed. But I checked the file size from file manager. The file of PDF has been increased about 0.2 KB. 

I am confused for below things:

- Why the file size increased?

- It seems something cleaned on the file. But why exiftool does not show me that information with "-d -all" ?

- As you can see on the above output, all the "date" variables are "-all". What that means?

Thank you

**Comment by StarGeekSpaceNerd** [comment]
See the [PDF tags page](https://exiftool.org/TagNames/PDF.html).

Exiftool uses an incremental update technique.  This means it does not completely remove metadata and allows for the changes to be reversible.  So any changes are going to increase the size of the file, even "removal" of data.  [This Foxit.com page](https://developers.foxit.com/developer-hub/document/incremental-updates/) has a good write up of the process.

To completely remove the data, you need to re-linearized the file.  This will complete remove the any previous data and should shrink the file size.  As mentioned on the PDF tags page, [qpdf](https://github.com/qpdf/qpdf), which is available for Windows, Linux, and Mac, can do this on the command line.  There are probably other programs that can do this as well.

**Comment by StarGeekSpaceNerd** [comment]
With regards to time stamps, the problem is that the [`-d` (`-dateFormat`) option](https://exiftool.org/exiftool_pod.html#d-FMT--dateFormat) *requires* a second parameter.  A format string detailing how the time stamp is to be formatted.  In this case, you are setting the the format as a static string, `-All=`.  So all the time stamps in the output are going to be set to that static string.  This is not how the data is actually embedded the file.

**Comment by karam72** [comment]
Thank you so much :)
