### ISSUE TITLE
aac not detect

### ISSUE THREAD

**Issue by mhf-ir** [exiftool/exiftool#132]
it's alpine latest docker container

Sample file is: https://github.com/gabriel-vasile/mimetype/blob/master/testdata/aac.aac

```
/testdata # exiftool -ver
12.30
/testdata # file -b --mime-type aac.aac 
audio/x-hx-aac-adts
/testdata # exiftool -n -json aac.aac 
[{
  "SourceFile": "aac.aac",
  "ExifToolVersion": 12.30,
  "FileName": "aac.aac",
  "Directory": ".",
  "FileSize": 33704,
  "FileModifyDate": "2022:04:08 15:08:00+00:00",
  "FileAccessDate": "2022:04:10 00:12:50+00:00",
  "FileInodeChangeDate": "2022:04:08 15:08:00+00:00",
  "FilePermissions": 100664,
  "Error": "Unknown file type"
}]
/testdata # 
```

**Comment by boardhead** [comment]
Quite right.  ExifTool doesn't currently support the AAC file format.

**Comment by dkbarn** [comment]
For what reason? Any further details you can share?

**Comment by boardhead** [comment]
AAC doesn't support metadata, so adding support is of limited usefulness, but I'll do this in the next release (12.72).

- Phil
