### ISSUE TITLE
Publish on winget-pkgs

### ISSUE THREAD

**Issue by framctr** [exiftool/exiftool#133]
Publish the Windows executable on the Windows Package Manager Community Repository to be used with `winget`. Does not require any modification to the original code, but a manifest file. Community repo with the submitting process is on [GitHub](https://github.com/microsoft/winget-pkgs).

**Comment by boardhead** [comment]
I'll leave this to someone else to do.  ExifTool is currently part of far too many package managers, all maintained by other ExifTool users.
