### ISSUE TITLE
Create non-editable tag

### ISSUE THREAD

**Issue by sanjain-progress** [exiftool/exiftool#137]
Is it possible to create a non-editable tag? I can create custom tags with this tool, but they are easily editable by any editor.

Tags such as `primary platform`, `profile creator`, and `primary platform` are not editable. Similarly, I need to create the tag example `image id`.

If yes then How can I achieve this?

**Comment by StarGeekSpaceNerd** [comment]
No, it is not possible to create a non-editable tag.

There are pretty much only two reasons a tag isn't editable by exiftool.  First, if the tag is a fundamental property of the file.  For example, `ImageWidth`/`ImageHeight` can't be simply edited.  You have to actually edit the image/video to change the size.  Second, exiftool has not been coded to edit that tag.  In the case of your examples, those are part of an `ICC_Profile`.  It is technically possible to add the ability to edit ICC_Profile tags, but ICC_Profiles are complex and it would require a lot of time to code it with little return for doing so.

And though it might be difficult, files can always be edited by a hex edit program, making it impossible to prevent any edit to a file if someone is determined enough.
