### ISSUE TITLE
Semi-crash of exiftool 11.88 on input file containing a mix of binary and plain text.

### ISSUE THREAD

**Issue by andreas-kupries** [exiftool/exiftool#138]
exiftool -ver = 11.88 as installed for Ubuntu 20.04.4 LTS (Focal Fossa).

Base64 decode the attached [boom.base64.txt](https://github.com/exiftool/exiftool/files/8682247/boom.base64.txt) file.
Assuming the decoded file is saved to `boom.txt`, invoking

> exiftool boom.txt

results in some kind of internal error message. Specifically:

> 'x' outside of string in unpack at /usr/share/perl5/Image/ExifTool.pm line 4887.

The original file is `50FINAL.DOC` from https://www.fanfics.dev/1997-01/messages/Attachments-23/, the FFML archives.

The attached reduces this from 7K to about 0.5K. No claim is made that this is actually minimal.

**Comment by boardhead** [comment]
The current version of ExifTool (12.41) doesn't have this problem.
