### ISSUE TITLE
cannot read file in folder with special characters

### ISSUE THREAD

**Issue by qontolmabur** [exiftool/exiftool#139]
i'm using windows, tried to create context menu in registry with batch file
```
REG ADD "HKCR\*\shell\ExifTool" /t REG_SZ /d "&ExifTool" /f
REG ADD "HKCR\*\shell\ExifTool" /v Icon /t REG_SZ /d "%programfiles%\CLI\ExifTool\exiftool.exe,0" /f
REG ADD "HKCR\*\shell\ExifTool\command" /t REG_SZ /d "\"%systemroot%\system32\cmd.exe\" /K exiftool \"%%L\"" /f
```

it works just fine if the file is under standard named folder, but doesn't work if the file is under a folder with special characters, in my case the special character is **Δ**

the error shows :
```
Wildcards don't work in the directory specification
No matching files
```

 but if i run command prompt/cmd on that directory _(directory with special characters)_ , and then type `exiftool <filename>`, it works just fine _(exiftool can read the file and show information about the file)_

Left side is the screenshot of error (running exiftool from context menu) - right side is the screenshot of successful (running exiftool in already opened cmd)
![image](https://user-images.githubusercontent.com/105628001/168538998-66daf723-00af-4ed7-8cdc-335ad08b97d6.png)

**Comment by qontolmabur** [comment]
for those who have the same problem creating context menu, my current workaround is
````
REG ADD "HKCR\*\shell\ExifTool\command" /t REG_SZ /d "cmd /K\"TITLE ExifTool^&FOR /F \"usebackq tokens=*\" %%%%X IN (`ECHO %%1`) DO (CD /D \"%%%%~dpX\"^&^&CLS^&^&exiftool \"%%%%~nxX\")\"" /f
````

**Comment by boardhead** [comment]
This doesn't appear to be an ExifTool issue
