### ISSUE TITLE
Support for GP1, MVI, and MVN tags in ID3v2.2

### ISSUE THREAD

**Issue by beardgoggles** [exiftool/exiftool#142]
Would it be possible to add the iTunes `GP1`, `MVI`, and `MVN` ID3v2.2 tags that correspond with iTunes' ID3v2.3/v2.4's `GRP1`, `MVIN`, and `MVNM` tags?

From what I can see they're just text strings, behaving much like `TT1` or `TRK`, so I assume they could be lumped together with the `^T` and `IPL|IPLS` tags for processing?

`} elsif ($id =~ /^T/ or $id =~ /^(IPL|IPLS|GP1|MVI|MVN)$/) {`

**Comment by boardhead** [comment]
This will be added in 12.70.  Sorry for the delay in getting around to this.

- Phil
