### ISSUE TITLE
Language XMP Tag

### ISSUE THREAD

**Issue by Korb** [exiftool/exiftool#143]
> Individual languages for lang-alt tags are accessed by suffixing the tag name with a '-', followed by an RFC 3066 language code (eg. "XMP:Title-fr", or "Rights-en-US"). (See http://www.ietf.org/rfc/rfc3066.txt for the RFC 3066 specification.) A lang-alt tag with no language code accesses the "x-default" language, but causes other languages for this tag to be deleted when writing. The "x-default" language code may be specified when writing to preserve other existing languages (eg. "XMP-dc:Description-x-default"). When reading, "x-default" is not specified.

https://exiftool.org/TagNames/XMP.html

RFC5646:

> This document replaces [RFC4646] (which obsoleted [RFC3066] which, in turn, replaced [RFC1766]).

https://www.ietf.org/rfc/rfc5646.txt

**Comment by boardhead** [comment]
Thanks, but I don't see the point in wasting time chasing new versions of this RFC.

**Comment by Korb** [comment]
@boardhead, I respect your right to prioritize the process of modifying your non-commercial project. Perhaps [my quote](https://github.com/exiftool/exiftool/issues/143#issue-1266012133) will only be useful to complement [the help system](https://exiftool.org/TagNames/XMP.html), which will mention changes in the standard that are not fully reflected in the appendix.

**Comment by boardhead** [comment]
There are bigger problems with this documentation since Adobe keeps moving the location of the XMP specification. :(
