### ISSUE TITLE
Missing Tags

### ISSUE THREAD

**Issue by dominiklippl** [exiftool/exiftool#146]
Hello, I am currently trying to extract all the metadata of an image into an XML file. 
For this I used the following command, `exiftool -tagsFromFile IPTC-PhotometadataRef-Std2021.1.jpg -all:all -U metadata.xml`.
This should normally extract all meta information according to the documentation, but unfortunately this is not completely the case. In particular, I am missing the AltTextAccessibility, AltTextAccessibility-en.
For testing I used the attached picture. 

![IPTC-PhotometadataRef-Std2021 1](https://user-images.githubusercontent.com/36797134/177564602-28af4586-2742-41eb-aa2f-44a6ef22d9f8.jpg)

**Comment by StarGeekSpaceNerd** [comment]
The image you link contains the tags you list and exiftool extracts them properly

`C:\>exiftool -G1 -a -s -Alt* Y:\!temp\ccc\c\177564602-28af4586-2742-41eb-aa2f-44a6ef22d9f8.jpg`
`[XMP-iptcCore]  AltTextAccessibility            : This is the Alt Text description to support accessibility in 2021.1`
`[XMP-iptcCore]  AltTextAccessibility-en         : This is the Alt Text description to support accessibility in 2021.1`

What is the contents of your `metadata.xml` in your original command?

**Comment by dominiklippl** [comment]
But you don't used the `exiftool -tagsFromFile` command to extract the metadata.
Here is my `metadata.xml` file, https://pastebin.com/fccVgEeG.

**Comment by dominiklippl** [comment]
Right, I also just noticed that the command is wrong, I have edited my question and corrected the command. 
I think I need to take a moment and explain what I'm trying to do in the first place. 
I want to use exiftool to read the metadata from an image and store it in a database (MongoDB) in a structured way. 
My approach is to extract the data via `exiftool -tagsFromFile IPTC-PhotometadataRef-Std2021.1.jpg -all:all -U metadata.xml` into a XML file (https://pastebin.com/fccVgEeG), read it via the system, convert it into a JSON object (https://pastebin.com/qYDN6PWu) and store it in the database. 
This mechanism is already implemented and works, I just noticed that the AltTextAccessibility and AltTextAccessibility-en text is missing.

**Comment by StarGeekSpaceNerd** [comment]
My output when running your command [includes these tags](https://pastebin.com/3kmGYkSV).  The only thing that I can figure is that you're running a version of exiftool that's older than ver 11.74, over 2½ years old, as that is when support for IPTC Extension version 1.5 tags was added.

You might instead want to look into either the [`-X` (`-xmlFormat`) option](https://exiftool.org/exiftool_pod.html#X--xmlFormat) or the [`-j` (`-json`) option](https://exiftool.org/exiftool_pod.html#j-JSONFILE--json).  The command you're using creates an XMP file, not an XML file, and will not contain any tags that exiftool doesn't know how to write.  Either of these options will include these other tags.

**Comment by dominiklippl** [comment]
Ok, I got the terms mixed up, sorry. I need an XMP file not an XML. 
But I still don't understand why the Alt text should not be in the XMP file, the AltTextAccessibility text is part of the IPTC core (https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#alt-text-accessibility) in the XMP specification (http://iptc.org/std/photometadata/specification/iptc-pmd-techreference_2021.1.yml) it is also listed.

**Comment by StarGeekSpaceNerd** [comment]
I had to double check, but I was incorrect about the version.  The `AltTextAccessibility` was added in [version 12.33](https://exiftool.org/history.html#v12.33).  If your command isn't writing those tags, it must be older than ver 12.33.  You will need to upgrade to a newer version if you want to write them.

Run
`exiftool -ver`  
to check the version

**Comment by dominiklippl** [comment]
Thank you very much, that was the solution. I still had the version `12.30`, after upgrading to `12.42` the tags appeared. Thanks again for your help.
