### ISSUE TITLE
Photoshop 2020+ is unable to open TIFF after copying clipping paths inside the image

### ISSUE THREAD

**Issue by fire1** [exiftool/exiftool#147]
Hi!
When I copy clipping paths from a JPG to a TIF image Photoshop 2020-2021 gets the error "Cannot open because of a program error."
Photoshop CS6 is opening those files just fine, saving the files from CS6 fixes the image. 
(Thanks to Adobe older programs like CS6 cannot be installed on newer Macs)

I'm using Exiftool 12.16 with  this command to copy paths:
` exiftool -config photoshop_paths.config -tagsfromfile SRC -allpaths# -originpathinfo DST`

I can provide such a broken image if needed, also the same image but saved from CS6.

_Thanks for your attention ..._

**Comment by boardhead** [comment]
I don't know if the samples will help, but sure, send them to me (philharvey66 at gmail.com).

This should really be reported to Adobe.

In the past I have seen an Adobe bug which prevented loading images due to metadata reader bugs which balked at time zone of +00:00, so maybe this is something like that.

- Phil

**Comment by boardhead** [comment]
There are many differences between the two sample files, and I can't see anything obvious that might be causing the problem.  The way to narrow this down is to incrementally change the metadata from one file until it matches the other until you find the exact piece of metadata that causes the problem.  If you do this you could be more specific in your bug report to Adobe, but that's the only real advantage.  Both files open fine in my version of Photoshop (CS4), but I don't have Photoshop 2020+ to test this with.
