### ISSUE TITLE
Wrong file type for Java class file

### ISSUE THREAD

**Issue by doronshemtov** [exiftool/exiftool#149]
When a [Java class](https://en.wikipedia.org/wiki/Java_class_file) file is processed, it gets a `Mach-O fat binary executable` file type.

https://github.com/exiftool/exiftool/blob/1e17485cbb372a502e5b9d052d01303db735e6fa/lib/Image/ExifTool/EXE.pm#L1234-L1236

Java class and Mach-O fat binary executable have the same magic number (`CA FE BA BE`), so additional test should be performed in order to distinguish between these types.

Here is a reference that could be helpful:
https://github.com/file/file/blob/master/magic/Magdir/cafebabe#L6-L15

**Comment by boardhead** [comment]
Thanks!  I'll patch ExifTool 12.45 to return the proper file type for Java bytecode files.

**Comment by boardhead** [comment]
Released on Sep. 16, 2022
