### ISSUE TITLE
Pentax AutoBracketing decoding on K-5, K-1

### ISSUE THREAD

**Issue by jeegit** [exiftool/exiftool#15]
Using
```
$ ./exiftool -ver
11.38
```
on Debian 9, Pentax AutoBracketing is incorrectly decoded for Pentax K-5 and K-1, which both encode it consistently as below.

Setting exposure steps to 1/3EV, the value recorded by the camera is 8192 + number of EV steps, e.g. 8196 for 1.3EV bracketing. K-5 example output for 1/3EV setting, 1.3EV steps (example including extended bracketing, which is correctly decoded):
```
$ ./exiftool -v  /media/jens/K-5/DCIM/126_2504 IMGS9879.JPG |grep AutoBracketing  | | | 17) AutoBracketing = 8196 259
$ ./exiftool -G0 -AutoBracketing -ExposureBracketStepSize /media/jens/K-5/DCIM/126_2504/IMGS9879.JPG 
[MakerNotes]    Auto Bracketing                 : 8186.5 EV, WB-BA+3
[MakerNotes]    Exposure Bracket Step Size      : 1.3
```
Setting exposure steps to 1/2EV, the value recorded by the camera is 4096 + number of EV steps, e.g. 4099 for 1.5EV bracketing:
```
$ ./exiftool -v  /media/jens/K-1/DCIM/113_2504/IMGC2093.DNG |grep AutoBracket
  | | 17) AutoBracketing = 4099 0
$ ./exiftool -G0 -AutoBracketing -ExposureBracketStepSize /media/jens/K-1/DCIM/113_2504/IMGC2093.DNG
[MakerNotes]    Auto Bracketing                 : 4089.5 EV, No Extended Bracket
```
Btw., the K-1 doesn't have the Exposure Bracket Step Size nor Bracket Shot Number (which I was looking for in the first place) in the same place as previous models, nor could I identify any likely candidates.

Let me know if you need any examples.

**Comment by boardhead** [comment]
Thanks for this report.  ExifTool 11.39 will decode AutoBracketing properly for these models.

- Phil
