### ISSUE TITLE
Needs better documentation and examples

### ISSUE THREAD

**Issue by CHJ85** [exiftool/exiftool#150]
Hi there. I've been trying to change the metadata for things like file size.But I keep getting errors.
I tried exiftool 00-1.png -File Size=5 MiB
Then I tried exiftool 00-1.png -File_Size=5 MiB
This gave me Warning: Tag 'File_Size' is not defined
Then I tried in quotations. Same result.
When I type in exiftool -h to see if it would give me commands with examples or something. But no.
All it gives me is Syntax:  exiftool [OPTIONS] FILE

Very frustrating.
Please do something about this. Because I hate it whenever a command line tool becomes a guessing game.
Command line tools are already complicated enough as it is.

**Comment by StarGeekSpaceNerd** [comment]
There are a lot of examples in the [documentation](https://exiftool.org/exiftool_pod.html#READING-EXAMPLES) as well as over 12 years of examples in the [forums](https://exiftool.org/forum/).

The `FileSize` is not writable.  See the [Extra Tag Names page](https://exiftool.org/TagNames/Extra.html).  Exiftool knows over 25,000 different tags and lists which ones are writable under the [various Tag Names subpages](https://exiftool.org/TagNames/).

`FileSize` is the size of the file on the drive and isn't something you could arbitrarily change anyway.  It's part of the underlying file system.

Also see the [FAQ page](https://exiftool.org/faq.html).  Specifically [FAQ #2](https://exiftool.org/faq.html#Q2), as you're mistaking a tag description, which will change depending upon which language exiftool has be set to, for a tag name, which will never have a space in it.

**Comment by CHJ85** [comment]
@StarGeekSpaceNerd Thank you.
Is there a way to "fake" the filesize metadata.
The reason I want to fake the file size is because the server that I'm uploading images to only allows 10 mb. So I'm trying to figure out a way to bypass this without having to decrease the image quality and use all kinds of compression.

**Comment by StarGeekSpaceNerd** [comment]
You can pad it with junk data to make it bigger, but you can't make it smaller without doing some sort of recompression.  If it's a PNG image, you can look into programs like [OptiPng](http://optipng.sourceforge.net/), which may losslessly compress it a bit better.  A jpeg would need to be recompressed, losing some of the image quality in doing so.

**Comment by CHJ85** [comment]
Wait. So OptiPng can compress it losslessly? Interesting. I didn't think that was possible.
Thank you.

**Comment by StarGeekSpaceNerd** [comment]
It can optimize PNG files, but not jpegs.  PNG files can have varying levels of compression and OptiPng does so by running a lot of calculations to figure out the very best level of compression.

**Comment by CHJ85** [comment]
Thank you @StarGeekSpaceNerd
