### ISSUE TITLE
Odd FileNumber behavior when using -n [v12.44]

### ISSUE THREAD

**Issue by cbckly** [exiftool/exiftool#151]
I'm trying to consistently extract FileNumber over my 5 or so different cameras of the last two decades and so far I've found it in two separate sections but the **-n** flag treats them differently leaving the dash in for Composite and removing it for MakerNotes.  

C:\apps\exiftool>C:\apps\exiftool\exiftool -filenumber -s -G img_0459.jpg
[Composite]     FileNumber                      : 100-0459

C:\apps\exiftool>C:\apps\exiftool\exiftool -filenumber -s -G img_0459.jpg -n
[Composite]     FileNumber                      : 100-0459

C:\apps\exiftool>C:\apps\exiftool\exiftool -filenumber -s -G img-0200.jpg
[MakerNotes]    FileNumber                      : 176-0200

C:\apps\exiftool>C:\apps\exiftool\exiftool -filenumber -s -G img-0200.jpg -n
[MakerNotes]    FileNumber                      : 1760200

**Comment by StarGeekSpaceNerd** [comment]
The `Composite:FileNumber` is a value derived from either the `FileIndex` and/or `DirectoryIndex ` tags.   See the [Composite Tags Page](https://exiftool.org/TagNames/Composite.html).  To get more details, you should check those tags for the raw values.

The `FileNumber` is the number actually embedded in the MakerNotes.  This is not necessarily standard, especially if you're comparing different cameras, even from the same manufacturer.

**Comment by boardhead** [comment]
I see the inconsistency.  I'll remove the "-" from the Composite:FileNumber when -n is used.

- Phil

**Comment by boardhead** [comment]
Patch included in version 12.45, released Sept. 16, 2022.
