### ISSUE TITLE
[Suggestion] On the "1,000 or 1,024" affairs (Byte counting)

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#152]
Follow-up [ [https://exiftool.org/forum/index.php?topic=11849](https://exiftool.org/forum/index.php?topic=11849) ].

    [ [https://exiftool.org/history.html#v12.42](https://exiftool.org/history.html#v12.42) ]: "Changed ExifTool FileSize print conversion to use kB/MB/GB units instead of KiB/MiB/GiB".
    The change probably should be reverted and consider the suggested approach:
    .
    Adding a new option named "-byteunit" [1] accepting the below options:
    /(?:(?:0|IT|it)(&#x2A;:0)|(?:1|SI|si)(&#x2A;:1)|(?:2|[Bb]oth)(&#x2A;:2))(?&Plus)(?(DEFINE)
    (?&lt;Plus>(?:&#x5C;+(?{ $Plus = 1; }))?) )/.
[1] Exact definition: /-([Bb])yte(?(?{ $1 eq "B" })U|[uU])nit/.
[ [2]
    For help, see:
    |&#x2A;| [https://regex101.com/](https://regex101.com/)
    |&#x2A;| [https://perldoc.perl.org/perlre](https://perldoc.perl.org/perlre) ]

    Case 0: Use the IT style counting (1,024).
    Case 1: Use the typical SI style counting (1,000).
    Case 2: Display both, e.g. "1 KiB (1.03 KB)" (round-up (ceil); 2 digits after fraction point, excessive 0 stripped).
    .
    If $Plus == 1, also display the count in Bytes; e.g.
    |0| "1,000 MiB (1,048,576,000 Bytes)"
    |1| "1 KB (1,000 Bytes)"
    |2| "0.98 KiB (1 KB) (1,000 Bytes)"
    Note: fringe case "1 Byte".

    Default for "-byteunit" using "0+".

[ Note:
    The Perl RegEx above are mostly intended to describe the logic, not specifically created for Perl implementation (though syntactically valid). ]
\
\
=== Background ===

    The KiB series units originated from the similar K, M, G, ... alike prefixes in SI unit:
    Intended to achieve very similar purpose but slightly different in implementation:
    They instead represent the digit shifting in binary view rather than decimal. (thus using (( 2^10 = 1,024 )) alike instead of (( 10^3 = 1,000 )) )
    .
    The usage is much inclined to computer systems thus the "i" in the name. (stands for Informatics (or Informatique, if French is preferred) )

    Note using "k" as the prefix may be misleading, as the lowercase typically indicates downscaled magnitude.
    E.g. "mV" [ (( 10^-3 = 0.001 )) V ] and "MV" [ (( 10^6 = 1,000,000 )) V ] as voltage unit.

    The definition initially used identical names as those of the typical SI definition. Which is later proven problematic thus the new "i" type names.
\
\
=== References ===

    &#x60;ls&#x60; # "-h" ("--human-readable")
    https://www.gnu.org/software/coreutils/manual/coreutils.html#index-_002dh-4
    [ Menu: [https://www.gnu.org/software/coreutils/manual/html_node/index.html](https://www.gnu.org/software/coreutils/manual/html_node/index.html) ]

    GNU CoreUtils' definition on KiB, MiB, etc.
    https://www.gnu.org/software/coreutils/manual/html_node/Block-size.html#index-kilobyte_002c-definition-of

    https://en.wiktionary.org/wiki/kilobyte?oldid=68668541

**Comment by boardhead** [comment]
I didn't really like changing this in the first place because of potential backward-compatibility issues, but anyone interested in seeing the exact file size should be using the -n option or -fileSize# to get the numerical value in number of bytes.  I don't want to change the default again, but perhaps adding an option to allow other modes would be good.  However, your suggesting is perhaps a bit more complex than necessary, but I'll think about maybe implementing something along these lines.  

Thanks for the suggestion.

**Comment by MasterInQuestion** [comment]
The change in v12.42 should regardless cause such backward compatibility issues anyway.
    As the concern doesn't seem to be very critical after all: stepping a bit further shouldn't make much difference.

    The suggestion much unambiguously defined every significant detail.
    Some are indeed more complex than minimum necessary (to just work), but each design has a purpose.

**Comment by boardhead** [comment]
OK. I'm finally getting around to implementing this.  Version 12.70 will have a new API BinaryPrefixes option which allows you to use binary prefixes if you want.

**Comment by MasterInQuestion** [comment]
The API option may be implemented as ByteUnit utilizing the definition above.
    In addition with the "-byteunit" CLI shortcut.

    I may help the later part after you finished the minimal BinaryPrefixes.

**Comment by boardhead** [comment]
I don't want to add a new CLI option -- the CLI documentation is already too lengthy.

Also, I don't think a "Both" option is necessary.

So I was hoping that the minimal BinaryPrefixes would be sufficient.

- Phil

**Comment by MasterInQuestion** [comment]
At will.
    Though the documentation issue is a different problem.
    The "Both" is primarily a placebo: hard to tell its use, merely there for its potential use.

**Comment by boardhead** [comment]
OK.  To keep the "Both" available as a future option, I'll use your suggestion of "ByteUnit" for the option name, with "Metric" as the default setting.

- Phil

**Comment by MasterInQuestion** [comment]
"Metric" is probably not well understood under this context. (potentially ambiguous)
    "IT" and "SI" would be the most appropriate.

**Comment by boardhead** [comment]
Thanks.

**Comment by boardhead** [comment]
I did some googling, and I prefer "Binary" over "IT" since it seems more common.  But you are right about "SI" being preferred over "Metric".

**Comment by MasterInQuestion** [comment]
Strictly binary is merely an interpretation: everything can be binary.
    Same applies to those so called "binary" files... (typical description to non Plain Text)

    Further reading:
    Hard disk is not necessarily hard nor involves disk...

**Comment by boardhead** [comment]
This is implemented in version 12.70
