### ISSUE TITLE
Potential ExifTool recursion issue with `.crw` file

### ISSUE THREAD

**Issue by postscript-dev** [exiftool/exiftool#153]
While running ExifTool on the exiv2 test files, I couldn't process https://github.com/Exiv2/exiv2/commits/main/test/data/issue_1097_poc.crw . I think that the file may have been created to demonstrate a recursion bug so this may be an artificial example.

My setup:
- ucrt64/MSYS2 on Windows 11
- ExifTool 12.42
- Perl 5.32.1 (from MSYS2 pacman)

The command that I used to trigger the issue is:
```bash
$ exiftool -flashinfoversion test/data/issue_1097_poc.crw
Deep recursion on subroutine "Image::ExifTool::CanonRaw::ProcessCanonRaw" at /c/msys64/home/postscript-dev/bin/lib/Image/ExifTool.pm line 7865.
Deep recursion on subroutine "Image::ExifTool::ProcessDirectory" at /c/msys64/home/postscript-dev/bin/lib/Image/ExifTool/CanonRaw.pm line 672.
Out of memory!
```
My laptop has 8GB of memory and the test file is only 4.8K.

I don't know if the file indicates a useful bug, but it doesn't cause any problems for me. I am happy simply to log the issue.

**Comment by boardhead** [comment]
Yes, malicious files may definitely be crafted to cause ExifTool to hang.

I'll look into adding a patch for this one.

- Phil

**Comment by boardhead** [comment]
ExifTool 12.46 will patch this issue

**Comment by postscript-dev** [comment]
Great, thanks for looking at this. I will close this issue.
