### ISSUE TITLE
[feature] shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [exiftool/exiftool#155]
How about adding shell completion for bash/zsh/fish/posh/etc? Just like [parallel](https://git.savannah.gnu.org/cgit/parallel.git/tree/src/parallel#n1583) (A same program written by perl which has shell completions)

**Comment by boardhead** [comment]
You mean completion for ExifTool options when entering commands?  I don't know how useful this would be because there are more than 16000 unique tag names which may be used as options.

- Phil

**Comment by StarGeekSpaceNerd** [comment]
> there are more than 16000 unique tag names which may be used as options.

And if you add in variations by groups, significantly more combos.  `Description` alone would include
`Description`
`XMP:Description`
`XMP-dc:Description`
`Image:Description`
`ID-description:Description`

And then, more options for an Alt-Language tag such as this
`Description-x-default`
`Description-en`
`Description-en-US`
`Description-fr`

**Comment by boardhead** [comment]
Dead issue
