### ISSUE TITLE
Compacting XMP data

### ISSUE THREAD

**Issue by da2x** [exiftool/exiftool#16]
exiftool writes metadata to PNG and JPEG files in separate RDF objects grouped by their namespaces. Is there a historical reason for writing it in this format?

E.g. `-rdf-ns1:tag1=Value1 -rdf-ns2:tag2=Value2` outputs something like this;

```
<rdf:RDF about="https://example.com/photo" xmlns:ns1="https://example.net/#">
  <ns1:tag1>Value1</ns1:tag1>
</rdf:RDF>
<rdf:RDF about="https://example.com/photo" xmlns:ns2="https://example.org/#">
  <ns2:tag2>Value2</ns2:tag2>
</rdf:RDF>
```

Would it be possible to switch to a compacted format instead?

```
<rdf:RDF about="https://example.com/photo"  xmlns:ns1="https://example.net/#" xmlns:ns2="https://example.org/#">
  <ns1:tag1>Value1</ns1:tag1>
  <ns2:tag2>Value2</ns2:tag2>
</rdf:RDF>
```

The two representations are technically identical but one adds less weight to the output files. The XMP specification uses the more compact form in almost all examples.

**Comment by boardhead** [comment]
ExifTool uses a single rdf:RDF element when writing.  However, your example isn't enclosed in an rdf:Description as it should be.  ExifTool does use separate rdf:Descriptions for the different namespaces because that is what Photoshop did at the time when the XMP writing ability was added to ExifTool.

**Comment by boardhead** [comment]
ExifTool 11.52 gives you the ability to combine all properties into a single rdf:Description element with this command-line option:  `-api compact=3`

For the smallest XMP possible, set `-api compact=5`

**Comment by da2x** [comment]
Thank you for resolving this!
This was exactly what I wanted and your work is greatly appreciated.

I omitted the outer `rdf:Descriptions` in an attempt to highlight the differences in a smaller example. I hope that didn’t cause too much confusion.
