### ISSUE TITLE
Bug: Approximate duration doubled on mp3 files

### ISSUE THREAD

**Issue by Domi250** [exiftool/exiftool#160]
Hi, I think I found a bug in exiftool version 12.16 concerning mp3 metadata. I don't know if its already fixed in newer versions, I'm sorry if that's the case.

```exiftool "Mono Inc. - Voices of Doom.mp3"```
prints
```Duration                        : 0:10:03 (approx)```
Which is twice the correct amount of time (0:05.01). This happens to me with any mp3 file downloaded with spotdl (I don't have any other mp3s to test it with). **ffprobe** delivers the correct time for this file: ```duration=301.272000```
I'm not sure if I can share this file due to copyright, otherwise I would.

Thank you!

**Comment by boardhead** [comment]
Can you tell me the value of these tags?:

AudioBitrate
VBRFrames
SampleRate
MPEGAudioVersion

ExifTool calculates the approximate duration from these tags.

Also, is the file mono or stereo?

- Phil

**Comment by boardhead** [comment]
The VBRFrames is only used for variable bitrate encoding, which this file is apparently not.

I think that ffprobe probably analyzes the audio stream to exactly determine the duration.  ExifTool doesn't analyze the whole stream, and just calculates an approximate duration from the header information.  Taking the extracted information at face value, if the bitrate really is 64 kbps you would get about 10 minutes out of a 4.7 MiB file, so the calculation makes sense.  Either the extracted bitrate is wrong, or half of the file doesn't contain audio information.  I can't say which without analyzing the sample carefully.

 - Phil

**Comment by Domi250** [comment]
You are right, ffprobe indeed shows a framerate of about 129 kbit/s, pretty much double of exiftool.
I've found sone audio without copyright, once again downloaded it with spotdl, and attached it here:
[song.zip](https://github.com/exiftool/exiftool/files/9882765/song.zip) 
(mp3 are not supported on github, therefore it's a zip)
This file has the same problem.

**Comment by v0h0ang** [comment]
Ok
