### ISSUE TITLE
About exiftool stay_open using multiprocessing

### ISSUE THREAD

**Issue by jishi92** [exiftool/exiftool#161]
Hi guys:
I use exiftool command line in Go.
I have used `stay_open` feature of exiftool to get a speed up compared to invoking one exiftool instance for each image.
However, the processing queue will accumulate if the speed of requests is greater than the speed of processing.Then the response-time will increase a lot.
I have too many images need to process.
Does the `stay_open` pattern support concurrent multi-process processing? 
If yes, can you provide a demo code. 
I would appreciate some guidance on where to look.

**Comment by StarGeekSpaceNerd** [comment]
I can't directly answer this question or link any code but I do know that the Windows program IMatch, which uses exiftool on the backend, runs four separate instances of exiftool.  I believe that that it uses the numbered response feature of the [`-execute` option](https://exiftool.org/exiftool_pod.html#execute-NUM) in this process.

**Comment by StarGeekSpaceNerd** [comment]
[Answered on the exiftool forum](https://exiftool.org/forum/index.php?topic=14154.msg75383)

**Comment by jishi92** [comment]
Thanks @StarGeekSpaceNerd , I  have  test it done. It's successful.
