### ISSUE TITLE
Customizing [HEAD] or [TAIL]

### ISSUE THREAD

**Issue by WGroleau** [exiftool/exiftool#163]
With -p FMTFILE, I would like to have a way to control what appears before and after the image files.

I can replacing the "1" in the name/desc elements with a longer string, and use another command to replace that afterward, but it would be nice to be able to do it in one lie..

See also https://stackoverflow.com/questions/74504661/how-to-make-exiftool-use-data-not-in-the-files-tags

**Comment by boardhead** [comment]
I don't know what you want your format to look like, or whether you are batch processing files, but I think the [tt]-userparam[/tt] option may be what you want:

[code]> exiftool a.jpg -p test.fmt -userparam name=Hello -userparam desc=Goodbye
<name>Hello</name>
<desc>Goodbye</desc>[/code]

here was the test.fmt file:

[code]<name>$name</name>
<desc>$desc</desc>[/code]

- Phil

**Comment by WGroleau** [comment]
Ah, that looks like it will work to replace the "1" in gpx.fmt !
