### ISSUE TITLE
Using multiple wildcards may not work.

### ISSUE THREAD

**Issue by WGroleau** [exiftool/exiftool#166]
It might not be possible to work around this.
`    exiftool '-GPSDateTime<CreateDate' *.MOV *.mov *.mp4`
will fail if the directory doesn't have files with **all** of those extensions.

If the directory has some .mov and some .mp4 but no .MOV, the shell will complain about the lack of .MOV and exiftool will not process the others.

**Comment by WGroleau** [comment]
Workaround is to do a loop and run each extension separately.

**Comment by StarGeekSpaceNerd** [comment]
Use the [`-ext` (`-extension`) option](https://exiftool.org/exiftool_pod.html#ext-EXT---ext-EXT--extension) to limit the scope of the files to process.  See [Common Mistake #2](https://exiftool.org/mistakes.html#M2).

`exiftool '-GPSDateTime<CreateDate' -ext mov -ext mp4 /path/to/files/`

You almost never want to loop exiftool as its biggest performance hit is the startup time.  See [Common Mistake #3](https://exiftool.org/mistakes.html#M3).

**Comment by WGroleau** [comment]
Thanks for the useful mistakes page.  Startup time isn't a big deal for my script, but I'll definitely improve it that way.  Currently, it invokes exiftool nine times and takes a total of 1.28 second to do a directory holding 21 images.  But removing the loop will make it four invocations.
