### ISSUE TITLE
JPEG XL Exif box not recognized if offset is not zero

### ISSUE THREAD

**Issue by kmilos** [exiftool/exiftool#168]
The JPEG XL Exif box specification is actually the same as the HEIF one (4 bytes of offset + actual payload), and this seems to work fine in the Quicktime handler for HEIFs, but not in the Jpeg2000 one for JXLs:
```
  | EXIF (SubDirectory) -->
  | - Tag 'Exif' (21892 bytes):
  |     003b: 00 00 00 06 45 78 69 66 00 00 49 49 2a 00 08 00 [....Exif..II*...]
  |     004b: 00 00 0d 00 00 01 03 00 01 00 00 00 00 10 00 00 [................]
  |     005b: 01 01 03 00 01 00 00 00 00 0c 00 00 0f 01 02 00 [................]
  |     006b: 07 00 00 00 aa 00 00 00 10 01 02 00 09 00 00 00 [................]
  |     007b: b2 00 00 00 12 01 03 00 01 00 00 00 01 00 00 00 [................]
  |     [snip 21812 bytes]
  | + [TIFF directory]
  | Warning = Unrecognized EXIF box
```

**Comment by boardhead** [comment]
Do you have a sample file that I could use for testing?

- Phil

**Comment by kmilos** [comment]
Sure, here goes: [Reagan_nonzero.zip](https://github.com/exiftool/exiftool/files/10338858/Reagan_nonzero.zip)

**Comment by kmilos** [comment]
Also here's the [non-zero offset HEIF sample](https://github.com/ImageMagick/ImageMagick/files/9681803/883089f0-80e4-45ea-89f9-50213c25ffbb.heic.zip) for comparison.

**Comment by boardhead** [comment]
Great, thanks.  I'll patch ExifTool 12.53 to read the EXIF in your JXL sample.

- Phil

**Comment by kmilos** [comment]
12.53 confirmed working, thanks!
