### ISSUE TITLE
Add 'dry run' mode

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#169]
[We see there is no dry run / report only / readonly mode](https://exiftool.org/forum/index.php?topic=8070.0).
Therefore it would be great if there would be a way to see what exiftool would do, without actually doing it.
That way we wouldn't need to make copies of big files, just to know what exiftool would do to them.

Actually we might not have any intention of writing anything, but instead just want to see what exiftool would put in a geotag, etc.

Wait, there is 
> 'WriteNothing' - flag indicating that nothing is actually
                  written when this tag is set.  It is a fake writable tag that
                  isn't actually written (eg. Geotag).  Used to avoid processing
                  a file unnecessarily if nothing will actually be written.

**Comment by jidanni** [comment]
Alas, there is no example of how to use "WriteNothing" on command lines like
> exiftool -geotag track.log /Users/Phil/Pictures

In fact no examples can be found anywhere.

**Comment by boardhead** [comment]
The WriteNothing flag isn't what you need, and isn't for use on the command line.

How would you expect to be able to determine if ExifTool would write a tag in dryrun mode?

- Phil

**Comment by jidanni** [comment]
I was just hoping that it could say what it was going to do instead of actually doing it. I thought that might be more elegant than having it actually write files, even though yes it  saves it in the _original file.

**Comment by boardhead** [comment]
ExifTool would have to actually write the file to determine what it was going to do.  In theory I could add a feature to allow you to write to /dev/null, which would effectively give you what you want, but in practice it isn't that simple because there are things other than the output file that ExifTool writes (eg. file system information), and adding a dryrun /dev/null patch to all these features would be a bit of work.

**Comment by jidanni** [comment]
Okay, it's all about those new Boeing 787 Dreamliners with the new  tinted glass that doesn't let any GPS signals pass through. That's why I was trying to query "where was this picture taken?" given the track log obtained from FlightAware during the one week that it is free of charge. And given the time the picture was taken, which is the only piece of data you're going to generate inside such kind of planes.

So I thought it was kind of weird that I couldn't just ask some program where on the track would  this interpolate.

Well okay if it needs to write something, okay I'm still grateful. (I can always just hand it  a copy even if it does indeed make an _original backup.) So I guess it's no big deal so I'll just close this feature request for now.
