### ISSUE TITLE
Mention example of (new) need for -geotag

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#170]
https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Geotag.pm perhaps could use an example of why in this day and age a digital photograph might still need to get its EXIF location added, as if someone was still using an early digital camera without GPS. Ah! https://github.com/dfandrich/gpscorrelate/issues/19 .

**Comment by boardhead** [comment]
There are many cameras which don't have GPS built in.
