### ISSUE TITLE
examples.html mangled

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#172]
I thought there was something wrong with https://exiftool.org/examples.html ,
a form without a submit button, etc.
And sure enough, lots of problems:
https://validator.w3.org/check?uri=https%3A%2F%2Fexiftool.org%2Fexamples.html&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by boardhead** [comment]
That is an incomplete web page of an idea that never got off the ground.

**Comment by jidanni** [comment]
(Sure hope you put a warning on it.)

**Comment by boardhead** [comment]
The examples are still valid, so I don't see why I should add a warning.  I'm just saying that page is old and isn't actively being developed so I'm not going to waste any time trying to fix the html.  It isn't linked anywhere from the ExifTool documentation, and the only way to find this page is from old forum posts.

- Phil

**Comment by jidanni** [comment]
Okay but Google's got its hands on it too... I think that's how I got there, by a keyword search.
