### ISSUE TITLE
Support KML tracks with all timing and coordinates in one single placemark

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#173]
```
$ exiftool -geotag *RJAA*RCTP*.kml ...
Loaded 1 points from XML-format GPS track log file [attached]
  GPS track start: 2022:12:21 14:49:40.000 UTC
  GPS track end:   2022:12:21 14:49:40.000 UTC
```
There are plenty of track 'points' in that file, not just one.

I'll need to run
```
gpsbabel -i kml -x interpolate,time=1 -o kml ...
```
on that file first.
[FlightAware_JAL809_RJAA_RCTP_20221221.kml.gz](https://github.com/exiftool/exiftool/files/10399514/FlightAware_JAL809_RJAA_RCTP_20221221.kml.gz)

**Comment by StarGeekSpaceNerd** [comment]
See [Geotagging Troubleshooting #1](https://exiftool.org/geotag.html#TR1) (emphasis mine)
> For instance, in KML files **each** Placemark must contain a TimeStamp.

All the timing and coordinates are in a single placemark.

Phil will have to comment further on whether support for this type of KML file can be added or not.
