### ISSUE TITLE
kml.fmt example clamps altitude to 0

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#175]
On geotag.html the gpx.fmt example has
`<ele>$gpsaltitude#</ele>`
but kml.fmt just has
```
#[BODY] <altitudeMode>clampedToGround</altitudeMode>
#[BODY] <coordinates>$gpslongitude#,$gpslatitude#,0</coordinates>
```
- Perhaps `$gpsaltitude#` could go where that 0 is?
- And then you could do away with clampedToGround. [Or use something else](https://developers.google.com/kml/documentation/altitudemode).
- If you really don't know the altitude, then [don't write it at all](https://developers.google.com/kml/documentation/kmlreference#example_21).

**Comment by boardhead** [comment]
The coordinates require an altitude, and I want this file to work if the altitude is not known or not reliable, which is the case for the most common usage of this file (for driving).  For flight, you can change 0 to $gpsaltitude# as you suggested.

**Comment by jidanni** [comment]
Well, if it is not known,  (undef), then just output the two parameter form. And if it is unreliable, including 0, then that's the user's own fault, garbage in  garbage out.

I mean you could have made a beautiful <extrude>d KML path that rises with the plane's acent.
But instead it's locked to the ground. That's just as fair as if I put your automobile up at Flight Level 360! :-) Anyway, all this picking on one of the three parameters, altitude, strikes me just  as fair  as if I arbitrarily beat up one of the other parameters, latitude or longitude. :-)

**Comment by boardhead** [comment]
Thanks.  I didn't realize the altitude was optional.

**Comment by boardhead** [comment]
I have added this note to kml.fmt:

> #            6) The "0" in the coordinates line may be changed to "$gpsaltitude#"
> #               and the altitudeMode may be changed to "absolute" to store
> #               altitude information if it exists in the track log.

to make it easier for people to figure out how to include the altitude.

**Comment by jidanni** [comment]
(Maybe that altitude mode is the default so you don't even have to say it. But that's kind of hard to figure out. But anyway the official docs say

>Any altitude value should be accompanied by an <altitudeMode>

So it doesn't matter what the default altitude mode is.)

**Comment by boardhead** [comment]
The format files are mainly for example, and it is easy for the user to tailor them to their preferences.
