### ISSUE TITLE
PNG: cICP chunk since ffmpeg now writes it by default

### ISSUE THREAD

**Issue by ValZapod** [exiftool/exiftool#178]
https://github.com/FFmpeg/FFmpeg/commit/6f79f0971e8ccf6c7a2b8eb1dbc5b64fdd77ca0f added support for

https://github.com/exiftool/exiftool/blob/19d09138d8ad75d0221435fb7a16a415625a53e5/lib/Image/ExifTool/PNG.pm#L346

**Comment by kmilos** [comment]
FYI, [`djxl` outputs it as well...](https://github.com/libjxl/libjxl/blob/main/lib/extras/enc/apng.cc#L189-L195)

**Comment by boardhead** [comment]
ExifTool 12.56 (to be released soon) will support extracting this information.

- Phil
