### ISSUE TITLE
Bug: IPTC section added with CodedCharacterSet without any tags

### ISSUE THREAD

**Issue by bheston** [exiftool/exiftool#179]
If -CodedCharacterSet=UTF8 is passed when writing a file (even if that is the only parameter), a new IPTC section is added to a file that previously did not have one.

According to the [FAQ](https://exiftool.org/faq.html#Q10) this should be used when writing IPTC tags, but it should be safe to pass if no IPTC tags are being written, in which case it should do nothing.

I discovered this because exiftool-vendored.js passes this when writing tags. One could argue the bug is on them, but it feels like the underlying library should handle this without side effects as well.

**Comment by boardhead** [comment]
CodedCharacterSet is an IPTC tag, so it will be written if specified.  From an ExifTool point of view, this is written like any other IPTC tag.  The "-wm wc" option may be added to the command to avoid creating IPTC (and other new groups) if they didn't already exist.

- Phil

**Comment by bheston** [comment]
I figured that was the case. It does seem like an odd tag that has no meaning without actual content tags. There are many like this though, and I suppose mapping those out, whether for warnings or ignoring them, would be difficult if not impossible. For instance, I've been doing a lot of date/time cleanup, and having a time offset without an actual time value for one of the main three tags would be meaningless.

I'll close this and open an issue with exiftool-vendored.
