### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by Barmem** [exiftool/exiftool#180]
When i try adding description to file in russian

`./exiftool.exe -description="Тестовое описание" C:\path\to\file.png`

it writes without issues, but when i read it it looks like that 

`Description                     : ╥хёЄютюх юяшёрэшх`

**Comment by StarGeekSpaceNerd** [comment]
Assuming you're using Windows, this is [FAQ #18](https://exiftool.org/faq.html#Q18).

Windows command line doesn't deal with accented/UTF characters very well.  FAQ 18 gives some options you can try to work around it..

Myself, I was never able to get them to work.  Instead, I had to use [this StackOverflow answer](https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window/57134096#57134096) to set the entire system to UTF8.  The downside to this is that in some older programs, it changes the font for GUIs which might have some negative effects on how they display data.

**Comment by Barmem** [comment]
thanks that's worked
