### ISSUE TITLE
Hang when passing in a corrupt real media file

### ISSUE THREAD

**Issue by svenclaesson** [exiftool/exiftool#181]
Hi,

The file inside this zip will hang exiftool.

[hang.zip](https://github.com/exiftool/exiftool/files/10548328/hang.zip)

I'm using windows and version 12.55

**Comment by boardhead** [comment]
Great!  Thanks for this report.  This will be fixed in version 12.56

- Phil

**Comment by svenclaesson** [comment]
Thank you for your quick response and for this great project!

**Comment by svenclaesson** [comment]
Tested OK in 12.56

**Comment by boardhead** [comment]
Thanks!
