### ISSUE TITLE
Minor XMP date-time string issues

### ISSUE THREAD

**Issue by trevorld** [exiftool/exiftool#182]
Some minor `exiftool` XMP date-time string issues I noticed playing around with `exiftool`:

1. `exiftool` XMP `date` documentation seems incomplete
2. year-only XMP date-time strings are returned as an integer instead of string in JSON output
3. possible feature request: it may be nice if `YYYY:mm:dd HH:MM:SS±HH` was treated as `YYYY:mm:dd HH:MM:SS±HH:00` instead of `YYYY:mm:dd HH:MM:SS`

According to https://exiftool.org/TagNames/XMP.html:

> `date` is a date/time string entered in the format "YYYY:mm:dd HH:MM:SS[.ss][+/-HH:MM]"

However after trial and error it seems that (for XMP date/time strings) `exiftool` supports more `date` options closer to `YYYY[:mm][:dd][ HH:MM][:SS][.s][+/-HH:MM]` which is great because it allows `exiftool` to support setting [all legal XMP date-time values](https://github.com/adobe/xmp-docs/blob/master/XMPNamespaces/XMPDataTypes/CoreProperties.md#date).

However I did note that if you only set the date-time year and then request JSON output that `exiftool` returns an **integer** instead of a **string** like it returns with all other date-time strings.  I've implemented a work around but this initially created a surprise bug in my code.

Most XMP date-time strings are returned in JSON as a **string**:

```bash
~/tmp/Image-ExifTool-12.55$ ./exiftool -ver
12.55
~/tmp/Image-ExifTool-12.55$ Rscript -e "png('test.png'); grid::grid.text(''); invisible(dev.off())"
~/tmp/Image-ExifTool-12.55$ ./exiftool -XMP-photoshop:DateCreated="2020:04" test.png
    1 image files updated
~/tmp/Image-ExifTool-12.55$ ./exiftool -j -G1 -a -XMP:all test.png
[{
  "SourceFile": "test.png",
  "XMP-x:XMPToolkit": "Image::ExifTool 12.55",
  "XMP-photoshop:DateCreated": "2020:04"
}]
```

However a year date-time string are returned in JSON as an **integer**:

```bash
~/tmp/Image-ExifTool-12.55$ ./exiftool -XMP-photoshop:DateCreated="2020" test.png
    1 image files updated
~/tmp/Image-ExifTool-12.55$ ./exiftool -j -G1 -a -XMP:all test.png
[{
  "SourceFile": "test.png",
  "XMP-x:XMPToolkit": "Image::ExifTool 12.55",
  "XMP-photoshop:DateCreated": 2020
}]
```

I'm also observing that date-time strings of format `YYYY:mm:dd HH:MM:SS±HH` (which aren't documented as being supported in `exiftool` and isn't a legal XMP date-time string) is being treated as `YYYY:mm:dd HH:MM:SS`.  It may be more useful if it was instead treated as `YYYY:mm:dd HH:MM:SS±HH:00` instead.  I do notice that `exiftool` seems to treat XMP date-time strings of format `YYYY:mm:dd HH` (also not legal XMP date-time string) as `YYYY:mm:dd HH:00` instead of `YYYY:mm:dd`.

```bash
~/tmp/Image-ExifTool-12.55$ ./exiftool -XMP-photoshop:DateCreated="2020:10:04 10:10:10-07" test.png
    1 image files updated
~/tmp/Image-ExifTool-12.55$ ./exiftool -j -G1 -a -XMP:all test.png
[{
  "SourceFile": "test.png",
  "XMP-x:XMPToolkit": "Image::ExifTool 12.55",
  "XMP-photoshop:DateCreated": "2020:10:04 10:10:10"
}]
~/tmp/Image-ExifTool-12.55$ ./exiftool -XMP-photoshop:DateCreated="2020:10:04 10" test.png
    1 image files updated
~/tmp/Image-ExifTool-12.55$ ./exiftool -j -G1 -a -XMP:all test.png
[{
  "SourceFile": "test.png",
  "XMP-x:XMPToolkit": "Image::ExifTool 12.55",
  "XMP-photoshop:DateCreated": "2020:10:04 10:00"
}]
```

**Comment by boardhead** [comment]
1. FAQ 5 explains date/time formats in more detail:

https://exiftool.org/faq.html#Q5

2. From the ExifTool -json option documentation:

 Note that ExifTool quotes JSON values only if they
 don't look like numbers (regardless of the original storage format
 or the relevant metadata specification).

3. Recognizing a partial time zone specification may be problematic because ExifTool also allows dashes separating the date/time specifiers, and a 2-digit time-zone specification would be problematic:

 > exiftool a.jpg -xmp:createdate="2022-01-01 02-03-05:00"
    1 image files updated
 > exiftool a.jpg -xmp:createdate
 Create Date                     : 2022:01:01 02:03-05:00
 > exiftool a.jpg -xmp:createdate="2022-01-01 02-03-05"
    1 image files updated
 > exiftool a.jpg -xmp:createdate
 Create Date                     : 2022:01:01 02:03:05

- Phil

**Comment by trevorld** [comment]
* Thanks for the explanations re: 2/3.  Perhaps it would be nice to link FAQ#5 in the discussion of legal XMP dates in https://exiftool.org/TagNames/XMP.html ?

**Comment by boardhead** [comment]
Good suggestion, I'll look into this.

- Phil

**Comment by boardhead** [comment]
OK, I can add link to FAQ 5 in the next release.
