### ISSUE TITLE
`exiftool` looks for hardcoded `perl` path

### ISSUE THREAD

**Issue by Kabouik** [exiftool/exiftool#183]
In a script that might be run from multiple machines and users (some of which don't have `exiftool` installed), I am using an `exiftool` binary stored on a remote machine. While `perl` is installed on all machines (or, for Windows users, installed in a remote MobaXterm root folder), I noticed that it fails when the `perl` binary is not located in `/usr/bin/perl`, and there does not seem to be any option to alter that hardcoded path. If I make a symlink to `/usr/bin/perl`, then `exiftool` succeeds, but that is not a good workaround. 

Should `exiftool` not look for `perl` in `$PATH` instead?

**Comment by boardhead** [comment]
If your perl is in the path, but not in /usr/bin/perl, then you should execute exiftool like this:

 perl exiftool ...

- Phil

**Comment by Kabouik** [comment]
Thanks for the answer. Since I want multiple users to run `exiftool` from their own machine, I can make a script with an `if` condition to execute `exiftool` in that way if `/usr/bin/perl` does not exist but `perl` is in `$PATH`, but would it not be more standard if `exiftool` did not expect a hardcoded location for `perl`? There are Linux distributions that have `perl` located elsewhere.

**Comment by boardhead** [comment]
I don't know if it is possible/desirable to have a variable path for perl in the shebang at the start of a Perl script.

**Comment by Kabouik** [comment]
Would `#!/usr/bin/env perl` work? I see that more and more often for `bash` scripts, but perhaps I am not neutral because I have to use that myself as a Guix System user.

**Comment by boardhead** [comment]
That may work on some Unix systems, and does seem to work on Mac, but I worry about portability for other systems (especially for older systems and odd systems like Windows).  Since this is the first time this problem has come up in the 20 years since ExifTool was released, I would hesitate to change this because it would likely break this for more people than it would help.

**Comment by Kabouik** [comment]
I totally understand your concerns, and would not want you to break a tool that work well because of me either! Maybe others will chime in here later and tell if that would be portable on older UNIX systems or on Windows, hopefully!

I'm taking the opportunity for thanking you for this great tool.
