### ISSUE TITLE
Losslessly read less precise PDF documentation info datetimes

### ISSUE THREAD

**Issue by trevorld** [exiftool/exiftool#185]
I'm observing that `exiftool` only supports a small subset of valid PDF documentation info datetimes:

```bash
Rscript -e "pdf('blank.pdf'); grid::grid.text(''); invisible(dev.off())"
./exiftool -ver
12.56
./exiftool -PDF:CreateDate=2023:02:10 blank.pdf
Warning: Invalid date/time (use YYYY:mm:dd HH:MM:SS[.ss][+/-HH:MM|Z]) in PDF:CreateDate (PrintConvInv)
Nothing to do.
```

It would be great if `exiftool` could support more valid PDF documentation info datetimes.  The low hanging fruit may be to support the extra datetimes that `exiftool` [currently supports for XMP](https://exiftool.org/faq.html#Q5) that are also legal PDF documentation info datetimes:

* `YYYY`
* `YYYY:mm`
* `YYYY:mm:dd`
* `YYYY:mm:dd HH:MM`

There are also a couple of datetimes that are legal PDF documentation info datetimes that are not legal XMP datetimes:

* `YYYY:mm:dd HH`
* `YYYY:mm:dd HH:MM:SS(+-Z)HH`

  - [You explained previously](https://github.com/exiftool/exiftool/issues/182#issuecomment-1417992340) why this latter one probably will not be supported by `exiftool`

Some documentation references on valid PDF documentation info datetimes:

* https://opensource.adobe.com/dc-acrobat-sdk-docs/library/pdfmark/pdfmark_Basic.html#document-info-dictionary-docinfo
* https://www.oreilly.com/library/view/pdf-explained/9781449321581/ch04.html

**Comment by boardhead** [comment]
Use the [tt]-n[/tt] option to write partial date/time values.  This is now mentioned in FAQ 5 https://exiftool.org/faq.html#Q5

- Phil

**Comment by trevorld** [comment]
I observe that `exiftool` **losslessly** reads/writes XMP datetimes with less than second precision:

```
~/tmp/Image-ExifTool-12.56$ ./exiftool -n -XMP:CreateDate=2023:02:10 blank.pdf
    1 image files updated
~/tmp/Image-ExifTool-12.56$ ./exiftool -G1 -a -j -XMP:CreateDate blank.pdf
[{
  "SourceFile": "blank.pdf",
  "XMP-xmp:CreateDate": "2023:02:10"
}]
```

But that `exiftool` "widens" less precise pdf datetimes to seconds even though the PDF standard doesn't require that pdf datetimes have second precision:

```
~/tmp/Image-ExifTool-12.56$ ./exiftool -n -PDF:CreateDate=2023:02:10 blank.pdf
    1 image files updated
~/tmp/Image-ExifTool-12.56$ ./exiftool -G1 -a -j -PDF:CreateDate blank.pdf
[{
  "SourceFile": "blank.pdf",
  "PDF:CreateDate": "2023:02:10 00:00:00"
}]
```

The feature request would be to extend this **lossless** datetime support you already have for XMP datetimes to PDF datetimes.

**Comment by trevorld** [comment]
* Playing around with `pdftk blank.pdf data_dump` it seems that `exiftool` actually does losslessly **write** some of these partial datetimes
* I haven't figured out a way losslessy **read** these partial datetimes in `exiftool` like I can losslessy **read** partial XMP datetimes

**Comment by trevorld** [comment]
I'm observing with the `-n` flag that `exiftool` converts `'`s in raw pdfmark datetimes to `&apos;`:

```
~/tmp/Image-ExifTool-12.56$ ./exiftool -n -PDF:CreateDate="20230402101010+02'" blank.pdf
    1 image files updated
~/tmp/Image-ExifTool-12.56$ pdftk blank.pdf data_dump
### omit some fields
InfoBegin
InfoKey: CreationDate
InfoValue: D:20230402101010+02&apos;
### omit some fields
```

UTC offset (hours/minutes) pdfmark datetimes are supposed to end with an apostrophe.  Unsure how to input them.

**Comment by boardhead** [comment]
I don't think that ExifTool is changing the apostrophe to &apos; -- Could it be that pdftk is doing this.  Here is what I get with ExifTool:

```
> exiftool -n -PDF:CreateDate="20230402101010+02'" a.pdf 
    1 image files updated
> exiftool a.pdf -v3 
...
  + [Info directory with 1 entries]
  | 0)  CreateDate = (D:20230402101010+02')
  |     - Tag 'CreationDate', direct object
...
```

So the apostrophe seems to be in there.

- Phil

**Comment by trevorld** [comment]
> I don't think that ExifTool is changing the apostrophe to ' -- Could it be that pdftk is doing this. 

You're right.  Sorry!  I should be able to losslessly **write** all legal PDF documentation datetimes with `exiftool` (I already tested all the other possible precisions).

```bash
~/tmp$ exiftool -n -PDF:CreateDate="20230402101010+02'" test.pdf
    1 image files updated
~/tmp$ grep -a CreationDate test.pdf
/CreationDate (D:20230223084751)
/CreationDate (D:20230402101010+02')
```
```bash
~/tmp$ pdftk test.pdf dump_data | grep "D:"
InfoValue: D:20230223084751
InfoValue: D:20230402101010+02&apos;
~/tmp$ pdftk test.pdf dump_data_utf8 | grep "D:"
InfoValue: D:20230223084751
InfoValue: D:20230402101010+02'
```
