### ISSUE TITLE
Garmin 66W dashcam started duplicating gpx tracks in mp4 after firmware update

### ISSUE THREAD

**Issue by rKsanu2MMYvypWePtQWM** [exiftool/exiftool#186]
After a firmware update (that didn't have any changelog) the videos from the dashcam started duplicating tracks - first a track in UTC, then the same exact track, but with UTC-2 timestamp (actual zone currently UTC+2).

Is it possible to work-around this with exiftool? It seems Garmin likes making things harder for everyone... 

[GPX.txt](https://github.com/exiftool/exiftool/files/10735518/GPX.txt)

Here is the link for the mp4: https://we.tl/t-uIuF14JeJD

Old mp4 files before the update seem to be fine. Now this whole thing coincided with the filenumber rolling over, perhaps that could be the culprit?

I remember a year ago when I was writing my scripts, altitude was showing speed (divided by 1.6 to get kilometers, from kilometers already) instead :smile: I guess that's just how Garmin rolls...

Thank you for the great tool!

**Comment by boardhead** [comment]
Interesting.  If you want the UTC track, add -track3:all to your command, or add Track3 as a prefix to all your tags.  If you want the local-time track, add --track3:all to extract everything but Track3.  I should put the local-time tags in another family 1 group (Garmin?) so they may be selected more easily.  Currently they are just in the QuickTime group.

- Phil

**Comment by rKsanu2MMYvypWePtQWM** [comment]
I've tried out the commands. -track3:all did nothing, but  --track3:all did work.

Actually, after I tried these new options, it seems like old videos started producing the same doubled-up gpx sequence... But I swear that it did actually work fine with old videos yesterday! Perhaps it actually was just a newer version of your tool? Something in the last 3 months perhaps? Or maybe I'm just going nuts...

In any case, thank you!

**Comment by boardhead** [comment]
It could be that earlier versions of ExifTool didn't decode one of the formats.  I'm continuously adding support for new timed GPS formats.

- Phil

**Comment by rKsanu2MMYvypWePtQWM** [comment]
Thanks for your hard work. I'll mark this as solved.

**Comment by boardhead** [comment]
As of ExifTool 12.57 (2023-02-23), tags from the first track are in the "Garmin" group.  This track is most reliable because it contains the UTC GPSDateTime.  The GPSDateTime for the "Track3" track is calculated based on the QuickTime:CreateDate and SampleTime for each position.  Note that the "-api QuickTimeUTC" option is necessary so the QuickTime:CreateDate is converted properly for this video.

- Phil

**Comment by boardhead** [comment]
I'm adding a patch to ExifTool 12.74 so the QuickTimeUTC option won't be required to fix the GPSDateTime values calculated for Track3.
