### ISSUE TITLE
Mention GitHub in the documentation

### ISSUE THREAD

**Issue by jidanni** [exiftool/exiftool#188]
Let's find out where we can submit a bug about Exiftool. On Debian
```
$ ls -og /usr/share/doc/*exift*/cop*
-rw-r--r-- 1 1921 02-24 11:21 /usr/share/doc/libimage-exiftool-perl/copyright
# that's nice and fresh.

$ grep http /usr/share/doc/*exift*/cop*
Source: https://metacpan.org/release/Image-ExifTool
# OK, let's browse it

$ $BROWSER https://metacpan.org/dist/Image-ExifTool [*]
# that must be the place. No e.g., github mentioned.

$ $BROWSER https://rt.cpan.org/Dist/Display.html?Name=Image-ExifTool
# Just a few dusty issues. I suppose development must have stopped. Oh, well.
```

Therefore, please on [*] be sure users are told to look at
https://github.com/exiftool/exiftool .
In fact https://github.com/mrdvt92/perl-Geo-Inverse/issues/1 mentions
the right way.

**Comment by boardhead** [comment]
You can submit bug reports to CPAN, github, debian, or in the Bug-report board on the ExifTool forum.  I respond to them all.  The preferred location is the forum.

- Phil

**Comment by jidanni** [comment]
Ah but a bug reported on GitHub by user A might get reported again on metacpan by user B because B has no way to find your  GitHub from metacpan.

**Comment by boardhead** [comment]
That hasn't been a problem.

**Comment by StarGeekSpaceNerd** [comment]
Phil's turn around time on fixing bugs is significantly faster than most other software.

Many bug reports on the forums are for problems that were fixed months ago and the person reporting it hasn't upgraded to the newest version.

**Comment by boardhead** [comment]
For bugs impacting file integrity, my turn-around time is usually less than a day.  Other problems may take longer... Non-critical bugs that affect only the Windows version may take years (like that last CPAN report). :P

**Comment by jidanni** [comment]
Okay. Please be sure to mention the GitHub  address on the man page etc. Thanks.

**Comment by boardhead** [comment]
I would prefer not to do that (for now at least) because I would rather people use the forum.  GitHub is more convenient for people who already have GitHub accounts, and I would think that those people can find this address easily.  Others will hopefully find the forum: https://exiftool.org/forum/index.php?board=6.0

- Phil

**Comment by jidanni** [comment]
Keyword searches often turn up many different forks first.
That's always why it's a good idea to document the official repository.

**Comment by boardhead** [comment]
I don't know how to respond to this because I don't know how you define "official repository".

The primary source code repository isn't public.  The ExifTool web site has the source for all versions back to 1.00.  CPAN has production versions since 3.60, and Github and SourceForge have all versions since 9.71.

- Phil

**Comment by jidanni** [comment]
OK, I made https://rt.cpan.org/Ticket/Display.html?id=146910 .
That way https://github.com/exiftool/exiftool/issues/ is now a tiny bit mentioned on metacpan finally.

**Comment by jidanni** [comment]
Fine. I sent https://rt.cpan.org/Ticket/Display.html?id=146910 to the wrong queue.
How about this: I give up.

**Comment by boardhead** [comment]
I understand your issue better now after reading your cpan ticket:

> I'm posting this bug here so you won't end up like me, in a dead end thinking there wasn't any other bug tracker, and these few dusty bugs were all the action regarding the exiftool package that exist.

This is true.  All I can say is that I hope people check the forum if they want to gauge the amount of action involving ExifTool (average activity is 14 posts per day):

https://exiftool.org/forum/

- Phil
