### ISSUE TITLE
Add write support for custom MicaSense Altum XMP tags

### ISSUE THREAD

**Issue by OneGneissGuy** [exiftool/exiftool#19]
Cannot edit MicaSense Altum XMP tags because a config file for the custom XMP tags is not yet defined.

**Comment by boardhead** [comment]
If you attach an XMP sample with these tags I can create a config file for you to allow you to edit them.

**Comment by OneGneissGuy** [comment]
I have attached a zipped multilayer tiff collected by the MicaSense Altum.The layers and channels and defined as such:

1 = BLUE
2 = GREEN
3 = RED
4 = NIR
5 = REDEDGE
6 = Thermal
 
I need to edit these custom XMP tags:

* BandName
* CentralWavelength
* WavelengthFWHM
* RigName
* RigCameraIndex

[AltumTiff.zip](https://github.com/exiftool/exiftool/files/3277506/AltumTiff.zip)

**Comment by boardhead** [comment]
The attached config file lets you write these tags
[MicaSense.config.zip](https://github.com/exiftool/exiftool/files/3281146/MicaSense.config.zip)
