### ISSUE TITLE
Samsung NX mini manual WB presets (Samsung_Type_2_0x00a0)

### ISSUE THREAD

**Issue by ge0rg** [exiftool/exiftool#190]
Hi,

I've recently resurrected the obscure, long-forgotten, Samsung NX mini, and wanted to [add proper WB profile support into darktable](https://github.com/darktable-org/darktable/issues/12820).

However, the NX mini only encodes the WB profile in the custom Samsung type2 field 0x00a0, which is [partially documented](https://github.com/exiftool/exiftool/blob/19d09138d8ad75d0221435fb7a16a415625a53e5/lib/Image/ExifTool/Samsung.pm#L371-L373) but not working out-of-the-box. If there is any interest in parsing more data from this field, I have the NX mini and can provide raw shots as well as squint at a hex editor to find patterns.

My first attempt is reconstructing the WB presets to individual values in the field, as documented in https://github.com/darktable-org/darktable/issues/12820#issuecomment-1309113913

**Comment by boardhead** [comment]
It looks like the WB modes may be identified through a combination of the little-endian 4-byte integers at offsets 9 and 13 in this record for your camera.  My worry is that this structure may vary for different models.

**Comment by ge0rg** [comment]
Yeah, the header varies with camera model, unfortunately. Below is one example from each generation of Samsung NX cameras, based on https://github.com/ge0rg/samsung-nx-hacks/#device-support - this should be representative for Samsung NX but is lacking the huge number of mobile phones they also released.

I was going to suggest checking for `AWB` in the beginning of the field, but this is also true on the NX20 and the format seems to deviate from there.

NX5 (DRIMe2, photo from raw.pixls.us):
```
Samsung Type 2 0x00a0           : ÈÉۜ»¿ªÈ77ÈÏÈÈÈÈÈÈÈÈÈÈÈïÈÈÈÈÈÈÈÈÈÉ.ÈÈÏ8ÈÈÎÈÈÈË8ÈÈÈÈ[...]
(no 0x00a1 field)
```
NX20 (DRIMe3, photo from raw.pixls.us):
```
Samsung Type 2 0x00a0           : AWB\x00\x14\x01TsAwb\x00ïü\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00°\x03\x00\x00\x00\t\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00°\x03[...]
Samsung Type 2 0x00a1           : 
```

NX300 (DRIMe4):
```
Samsung Type 2 0x00a0           : \x00\x00\x00\x00'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00a¢\x00\x00\x01\x00\x00\x00\x00\x00\x05\x00\x00\x07\x00\x00`\x05\x00\x00°\x07\x00\x00\x00\x05\x00\x00\x07\x00\x00`\x05\x00\x00\x00\x00[...]
Samsung Type 2 0x00a1           : 
```

NX500 (DRIMe5):
```
Samsung Type 2 0x00a0           : ÈÒÊØÉÈÈÈÈÈÈÈÈêÈÈÈilÈÈÀÜØÈÈØËÈÈhÏÈÈÈÎÈÈxÌÈÈÈÈÈÈÈÈÈÈÈÈ[...]
Samsung Type 2 0x00a1           : ÈÒÊØÉÈÈÈÈÈÈÈÈêÈÈÈilÈÈÀÜØÈÈØËÈÈhÏÈÈÈÎÈÈxÌÈÈÈÈÈÈÈÈÈÈÈÈ[...]
```

NX3000 (M7MU, same SoC as NX mini):
```
Samsung Type 2 0x00a0           : AWB\x00\x00\x02\x08\x01\x00\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x00\x00\x00\x00)£\x00\x00\x00\x00\x10\x00\x000\x02\x00\x00\x00\x07\x00\x00`\x06\x00\x00Ð\x02\x00\x00\x00\x00\x00\x00\x00\x00[...]
Samsung Type 2 0x00a1           : 
```

**Comment by boardhead** [comment]
Unfortunate.
