### ISSUE TITLE
SonyModelID 373

### ISSUE THREAD

**Issue by AdamMainsTL** [exiftool/exiftool#191]
Hello,

I've come across some files that have a SonyModelID of 373 which doesn't seem to be included in current tags. I'm not sure what all information you need to add it, so if this isn't enough let me know.

```
"EXIF:Make": "SONY",
"EXIF:Model": "DSC-HX95",
"EXIF:Software": "DSC-HX95 v1.00",
```

I can run commands to get more exif data if you need it, but I cannot provide the originals.

**Comment by boardhead** [comment]
Great, thanks!  This will be added in ExifTool 12.58

- Phil

**Comment by AdamMainsTL** [comment]
Closing as I see this in the 12.58 release. Thanks!
