### ISSUE TITLE
Add ability to copy Photoshop clipping paths

### ISSUE THREAD

**Issue by elmimmo** [exiftool/exiftool#192]
Add a way for clipping paths to be copied with the 'clipping path' property intact.

The repo provides a config file for dealing with Photoshop paths, and its comments document the [command line to copy paths from one image file to another](https://github.com/exiftool/exiftool/blob/7ee524e7895133140d50dc27284aee7890efe278/config_files/photoshop_paths.config#L48).

Even though the command does copy the paths, the destination does not inherit a path being marked in Photoshop as clipping-path, which is crucial for InDesign to be able to read said path.

**Comment by boardhead** [comment]
I've looked into this briefly.  The PSD record containing the clipping path name also contains the "flatness" and "fill rule" information.  Somehow you would have to be able to specify all of these.  Or maybe they could be set to default values if not specified?  At any rate, I would have to be able to read/write these extra parameters. I'll think about this.
