### ISSUE TITLE
New Panasonic tags in format 8

### ISSUE THREAD

**Issue by kmilos** [exiftool/exiftool#193]
Looking at e.g. DC-GH6 and DC-S5M2 samples at https://raw.pixls.us, these become obvious:

PanasonicRaw_0x0127  is a full-resolution embedded JPEG produced in camera
PanasonicRaw_0x013b  is identical to Exif Artist (i.e. duplicate of the thumbnail Exif tag but in IFD0, as now a normal TIFF/EP tag)
PanasonicRaw_0x8298  is identical to Exif Copyright (ditto)

**Comment by boardhead** [comment]
Great, thanks!  These will be added in ExifTool 12.59.

- Phil

**Comment by kmilos** [comment]
Confirmed working in 12.59, thanks.
