### ISSUE TITLE
Sony ARW 4.0 tags

### ISSUE THREAD

**Issue by kmilos** [exiftool/exiftool#195]
Here's the probable interpretation of a couple of more new tags found in the full-res SubIFD of Sony ARW 4.0 files (e.g. [lossless ILCE-7M4 sample](https://raw.pixls.us/getfile.php/4980/nice/Sony%20-%20ILCE-7M4%20-%2014bit%20(4:3).ARW) from https://raw.pixls.us/)

```
Exif_0x7310                     : 512 512 512 512
Exif_0x7313                     : 2483 1024 1024 1656
DefaultCropOrigin               : 12 8
DefaultCropSize                 : 7008 4672
SonyCropTopLeft                 : 12 8
SonyCropSize                    : 7008 4672
Exif_0x7038                     : 7032 4688
```

`0x7310` is BlackLevel (same as in SR2SubIFD)
`0x7313` is WB_RGGBLevels (same as in SR2SubIFD)
`0x7038` is something like sensor size or active area before crop (similar to ActiveArea of DNG?)

Also, the newest ZV-E1 sample from DPReview has
```
FileFormat                      : Unknown (4 0 1 0)
```
which should probably translate to "ARW 4.1"?

**Comment by boardhead** [comment]
Great, thanks!  I'll add 0x7310 an 0x7313.  0x7038 is smaller than the image size in one of my samples, so I don't see how it can be active area or sensor size.

**Comment by boardhead** [comment]
I understand now, thanks.  I'll add this as SonyRawImageSize.

- Phil

**Comment by kmilos** [comment]
> Oh, and I'll add the new FileFormat value.

Looking at the current scheme, it looks like ARW 4.0.1 is more appropriate...

**Comment by boardhead** [comment]
Yes, that is what I used.

**Comment by kmilos** [comment]
All confirmed in 12.60, thanks!
