### ISSUE TITLE
Newer Photoshops cannot open images with copied clipping paths.

### ISSUE THREAD

**Issue by fire1** [exiftool/exiftool#196]
I was using this command to copy clipping paths: 

`exiftool -config <config> -tagsfromfile <from.jpg> -allpaths# -originpathinfo  <target.jpg>`

But when "target.jpg" already has some clipping paths inside, it cannot be opened from newer Photoshops.
(Cloud not open "target.jpg" because of a program error.)
I cannot find any option to check for existing paths inside "[photoshop_paths.config](https://github.com/exiftool/exiftool/blob/master/config_files/photoshop_paths.config)", so this is missing?

**Comment by fire1** [comment]
Is there some option in ExifTool to clear a clipping path, like `0x07D0 = null` or changing the position of the incoming clipping paths when copying `0x07D0 => 0x07D3`

**Comment by boardhead** [comment]
Hi Angel,

Try this:  `exiftool -config photoshop_paths.config -path7d0= FILE`

- Phil

**Comment by fire1** [comment]
Found the problem... it was the Original path info ID 0x0BB8  ( dec 3000), when the data is erased from the target file image is opened just fine. Now my question will be how to drop only 0x0BB8 from the 8bim metadata after clipping paths are added.

This case is starting to be strange, I so the comment in `photoshop.conf` that we need to keep the original path info in order to work properly clipping paths data, but from my tests (also checked how  PsCS6 fixes the image) removing the original path info fixes the image for newer Photoshops (2020+)

**Comment by boardhead** [comment]
You can drop the OriginPathInfo like this:

`exiftool -config photoshop_paths.config -originpathinfo=`

I don't know exactly what you mean by question 2.  You could create a user-defined tag to import any 8BIM tag data in binary if that helps.  You can't import the whole photoshop APP13 data into a JPEG if that is what you are asking.

- Phil

**Comment by fire1** [comment]
For question 2 ...  then the whole Photoshop APP13, how to do that (import/export binary data)? It seems my confusion is coming from the ImageMagick PHP layer where there's a method  `getImageProfile('8BIM');`, that will return all 8BIM data in binary.

_Those methods `getImageProfile('8BIM');` and `setImageProfile('8BIM');` helps me a lot to debug this problem._

Thanks in advance!

**Comment by fire1** [comment]
Confirmed!
Removing original path info `-originpathinfo= ` info fixes the images for newer Photoshops!
