### ISSUE TITLE
Change .dpi value on multiple WebP files

### ISSUE THREAD

**Issue by Arekkusu1998** [exiftool/exiftool#198]
Good day everyone.
I state that I'm teetotaler of programming language and that so far I have used ExifTool (**v12.60**, on PC Windows 10 64 bit) to change the dpi resolution of multiple **.jpg** files. I've always used the following command for the conversion in batch:
`exiftool -XResolution=96 -YResolution=96 -ResolutionUnit=inches -P -overwrite_original ExifTool`
_ExifTool_ is the folder's name where I put the files to convert.

Now I find myself dealing with multiple **.WebP** images that are at 72dpi resolution. 
I convert them to .jpg format from the prompt with
`cmd /c ren *.webp *.jpg`
but at that point ExifTool, if i run the above command, tells me
`Error: Not a valid JPG (looks more like a RIFF)`
So I've to change the dpi value (only that, no other parameters) when the files are still in .WebP format. Only after that, convert them to .jpg with the prompt, finally obtaining 96dpi images in format .jpg. At least I think so ... I hope I haven't written nonsenses. 

[Phil Harvey's official website](https://exiftool.org/) specifies that the metadata of .WebP format can be both Read and Write (unlike the .RIFF format). The problem is that I don't have idea **what command to give** to ExifTool. Please, could someone help me?
Thanks for Your kind attention and I apologize if my issue is banal.

**Comment by StarGeekSpaceNerd** [comment]
> I convert them to .jpg format from the prompt with

This does not convert them.  Even though they now have a jpg extension, they are still webp files.  Exiftool won't touch them in this circumstance so as not to corrupt the files by trying to write them as jpg.

Have you tried your first command on the webp files?  I believe that it would set the EXIF resolution tags.  The biggest problem is whether or not your other programs will read those resolution tags.

If you have a webp file that already shows a different dpi, use the command in [FAQ #3](https://exiftool.org/faq.html#Q3) to try and figure out what tags your other programs are reading and set those.

**Comment by StarGeekSpaceNerd** [comment]
Can you find a webp that has a resolution different than 72dpi to begin with?  It's quite possible that Window doesn't actually read any dpi from a webp file and is simply displaying a default value.

**Comment by Arekkusu1998** [comment]
Before running any ExifTool modify commands on the file, by running `exiftool -a -G1 -s "C:\Users\Utente\ExifTool"`, **no dpi resolution is indicated**. 
> Can you find a webp that has a resolution different than 72dpi to begin with?

No, I'm sorry: if I open "Properties", every WebP file I've on my PC is indicates at 72dpi.

**Comment by StarGeekSpaceNerd** [comment]
I tested about a dozen webp files I already had that had a different resolution and Windows displayed 72dpi for all of them.  This included files with the `XResolution`/`YResolution` in both EXIF and XMP.

I am strongly inclined to believe that Windows doesn't read any dpi values in a webp file.

But this did remind me that I haven't check to see if Windows would read any tags in a webp, so I thank you for that.

**Comment by Arekkusu1998** [comment]
Sorry me, I updated my last comment late: as I wrote, You're right that Windows seems to read .WebP files at 72dpi by default.

**Comment by StarGeekSpaceNerd** [comment]
> But that doesn't explain why it's not possible to change its value 

It's not possible to change the value because Windows isn't reading any DPI value from the file.  It has been hard coded to display 72dpi for *all* webp files.

You can't force any program (OSs included) to read data that it hasn't been programmed to read.

**Comment by Arekkusu1998** [comment]
Ouch, it's basically a dead end issue... poor me😢!

**Comment by boardhead** [comment]
The solution is to report this bug to Microsoft.

**Comment by StarGeekSpaceNerd** [comment]
I updated my [Windows Metadata post](https://exiftool.org/forum/index.php?topic=6591.msg32875#msg32875) to include what Windows will read in a webp file.
