### ISSUE TITLE
PDF 2.0 spec no longer held hostage by ISO

### ISSUE THREAD

**Issue by tballison** [exiftool/exiftool#199]
Ref: https://github.com/exiftool/exiftool/blob/19d09138d8ad75d0221435fb7a16a415625a53e5/lib/Image/ExifTool/PDF.pm#L2123

You can download a free copy as of about a week ago: https://www.pdfa.org/resource/iso-32000-pdf/

**Comment by tballison** [comment]
Side note: I :heart: ExifTool, and that error message has caused me great joy!

**Comment by tballison** [comment]
This is how I learned about that error msg: https://openpreservation.org/blogs/pdf-validation-with-exiftool-quick-and-not-so-dirty/

**Comment by tballison** [comment]
Doh...sorry.

**Comment by boardhead** [comment]
Thanks for the note.  My hope is to be able to add PDF 2.0 support soon.

- Phil

**Comment by StarGeekSpaceNerd** [comment]
> Doh...sorry.

Nothing to be sorry about.  I only saw it because it popped up in my feed on reddit in a low traffic subreddit and had almost no upvotes.  Pretty much pure chance that I saw it.  The more eyes looking for things like this, the better.

**Comment by boardhead** [comment]
Version 12.61 has official support for PDF 2.0
