### ISSUE TITLE
Add write support for custom SlantRange 3px XMP tags

### ISSUE THREAD

**Issue by OneGneissGuy** [exiftool/exiftool#20]
Cannot edit MicaSense Altum XMP tags because a config file for the custom XMP tags is not yet defined. I have attached a zipped single channel (green) tiff collected by the SlantRange 3px. 

I need to edit these EXIF tags:

* Make
* Model

and these custom XMP tags:

* BandName
* CentralWavelength
* WavelengthFWHM
* RigName
* RigCameraIndex

[SlantRangeTiff.zip](https://github.com/exiftool/exiftool/files/3277733/SlantRangeTiff.zip)

**Comment by boardhead** [comment]
The config file of #19 gives you the ability to write these
