### ISSUE TITLE
Add LICENSE file to GitHub

### ISSUE THREAD

**Issue by xmha97** [exiftool/exiftool#200]
Please add the LICENSE file to GitHub.
Like this repository.
https://github.com/microsoft/PowerToys
https://github.com/microsoft/PowerToys/blob/main/LICENSE
![image](https://user-images.githubusercontent.com/23485114/232398482-b5ed1292-cd28-4b22-8054-f6674564f440.png)
Thanks.

**Comment by boardhead** [comment]
OK.  I'll try this again.  I failed on my first attempt:  https://github.com/exiftool/exiftool/pull/177

- Phil

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by boardhead** [comment]
Done.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by balasankarc** [comment]
@boardhead The LICENSE file uploaded to the repository - https://github.com/exiftool/exiftool/blob/master/LICENSE - has only GPLv3 in it. Exiftool is mimicking Perl's license, right? So, shouldn't it be GPL1+ or Artistic?

**Comment by svenclaesson** [comment]
> @boardhead The LICENSE file uploaded to the repository - https://github.com/exiftool/exiftool/blob/master/LICENSE - has only GPLv3 in it. Exiftool is mimicking Perl's license, right? So, shouldn't it be GPL1+ or Artistic?

Today I also found out about this. This file where added between version 12.60 -> 12.61. @boardhead please clarify. 🙏

**Comment by boardhead** [comment]
It is the Perl Artistic License, but I couldn't find the file for that.  Perl's Artistic license also allows you to select GPL, which is what I did.  Personally I don't care.  It is free.  Attach whatever license you want and I'll implement that.
