### ISSUE TITLE
-L / -charset Latin1 doesn't apply to json output

### ISSUE THREAD

**Issue by karlp** [exiftool/exiftool#202]
I have some files that have Latin1/ISO-8859-1 encoded captions (because... no good reasons, just some old software), and reading these from the command line, on a utf8 terminal works just fine, with the -L options...

_Good:_ Hornvík
**Bad:** HornvÃ­k

```
$ exiftool -G  -n *8114* -IPTC:Caption-Abstract
[IPTC]          Caption-Abstract                : Wolfgang, fresh off the boat in HornvÃ­k.
$ exiftool -G  -n *8114* -IPTC:Caption-Abstract -L
[IPTC]          Caption-Abstract                : Wolfgang, fresh off the boat in Hornvík. 
```

However, when requesting JSON output (for some downstream processing) the -L option seems to be ignored?

```
$ exiftool -G  -n -j -L *8114* -IPTC:Caption-Abstract 
[{
  "SourceFile": "2007_07_30-11_29_50--crw_8114_JFR.jpg",
  "IPTC:Caption-Abstract": "Wolfgang, fresh off the boat in HornvÃ­k\r"
}]
$ exiftool -G  -n -j  *8114* -IPTC:Caption-Abstract 
[{
  "SourceFile": "2007_07_30-11_29_50--crw_8114_JFR.jpg",
  "IPTC:Caption-Abstract": "Wolfgang, fresh off the boat in HornvÃ­k\r"
}]
```

This may be "as designed" but it feels inconsistent.  If there's an alternative method for getting the decoding done correctly into JSON output, I'm all ears.

exiftool is version 12.50, which I know isn't the latest, but I can't see anything related in the changelog that seems remotely likely to have fixed this in the meantime either.

**Comment by StarGeekSpaceNerd** [comment]
What is the values of `IPTC:CodedCharacterSet`?  From what I can tell from the [IEC_2022 wiki page](https://en.wikipedia.org/wiki/ISO/IEC_2022), Latin1 should have an `IPTC:CodedCharacterSet` value of "ESC . A"

Of course, I could be way off, as my knowledge here is limited.

**Comment by karlp** [comment]
Ok, this is resolved.  I'm still not sure I really understand what -L is meant to do, but my underlying problem was that I had written _utf8_ to the IPTC caption-abstract fields.  (I'm guessing I misread the docs that IPTC was meant to be always latin1 20 years ago when I was hacking these perl scripts back then and wasn't properly encoding my captions)

`exiftool -v3` was super helpful to finally see the actual bytes stored in the file, thought I'd finally found `$et->GetValue("IPTC:Caption-Abstract", "Raw");` as well.

I'm now getting the correct utf8 back into json:
```
$ exiftool -G -s -j -charset iptc=utf8 -IPTC:Caption-Abstract 2007_07_30-11_29_50--crw_8114_JFR.jpg
[{
  "SourceFile": "2007_07_30-11_29_50--crw_8114_JFR.jpg",
  "IPTC:Caption-Abstract": "Wolfgang, fresh off the boat in Hornvík\r"
}]
```
And now it all works in downstream apps again, yay!  Thanks for the extra pointers, sorry for the noise!
