### ISSUE TITLE
Shebang line caused exiftool to fail

### ISSUE THREAD

**Issue by thvv** [exiftool/exiftool#209]
The first line of exiftool as installed by homebrew 4.0.22 on macOS 13.4.1 was #!/usr/bin/perl5.30 -w
executing it failed with

[thvv ~]$ exiftool
Can't load '/opt/homebrew/lib/perl5/5.36/darwin-thread-multi-2level/auto/File/Glob/Glob.bundle' for module File::Glob: dlopen(/opt/homebrew/lib/perl5/5.36/darwin-thread-multi-2level/auto/File/Glob/Glob.bundle, 0x0001): symbol not found in flat namespace '_PL_env_mutex' at /opt/homebrew/lib/perl5/5.36/XSLoader.pm line 97.
 at /opt/homebrew/lib/perl5/5.36/darwin-thread-multi-2level/File/Glob.pm line 64.
Compilation failed in require at /opt/homebrew/bin/exiftool line 994.
BEGIN failed--compilation aborted at /opt/homebrew/bin/exiftool line 994.
Undefined subroutine &main::SetWindowTitle called at /opt/homebrew/bin/exiftool line 359.
END failed--call queue aborted at /opt/homebrew/bin/exiftool line 994.

I changed the first line to #!/usr/local/bin/perl and it worked.

**Comment by StarGeekSpaceNerd** [comment]
The might be a problem with homebrew.  If you go to the [main exiftool page](https://exiftool.org/) and download the main archive (first "Download" link), the `exiftool` in that shows `#!/usr/bin/perl -w`

**Comment by thvv** [comment]
Thanks StarGeekSpaceNerd.  
The Perl on my machine was installed by Homebrew and is version 5.36.0.  
The exiftool that Homebrew installed had a shebang for Perl 5.30, which I do not have.
I am not a homebrew expert: it looks like https://docs.brew.sh/Formula-Cookbook#rewriting-a-script-shebang is relevant...
but it seems like this step is something that should have been done when exiftool's "formula" was created.
I am running homebrew 4.0.22.  
I grepped /opt/homebrew/bin for shebang lines containing "perl" and there were no others specifying a Perl version.
Some tools had #!/opt/homebrew/opt/perl/bin/perl and others had #!/usr/local/bin/perl ... no others pointed to a specific version.
-- tom

**Comment by StarGeekSpaceNerd** [comment]
If you go to the top of this page, click "Code", and then click the exiftool source file, you will see that exiftool does not require a specific version of Perl.

You seem to be under the impression that Phil, the author of exiftool, is writing the homebrew script.  He is not.  You will have to contact the author of the Homebrew script.

**Comment by thvv** [comment]
On Jun 23, 2023, at 10:42 AM, StarGeekSpaceNerd ***@***.***> wrote:
> 
> If you go to the top of this page, click "Code", and then click the exiftool source file, you will see that exiftool does not require a specific version of Perl.
> You seem to be under the impression that Phil, the author of exiftool, is writing the homebrew script. He is not. You will have to contact the author of the Homebrew script.

Thank you for the pointer to the homebrew formula.
As you said, it does not specify Perl 5.30 anywhere. 
I apologize for posting to the wrong forum.
