### ISSUE TITLE
Fix black level detection for Canon EOS 1000D

### ISSUE THREAD

**Issue by photopea** [exiftool/exiftool#21]
When you open [this image](http://www.rawsamples.ch/raws/canon/RAW_CANON_1000D.CR2)  in ExifTool, it says, that the Black Level is 1024. 

However, when I parse the picture data, it is necessary to use a Black Level 255, for the picture to make sense. Also, in [this database ](https://github.com/darktable-org/rawspeed/blob/develop/data/cameras.xml), Canon EOS 1000D has a black level of 255.

Is it possible to make ExifTool read black level 255 from this photo?

**Comment by boardhead** [comment]
Try this command:

exiftool -p '${blacklevel;$_=int($_/4)' FILE

(use double quotes instead of single quotes if you are on Windows)

Also, you could create a user-defined tag do to this math for you.  See the [sample config file](http://owl.phy.queensu.ca/~phil/exiftool/config.html) for details.

- Phil

**Comment by photopea** [comment]
But it would just divide the black level by 4 for all cameras, right? I am curious, if it is possible to extract the value of 255 from this file, which I hope is stored in it somewhere.

**Comment by boardhead** [comment]
There may be other places where the black level is stored with different scaling, but these haven't yet been decoded and I have no way to do this myself.  You can use the -U option to see most of the relevant unknown information .  Let me know if you discover the meaning of any of it.

**Comment by boardhead** [comment]
Closing this issue because ExifTool reports the value in the file and there is no clear alternative.
