### ISSUE TITLE
How does it write the non-standard IPTC in zTXT chunks?

### ISSUE THREAD

**Issue by StefanOltmann** [exiftool/exiftool#210]
I'm the author of [Kim](https://github.com/Ashampoo/kim), the Kotlin Image Metadata library.

I tried to write the IPTC block as a zTXT PNG chunk in the same way ExifTool does this, so that my library is compatible with ExifTool.

Unfortunately the result is not the same.

Can someone point me to the code that writes the block?
I'm looking for a specification.

Thank you.

**Comment by StarGeekSpaceNerd** [comment]
I can see in `WritePNG.pl` on [line #332](https://github.com/exiftool/exiftool/blob/d35e9e26e0a8b443dae307f55d0a4a067d311a16/lib/Image/ExifTool/WritePNG.pl#L332) the code that sets up writting IPTC data.  That calls [`WriteDirectory`](https://github.com/exiftool/exiftool/blob/d35e9e26e0a8b443dae307f55d0a4a067d311a16/lib/Image/ExifTool/Writer.pl#L4169) in `Writer.pl` to create a buffer with what I assume is the IPTC structure.  The buffer is then passed to [`WriteProfile`](https://github.com/exiftool/exiftool/blob/d35e9e26e0a8b443dae307f55d0a4a067d311a16/lib/Image/ExifTool/WritePNG.pl#L67).

That's the best I can do.  Phil would have to answer if there is more.

**Comment by StefanOltmann** [comment]
@StarGeekSpaceNerd Thank you a lot. That helped me. :)

But there must be more magic involved, unfortunately.

What I wrote is not recognized by ExifTool, even if according to https://www.nayuki.io/page/png-file-chunk-inspector the block is the same.

How can that be?

GIMP can show both files metadata.

[exiftool.png](https://github.com/exiftool/exiftool/assets/9299303/737683a0-ca1c-4f7d-971f-63e85141814f)

[my_version.png](https://github.com/exiftool/exiftool/assets/9299303/3a4c7895-7e13-4f66-bf39-e5829137a5c8)

Is there anything else I need to do for ExifTool?

**Comment by boardhead** [comment]
ExifTool doesn't recognize your profile because the your header lacks the leading newline:

  0000: 49 50 54 43 20 70 72 6f 66 69 6c 65 0a 20 20 20 [IPTC profile.   ]

it should be:

  0000: 0a 49 50 54 43 20 70 72 6f 66 69 6c 65 0a 20 20 [.IPTC profile.  ]

- Phil

**Comment by StefanOltmann** [comment]
Thanks, Phil, that was the problem. With the next update my library will write that data in an ExifTool-compatible way.
