### ISSUE TITLE
Can't write EXIF date tags in MP4 file

### ISSUE THREAD

**Issue by Curley-Joe** [exiftool/exiftool#211]
I can't update the EXIF date tags in this MP4 file. Tried with latest 12.64 version of exiftool. Instead of updating the EXIF tag it creates a new XMP tag. See MP4 file and sample script in attached zip file.

[files.zip](https://github.com/exiftool/exiftool/files/12047142/files.zip)

**Comment by boardhead** [comment]
EXIF is non-standard in MP4 files, and ExifTool currently writes only some of the various flavours.  On the plus side, there isn't much other than ExifTool that can read this anyway.

- Phil

**Comment by Curley-Joe** [comment]
Thanks for the information.

But there's still a bit of an inconsistency with how the EXIF tags are handled.

If I run
```
exiftool -P $file '-CreateDate<MediaModifyDate'
```
It will create a new tag XMP tag for CreateDate, but if I run
```
exiftool -P $file -CreateDate+=1
```
it won't.

**Comment by StarGeekSpaceNerd** [comment]
That is as intended.  From the docs on the [`-TAG[+-^]=[VALUE]` option](https://exiftool.org/exiftool_pod.html#TAG---VALUE)
>  += may also be used to increment numerical values (or decrement if VALUE is negative)

It's not used to create new tags.

From the [Quicktime tags page](https://exiftool.org/TagNames/QuickTime.html)
> When writing, ExifTool creates both QuickTime and XMP tags by default, but the group may be specified to write one or the other separately

This is a bit different from most cases, as exiftool will usually create a tag in one location and updated any additional tags with the same name, with Shortcut and Composite tags being the most common exceptions.  But it is useful in this case as some programs read the Quicktime tags (usually Apple apps) and others, specifically Adobe apps, will read the XMP tags.
