### ISSUE TITLE
Error: [minor] DNG Version 1.7.0.0 not yet tested

### ISSUE THREAD

**Issue by yoavchai** [exiftool/exiftool#212]
I'm running latest exiftool 12.64, do you know when version 1.7 going to be supported?
Is there any workaround i can do?
I have a fille with DNG Backward Version 1.3, can i make it work for this file?

Thanks!

DNG Version                     : 1.7.0.0
DNG Backward Version            : 1.3.0.0

**Comment by boardhead** [comment]
As far as I know the DNG 1.7 specification is has not yet been released.  ExifTool will support it shortly after I have this specification.  Until then, you can use the IgnoreMinorErrors option (-m) to write these files.  In all probability, this should work fine (unless Adobe made another blunder in the specification to break forward compatibility).

- Phil
