### ISSUE TITLE
Infinite loop in BigTIFF handling

### ISSUE THREAD

**Issue by zhrep** [exiftool/exiftool#214]
In the file `exiftool/lib/Image/ExifTool/BigTIFF.pm` the function `ProcessBigIFD` can loop infinitely if the next IFD references previous directory. Sample file is attached.

[loop.zip](https://github.com/exiftool/exiftool/files/12131398/loop.zip)

**Comment by boardhead** [comment]
Great, thanks.  This will be fixed in 12.65

- Phil
