### ISSUE TITLE
Missing an option to overwrite target if using -o option

### ISSUE THREAD

**Issue by kabakakao** [exiftool/exiftool#221]
Hi together,
I would like to use the -o option to set a custom out folder. That works great, if the target does not exist.
But now, I have to update several files, which were created with a subset of metadata and I would like to add some. But there cannot we overwritten, or do I miss anything? The -overwrite_original will delete my Original while using the -o option.

**Comment by StarGeekSpaceNerd** [comment]
This is by design.  From the docs on the [`-o` (`-out`) option](https://exiftool.org/exiftool_pod.html#o-OUTFILE-or-FMT--out)

> Existing files will not be overwritten.

Phil explains in [this post](https://exiftool.org/forum/index.php?topic=6643.msg33172#msg33172)

> I don't think it is a good idea to allow overwrite of output image files without warning.  I understand that you could overwrite images with -w! if you really tried, but I would think that the odds of doing this by accident with -o! would be much higher.  So although I see how this could be useful, I resist adding this feature because of the hazards involved.

**Comment by kabakakao** [comment]
Thanks for the really quick reply. Then I have to remove the file before writing or take a look at -w!

**Comment by StarGeekSpaceNerd** [comment]
I believe that the context regarding `-w!` was about possibly overwriting a main image while extracting a thumbnail image.  I can't think of a way to use `-w` to replace `-o`.

**Comment by boardhead** [comment]
StarGeek is correct.  The -w functionality is for metadata output, not image file output.
