### ISSUE TITLE
Add VideoFullRangeFlag to QuickTime parser

### ISSUE THREAD

**Issue by kmilos** [exiftool/exiftool#225]
Missing from https://github.com/exiftool/exiftool/blob/6e175fd7662e02f6d252b31ebb67222fbc6f8c37/lib/Image/ExifTool/QuickTime.pm#L2897

but should be the same as the PNG one (could be differently stored though, i.e. as [a single bit](https://github.com/strukturag/libheif/issues/119#issuecomment-521958102)?): https://github.com/exiftool/exiftool/blob/6e175fd7662e02f6d252b31ebb67222fbc6f8c37/lib/Image/ExifTool/PNG.pm#L506

~~Also note that there might a difference in the bit position between ISO14496-12/ISO1544-12 (ISO BMFF) and ISO29199-2 (JPEG XR)?~~ Edit: JXR parsing is irrelevant here.

**Comment by boardhead** [comment]
I would need details about how this is stored to be able to decode this.  (Other tags in this structure are 16-bit integer... what about this one?)  Samples with and without this flag set would be sufficient to be able to figure this out.

- Phil

**Comment by kmilos** [comment]
> Other tags in this structure are 16-bit integer... what about this one

As the linked snippet of the spec says, it is the the MSB of single byte.

You can perhaps test w/ these: https://chromium.googlesource.com/chromium/src/+/113e7f3b0acb55943aa7c8ce80d8d97424cd100c/third_party/blink/web_tests/images/resources/avif/README.md

**Comment by boardhead** [comment]
Thanks.  I'll add decoding for this to ExifTool 12.68

- Phil

**Comment by kmilos** [comment]
Confirmed working in 12.68, thanks!
