### ISSUE TITLE
PentaxModelID 0x132d6

### ISSUE THREAD

**Issue by AdamMainsTL** [exiftool/exiftool#226]
As of 12.65 it is marked as Unknown and I don't see it in the repo. From what I can tell, this is the PENTAX K-3 Mark III Monochrome.

```exiftool image.PEF -Make -Model -PentaxModelID
Make                            : RICOH IMAGING COMPANY, LTD.
Camera Model Name               : PENTAX K-3 Mark III Monochrome
Pentax Model ID                 : Unknown (0x132d6)
```

By the way, is there a place I should be reporting these or making PRs? It doesn't seem like this repo accepts PRs which is why I'm making this an issue.

---

Edit: Since I'm talking about this model, I might as well add some other unknown values that may be of use.

```
Pentax Model ID                 : Unknown (0x132d6)
Raw Development Process         : Unknown (21)
Quality                         : Unknown (9)
Image Tone                      : Unknown (32768)
ISO Auto Parameters             : Unknown (3 124)
Flash Mode                      : On, Fired; Unknown (0x40c)
```
I believe the Model ID should be `K-3 Mark III Monochrome` and Raw Development Process should be `21 (K-3IIIMonochrome)`. 

For the others I'm unsure what they could mean exactly, but I believe Image Tone might just be another Monochrome flag. Will try to find more images to verify.

**Comment by StarGeekSpaceNerd** [comment]
Is the lens still unknown if you upgrade to ver 12.67?  Two Pentax lens were added.  See [this exiftool forum's post](https://exiftool.org/forum/index.php?topic=3833.msg81711#msg81711).

**Comment by AdamMainsTL** [comment]
This is not a lens, this is the model ID. I did update to 12.67 and it still shows as unknown.

**Comment by AdamMainsTL** [comment]
I've updated the original post with some more unknown tags instead of making separate issues for them. Out of all of them I only know what 2 of them should be. I think Image Tone might be another monochrome flag but not sure how to confirm it.

**Comment by StarGeekSpaceNerd** [comment]
> This is not a lens, this is the model ID

Ooops, sorry.  Don't know why I was thinking lens.

Phil will have to take a look and might have more questions.

**Comment by kmilos** [comment]
See also https://github.com/Exiv2/exiv2/pull/2774

**Comment by boardhead** [comment]
I'll add the new model, RawDevelopmentProcess, ImageTone 32768 = "n/a", and Quality 9 = "Monochrome".

If you have better suggestions or decode any new information please let me know.

- Phil

**Comment by boardhead** [comment]
This version is now available
