### ISSUE TITLE
Insta360 - IMU data mixed up.

### ISSUE THREAD

**Issue by nofreewill42** [exiftool/exiftool#227]
I believe that for .insv files from the Insta360s, the resulting Accelerometer and Angular Velocity values are swapped.

**Comment by nofreewill42** [comment]
This is read from the orientation values, while I carried the camera throughout my little town.

![image](https://github.com/exiftool/exiftool/assets/14865017/a804de1b-72a1-4b88-a6ee-1394fb656a23)

**Comment by boardhead** [comment]
Thanks.

So you are saying that the extracted values for Accelerometer and AngularVelocity should be swapped?  Can you provide a sample video?

**Comment by boardhead** [comment]
I just took a closer look at a couple of Insta360 INSV samples that I have.  The Accelerometer values in both samples have one component which is always close to 1.  This is presumably the Z component (ie. gravity).  Readings like this for angular velocity would mean that the camera is always spinning around, which is not reasonable.

I'm closing this issue, but we can re-open it if you can provide a sample showing this effect.

- phil
