### ISSUE TITLE
Can't copy metadata to JXL files

### ISSUE THREAD

**Issue by fernandoarmengol** [exiftool/exiftool#230]
<img width="701" alt="image" src="https://github.com/exiftool/exiftool/assets/71931361/a9b3cf65-0df7-489a-8db5-6522f02fd6b2">

**Comment by boardhead** [comment]
Use the -m option to ignore this minor error.

Note that this will add a BMFF container around the JXL codestream, so the file will be a different format (although still .jxl extension).

- Phil

**Comment by fernandoarmengol** [comment]
It worked, thanks, I was not aware of that option.
