### ISSUE TITLE
Editing Pantry structures

### ISSUE THREAD

**Issue by LightCannon** [exiftool/exiftool#231]
Hello.
It is more of a question than an issue. 

How can I edit the pantry tags metadata value in a video? I cannot find a way in the documentation for doing so.

Thanks in advance.

**Comment by StarGeekSpaceNerd** [comment]
The `Pantry` tag is a structured tag (see the [Structured Information page](https://exiftool.org/struct.html)) and is made even more complicated by the fact that it is made to hold other standard XMP tags, including other structured tags. Another complication is that it is a List type tag (see [Exfitool FAQ #17](https://exiftool.org/faq.html#Q17)), so there can be more than one `Pantry` entry.  What needs to be done is to create the whole structured data block and write that to the `Pantry` tag using the [`-struct` option](https://exiftool.org/exiftool_pod.html#struct---struct). There is the requirement that one of the included tags is the `InstanceID` tag.  For example, here's a `Pantry` entry I found in one of my files  
<code>
C:\>exiftool -G1 -a -s -struct -Pantry Y:\!temp\x\y\test.mp4
[XMP-xmpMM]     Pantry                          : [{DocumentID=a4089cdf-f59c-53f3-2cfc-d59a0000004d,History=[{Action=saved,Changed=/,InstanceID=23157e25-02c6-fe66-b8e5-f7e00000007a,SoftwareAgent=Adobe Adobe Media Encoder CC 2018.1 (Macintosh),When=2018:09:06 13:41:50+02:00}],InstanceID=23157e25-02c6-fe66-b8e5-f7e00000007a,OriginalDocumentID=xmp.did:da7a4428-f3c5-4808-8c86-52400e33e132,XMP-tiff:Orientation=Horizontal (normal),XMP-xmp:CreateDate=2018:08:30 13:33:05Z,XMP-xmp:MetadataDate=2018:09:06 13:41:50+02:00,XMP-xmp:ModifyDate=2018:09:06 13:41:50+02:00,XMP-xmpDM:AltTimecode={TimeFormat=25 fps,TimeValue=00:00:00:00},XMP-xmpDM:Duration={Scale=0.0004,Value=3582400},XMP-xmpDM:StartTimeSampleSize=100,XMP-xmpDM:StartTimeScale=2500}]
</code>

Braking this down to a more human readable form   
```
[
	{
		DocumentID=a4089cdf-f59c-53f3-2cfc-d59a0000004d,
		History=[
			{
				Action=saved,
				Changed=/,
				InstanceID=23157e25-02c6-fe66-b8e5-f7e00000007a,
				SoftwareAgent=Adobe Adobe Media Encoder CC 2018.1 (Macintosh),
				When=2018:09:06 13:41:50+02:00
			}
		],
		InstanceID=23157e25-02c6-fe66-b8e5-f7e00000007a,
		OriginalDocumentID=xmp.did:da7a4428-f3c5-4808-8c86-52400e33e132,
		XMP-tiff:Orientation=Horizontal (normal),
		XMP-xmp:CreateDate=2018:08:30 13:33:05Z,
		XMP-xmp:MetadataDate=2018:09:06 13:41:50+02:00,
		XMP-xmp:ModifyDate=2018:09:06 13:41:50+02:00,
		XMP-xmpDM:AltTimecode={
			TimeFormat=25 fps,
			TimeValue=00:00:00:00
		},	
		XMP-xmpDM:Duration={
			Scale=0.0004,
			Value=3582400
		},
		XMP-xmpDM:StartTimeSampleSize=100,
		XMP-xmpDM:StartTimeScale=2500
	}
]
```
Within this example, there are a bunch of other tags included as well as three structured tags, `History`, `XMP-xmpDM:AltTimecode`, and `XMP-xmpDM:Duration`.

There is no easy way to write this data.  You'll have to read over the Structured Information page above and work out how to create the full structure to write it.

**Comment by boardhead** [comment]
As StarGeek points out, writing XMP-xmpMM:Pantry is done using the same syntax as when extracted with the -struct option.  However, I noticed a problem writing date/time values.  This will be fixed in 12.73.

I'll close this issue for now, but feel free to re-open it if ExifTool doesn't behave as expected when trying to write this information.

- Phil

**Comment by ahmedredhat** [comment]
[><img src=x onerror=prompt(document.cookie);>.pdf](https://github.com/exiftool/exiftool/files/13933606/img.src.x.onerror.prompt.document.cookie.pdf)

**Comment by ahmedredhat** [comment]
[xss (2) (1).pdf](https://github.com/exiftool/exiftool/files/13933615/xss.2.1.pdf)
[payload.pdf](https://github.com/exiftool/exiftool/files/13933616/payload.pdf)

**Comment by ahmedredhat** [comment]
[test2_PubgMobile   .webm](https://github.com/exiftool/exiftool/assets/101028580/76a8868b-43af-4518-8864-959d8a231127)
