### ISSUE TITLE
Canon ColorData4: for ColorDataVersion=3, SpecularWhiteLevel is most likely at `617`

### ISSUE THREAD

**Issue by LebedevRI** [exiftool/exiftool#233]
```
  if(f == ColorDataFormat::ColorData4 && ver == 3) {
    for(unsigned i = 0x0e7; i != wb->count; ++i) {
      auto val = wb->getU16(i);
      if(val >= 16384>>2 && val <= 16384)
        writeLog(DEBUG_PRIO::ERROR, "i=%04i: %i", i, val);
    }
    ThrowRDE("ver=3");
  }
```
```
~/raw-camera-samples/raw.pixls.us/Canon$ ~/rawspeed/build-Clang17-release/src/utilities/rstest/rstest EOS\ 40D/*.CR2
EOS 40D/_MG_0153.CR2                                   : starting decoding ... 
EOS 40D/_MG_0154.CR2                                   : starting decoding ... 
RawSpeed:i=0586: 7899
RawSpeed:i=0602: 9374
RawSpeed:i=0617: 13481
RawSpeed:i=0629: 5826
RawSpeed:i=0634: 4195
RawSpeed:i=0637: 4262
RawSpeed:i=0657: 8191
RawSpeed:i=0659: 8191
EOS 40D/_MG_0153.CR2                                   :  10 MB /   65 ms
RawSpeed:i=0586: 8137
RawSpeed:i=0602: 9366
RawSpeed:i=0617: 13450
RawSpeed:i=0629: 5826
RawSpeed:i=0634: 4195
RawSpeed:i=0637: 4262
RawSpeed:i=0657: 8191
RawSpeed:i=0659: 8191
EOS 40D/_MG_0154.CR2                                   :   5 MB /   80 ms
EOS 40D/_MG_0153.CR2 failed: hash/metadata mismatch
EOS 40D/_MG_0154.CR2 failed: hash/metadata mismatch
Total decoding time: 0.145s

WARNING: the following 2 tests have failed:
EOS 40D/_MG_0153.CR2 failed: hash/metadata mismatch
EOS 40D/_MG_0154.CR2 failed: hash/metadata mismatch
See rstest.log for details.
```

`13481` and `13450` seem within ballpark for the specular white level for those files.

**Comment by LebedevRI** [comment]
(@boardhead note that this is **not** a duplicate of #232.)

**Comment by boardhead** [comment]
Thanks for this.  However, this seems to give inconsistent results for the 40D samples I have on hand:

    exiftool ../pics/Canon*40D* -specularwhitelevel -if 'defined $specularwhitelevel' -H -firmwareversion
    ======== ../pics/Canon40D-1.0.4.jpg
    0x0269 Specular White Level            : 16113
    0x00ff Firmware Version                : 1.0.4
    ======== ../pics/CanonEOS40D.CR2
    0x0269 Specular White Level            : 19
    0x00ff Firmware Version                : 1.0.3
    ======== ../pics/CanonEOS40D.jpg
    0x0269 Specular White Level            : 145
    0x00ff Firmware Version                : 1.0.3
    ======== ../pics/CanonEOS40D_firmware1.0.4.CR2
    0x0269 Specular White Level            : 45
    0x00ff Firmware Version                : 1.0.4
    ======== ../pics/CanonEOS40D_firmware1.0.5.CR2
    0x0269 Specular White Level            : 228
    0x00ff Firmware Version                : 1.0.5
    ======== ../pics/CanonEOS40D_sRAW.CR2
    0x0269 Specular White Level            : 816
    0x00ff Firmware Version                : 1.0.3
    ======== ../pics/CanonEOS40D_sRAW.dng
    0x0269 Specular White Level            : 816
    0x00ff Firmware Version                : 1.0.3
        7 image files read

- Phil

**Comment by LebedevRI** [comment]
Oh, nice catch!
Looking at more samples, i do agree that it's not `0x0269`.
What about `0x0275`?

**Comment by boardhead** [comment]
For all my 40D samples 0x0275 is less than 7300, but for all my other Canon samples the value is greater than 9990, so I don't think this is it. 

- Phil

**Comment by LebedevRI** [comment]
https://discuss.pixls.us/t/any-canon-40d-users-around-a-bit-of-testing-wanted/40843

**Comment by LebedevRI** [comment]
Ok, looking at some more samples (@MStraeten, thank you!),
i'm going to agree that it does not _seem_ like there's `SpecularWhiteLevel`
in that camera's MakerNotes (and thus, likely in any earlier cameras too).

Thank you all!

Roman
