### ISSUE TITLE
Error: [minor] Different 'rdf:about' attributes not handled

### ISSUE THREAD

**Issue by freetom** [exiftool/exiftool#234]
I am attempting to clear certain EXIF attributes from a set of images using `exiftool` but it is failing on some images with this output:
 ```
Warning: [minor] Excessive number of items for crs:RetouchAreasMasksDabs. Processing may be slow - /blablabla/image.jpg                                       
Error: [minor] Different 'rdf:about' attributes not handled - /blablabla/image.jpg       
0 image files updated
1 files weren't updated due to errors      
```

Why wouldn't it handle the case of different 'rdf:about' attributes?
By the way is 'rdf:about' attribute supposed to be seen in the standard info dump of `exiftool`? Because I don't see it

**Comment by boardhead** [comment]
You should see the "About" tag in the output when reading a file if you get this warning.  If not, post a sample and I'll take a look.

Add the -m option to ignore minor errors and allow this file to be written, but the rdf:about values will be changed so they are consistent.

- Phil

**Comment by freetom** [comment]
The 'About' tag says:
```
About                           : DJI Meta Data
```

But thanks a lot, using the `-m` option resolves the problem! 

I should have read the man!
