### ISSUE TITLE
Documentation issue on "LimitLongValues"

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#240]
= "LimitLongValues" default may cause backward compatibility issues =

    https://exiftool.org/history.html#v12.73
    https://exiftool.org/ExifTool.html#LimitLongValues
    .
    Default 60 at the moment.

    Related:
    https://exiftool.org/forum/index.php?topic=15547#msg83491
    https://exiftool.org/exiftool_pod.html#n---printConv

    Please verify. (probably a documentation issue?)

**Comment by boardhead** [comment]
I don't understand your concern.  There should be no backward compatibility issues.

- Phil

**Comment by boardhead** [comment]
Correct.

**Comment by MasterInQuestion** [comment]
Probably linking to this post in the documentation would be the easiest fix...

**Comment by boardhead** [comment]
I don't understand this issue.

**Comment by StarGeekSpaceNerd** [comment]
I believe that they want it documented, even though it only affects a few tags.

@MasterInQuestion, this only affects some tags which are usually not usable by people, only the programs that write them.  The Pantry video tags or the DocumentHistory tags, for example.  These tags can hold an extreme amount of data.

This won't affect the more commonly used tags, such as `Description`.  For example, I wrote to the `Description` a 7,000 character string and exiftool doesn't truncate it.

The use case for this option was very specific.  As per the forum post you linked, it was for EXIF tag ID 0x9999, which exiftool doesn't even display by default.

**Comment by boardhead** [comment]
They want "it" documented?  What is "it"?  Sorry for being dense here.

The fact that it was originally hardcoded?  (I don't see this as being relevant for future versions going forward, unless you meant to document it in the release notes.)  Which tags are affected?  (I don't see this as being useful, plus a long list like this would clutter the documentation and be a headache to maintain in the future, although maybe it would assuage some fears if I mentioned that they are mostly Unknown tags.)

- Phil

**Comment by StarGeekSpaceNerd** [comment]
Probably something along those lines, and I agree with you on the usefulness.  It also seems to me that there is a Google translation problem here.

**Comment by MasterInQuestion** [comment]
Thanks for the explaining.

    “API Changes: Added ["LimitLongValues"](https://exiftool.org/ExifTool.html#LimitLongValues) option”
[[
[ "LimitLongValues"
    When extracting some values that may be very long, the PrintConv values are length-limited and the value is truncated with an elipsis ("[...]") if it exceeds a specified length.
    This option specifies the length limit for these tags.
    A setting of 4 or less disables the limit (because the elipsis string is longer than this). ]
]]
    Misleading as it does not affect tags generally.
    This may give people a hunch that the change may break things: if they haven't investigated thoroughly.

    Also, ["elipsis"](https://en.wiktionary.org/wiki/elipsis) is not preferred form in English: ["ellipsis"](https://en.wiktionary.org/wiki/ellipsis).

**Comment by StarGeekSpaceNerd** [comment]
>   "..." longer than 4..?

`[...]` is 5 characters. So yes, 4 or less.

Though technically, it can be 3 by using the actual ellipsis character
`[…]`
though that might someone's script that checks for the 5 character version.

**Comment by boardhead** [comment]
Thanks for explaining.  I'm happy with this:

When extracting values for some specific tags (usually Unknown tags), the
PrintConv values are length-limited and the value is truncated with an
ellipsis ("[...]") if it exceeds a specified length.  This option specifies
the length limit for these tags.  A setting of 4 or less disables the limit
(because the ellipsis string is longer than this).  Default is 60.

@StarGeek: We have enough troubles with special characters in the output  :P

- Phil

**Comment by MasterInQuestion** [comment]
For embedding in HTML, you may refer to this post:
    [https://github<i>.</i>com/madler/zlib/issues/910](https://github.com/madler/zlib/issues/910)

    See also:
    ASCII punctuation preference
    [https://github<i>.</i>com/MasterInQuestion/talk/discussions/5](https://github.com/MasterInQuestion/talk/discussions/5)

**Comment by boardhead** [comment]
I'm going to pretend I didn't see that. :)

**Comment by MasterInQuestion** [comment]
Of course, at will. :)
    But I noticed significant amount problems are caused by such alike.

**Comment by boardhead** [comment]
I've attempted to make the documentation and release notes more clear about this.
