### ISSUE TITLE
Error accessing MIE files in version 12.74

### ISSUE THREAD

**Issue by ghotz** [exiftool/exiftool#242]
There seems to be a problem accessing MIE files in version 12.74, Exfitool throws the following error: `Undefined subroutine &File::RandomAccess called at Image/ExifTool/MIE.pm line 1588.`

Reverting back to version 17.73 works as expected, following are a couple of example ran switching between versions.

![image](https://github.com/exiftool/exiftool/assets/7333997/e6714496-71e9-4a0a-a208-ad36693c6c6f)

![image](https://github.com/exiftool/exiftool/assets/7333997/b0237d83-63a5-4005-80c5-7a63ac094161)

- OS Version: Microsoft Windows 11 Pro (10.0.22631 N/A Build 22631)

Please note I also tested it in a regular Windows command line prompt, to rule out anything that could have been related to PowerShell, and got the same errors.

**Comment by boardhead** [comment]
Thanks for this report!  This is due to changes made to satisfy https://github.com/exiftool/exiftool/pull/159

(bugs like this are why I resist making sweeping changes if possible)

This will be fixed in 12.75.

- Phil

**Comment by boardhead** [comment]
P.S.  Odd that it works with my version of Perl (5.18.4).  :/

- Phil

**Comment by boardhead** [comment]
This should be fixed in 12.75
