### ISSUE TITLE
JSON detected as wrong type if array containing object is MIMEtype

### ISSUE THREAD

**Issue by tvt-joni** [exiftool/exiftool#243]
file content: `[{"MIMEType": "image/x-png"}] `

From little what i've tested: if theres a seperate array with the mimetype in the beginning of file, it gives filetype as whatever is written in it.

```
ExifTool Version Number         : 12.30
File Name                       : testfile
Directory                       : .
File Size                       : 30 bytes
File Modification Date/Time     : 2024:02:26 12:38:33+02:00
File Access Date/Time           : 2024:02:26 12:38:50+02:00
File Inode Change Date/Time     : 2024:02:26 12:38:33+02:00
File Permissions                : -rw-r--r--
File Type                       : JSON
File Type Extension             : json
MIME Type                       : image/x-png
```

Don't know if theres any harm in this but I figured better safe than sorry

**Comment by StarGeekSpaceNerd** [comment]
This is [FAQ #3](https://exiftool.org/faq.html#Q3).  If you include the [`-a` (`-duplicates`) option](https://exiftool.org/exiftool_pod.html#a---a--duplicates---duplicates), you will see that there are actually two `MIMEType` entries, one which applies to the file, and one which is the data inside the file.  Adding the [`-G` (`-groupNames`) option](https://exiftool.org/exiftool_pod.html#G-NUM-:NUM...--groupNames) and you will see the groups they belong two

```
[File]          MIMEType                        : application/json
[JSON]          MIMEType                        : image/jpeg
```
