### ISSUE TITLE
Microsoft Xtra tags - expand writable tags

### ISSUE THREAD

**Issue by DoubleJCream** [exiftool/exiftool#248]
Hi Phil

I was wondering if it would be an easy job to add some more of the Microsoft Xtra tags in the MP4 metadata, specifically in the moov -> udta box / atom?
I see you got this working in issue #70 , for some tags, such as;
-Microsoft:Subtitle
-Microsoft:SharedUserRating
-Microsoft:Category
etc.

I was specifically looking if it would be possible to add the tag;
-Microsoft:Description

This is the tag that is displayed in the Details tab of the file under Description - Comments

If you want an example file let me know and i can send it.
Thanks again!

**Comment by StarGeekSpaceNerd** [comment]
I never had any file to test `Microsoft:Description` with.  If you have a sample or program that writes it, it would be helpful for my further tests.

But the Properties->Details tab->Comments will read the `ItemList:Comment` tag.  This is the tag that Windows 10 will write when you edit the Comments in the Properties window.

You can see my previous tests for the Windows Properties in [this exiftool forum's post](https://exiftool.org/forum/index.php?topic=6591.0).

**Comment by DoubleJCream** [comment]
I will send it when i get home;
I really have not found anything that writes to this atom since it never seems to have been really documented by Microsoft.

In my tests the  Properties->Details tab->Comments seems to check a hierarchy if there is a  ItemList:Comment (which i think is just the -QuickTime:Comment tag)  it will take priority over Microsoft:Description but if there is no ItemList:Comment tag then it will display the Microsoft:Description.

**Comment by boardhead** [comment]
A sample is required.  There are 3 (!!) different Microsoft Xtra Description tags, and I need to know which one to write.

- Phil

**Comment by StarGeekSpaceNerd** [comment]
There isn't a hierarchy as far as I can tell. Windows appears to take the value of whatever was the last read tag. Or maybe it was first read, I can't remember.  It drove me crazy when I was doing the testing in my link above, as sometimes one tag would seem to take precedent, then a different one would.  I finally used exiftool's [`-v` (`-verbose`) option](https://exiftool.org/exiftool_pod.html#v-NUM--verbose) to see that it was the order the tags appeared in the file, not one specific tag over another.

>(which i think is just the -QuickTime:Comment tag)

There are three main subgroups for the Quicktime tags, `ItemList`, `Keys`, and `UserData`.  The `Comment` tag can appear in any of these subgroups, i.e. `ItemList:Comment`, `Keys:Comment`, or `UserData:Comment`. Exiftool will default to writing `ItemList` tags if the tag can exist there.

I just double checked all three tags and Windows will only read `ItemList:Comment`.

One problem with testing is that if there is too much metadata set, then Windows will choke and have problems displaying any data under Properties.  My test file has over 150 different tags set in the Quicktime and Microsoft groups for video files (my image test file has over 1,400 tags for testing).

To add to the fun, I believe that Apple programs are more likely to read the `Keys` tags, though wywh on the exiftool forums is the Apple expert.

**Comment by DoubleJCream** [comment]
Here's the file;
[https://mega.nz/file/5csBwYzL#IElAoGBFRYAg8FEyKs2RDnGEq9VLwf2aBI1K2YVC8g8](url)

Ideally it would be great to be able to edit or delete the tag - i'm curious if you delete the last/only tag will it also delete that xtra atom? Certainly it would be good if no other tags are in the box/atom to remove it after the last tag is gone.
The only app i have used that seems to be able to work with them properly is called 3delite Video Manager
[https://www.3delite.hu/Object%20Pascal%20Developer%20Resources/VideoManager.html](url)

I also tried taking another video and trimming it to make it smaller to send to you but every online app or installed app that i had, including handbrake and LosslessCut seems to remove that Xtra atom. While that may be one goal I wouldn't want to have some important information in there that is then removed by these apps, since they don't seem to preserve that tag (even if LosslessCut says it will preserve all metadata!)

Let me know if this one is ok - I didn't add any QuickTime Comment to confuse the issue.

-Stargeek: You are probably correct - I'll take your experience over my guesses anyday! it was my jump-to-conclusion about how Microsoft was handling the tags but your explanation sounds more logical.

In my naivety i had just finished some powershell scripts for mkv metadata and i was thinking mp4 would be so much more simple since i thought it was much more standardized. Then i found out about Apple's and Microsoft QuickTime and xtra tags and the headaches started! Thanks you guys for beating some type of order in this metadata mayhem!

let me know what else i can do.

**Comment by DoubleJCream** [comment]
Thanks Phil!
made a small donation.

**Comment by StarGeekSpaceNerd** [comment]
Your file gives further verification on Windows most likely using the last tag it finds to fill a property.  Looking at the file with exiftool's [`-v3` (`-verbose3`) option](https://exiftool.org/exiftool_pod.html#v-NUM--verbose), the Microsoft tag is the very last item in the file.   And thanks for the sample.

**Comment by DoubleJCream** [comment]
Your very welcome StarGeek, thank you for all your help (again)!

**Comment by boardhead** [comment]
> Thanks Phil!
> made a small donation.

I got it, thanks!

- Phil

**Comment by DoubleJCream** [comment]
Hi Phil

I've been testing out the fuctionality for writing to the Microsoft Atom, its working most times however on a few i am getting;

> D:\MediaBinaries\exiftool\exiftool.exe : Error: '0xc8b6efe7' atom is too large for rewriting (208 MB)

I tried the switch '-api largefilesupport=1' that i noticed i need for some large files but it doesn't change the outcome, it looks like its specific to that -Microsoft:Description command
an easy fix?

**Comment by boardhead** [comment]
You're getting the error with 12.81?  Can you upload the video somewhere so I can test this?  Email the link to me if you don't want to post it here (philharvey66 at gmail.com)

- Phil

**Comment by DoubleJCream** [comment]
Here you go;
[https://mega.nz/file/sJFznL4L#vvAxjFFlAbS_MRG6UW4gEZewdDW05L4VL35zbG8qscQ](url)

its the smallest one that shows the error;
thanks

**Comment by boardhead** [comment]
I got the sample.  There are two very large unknown atoms with binary ID's near the start of this file.  One is 218449040 bytes, and the second is 122759516 bytes.  They seem well-formed since the sizes are good even though the tag ID's are stupid.  I don't recognize the data they contain -- do you have any idea what this is?

ExifTool won't currently rewrite files with unknown atoms this large because in general this is indicative of a corrupted file, although in this case it seems to not be true.  And if ExifTool attempted to rewrite this file, it would likely run out of memory trying to load these very large atoms into RAM.

I'm not sure of the best course of action here.  It depends on whether or not this unknown data is useful to you somehow.

- Phil

**Comment by DoubleJCream** [comment]
I just loaded that file up in Video Manager (3delite) and it just shows a small atom (cnam) of 43 bytes so i don't know. The file is a video i downloaded off the internet so who knows what processing it has been through.
I think you can close the case since i am only seeing this on a few files and that Video Manager seems to be able to edit/delete them but it doesn't have command line like Exiftool.
I'm afraid i don't know enough about metadata structure to open it up and tell what those atoms can be - I didn't even know about those stupid things till a few weeks ago - I was hoping mp4 metadata was more simple.
As i said i think you can close this - if it ever becomes an issue maybe add another switch to force delete any atoms?

**Comment by boardhead** [comment]
OK.  Good plan.
