### ISSUE TITLE
Unable to update MAKE tag using exiftool 12.76

### ISSUE THREAD

**Issue by JeffGoldner** [exiftool/exiftool#249]
I have been updating missing or incorrect MAKE and MODEL tags for scanned images. With my latest scans, I can update MODEL but MAKE throws an error.

Details:
I usually scan with Silverfast. Last week, I used their latest version (9.2.3) on MacOS to scan a roll of negatives. I then tried to update the MAKE and MODEL fields using exiftool 12.65. MODEL can be changed, but MAKE throws this error:

exiftool -make="Nikon" -verbose 20240328-20240321-01.tif 
======== 20240328-20240321-01.tif
Rewriting 20240328-20240321-01.tif...
  Editing tags in: ExifIFD IFD0 Keys MIE-Camera MakerNotes PNG TIFF UserData XMP 
  FileType = TIFF
  FileTypeExtension = TIF
  MIMEType = image/tiff
  Rewriting IFD0
  Rewriting SubIFD
  Rewriting XMP
  Rewriting IPTC
  Rewriting ExifIFD
  Error = [minor] Maker notes could not be parsed
  Rewriting ICC_Profile
  Copying 3546 image data blocks
Error: [minor] Maker notes could not be parsed - 20240328-20240321-01.tif
    0 image files updated
    1 files weren't updated due to errors

I then tried this on scans from last June, when I used Silverfast 9.1.8. No problems encountered, I could change both tags.

Since these files are on a NAS and accessible from my PC as well, I used Explorer on Windows 11 to look at Properties for the files I could not change using exiftool. From there, I could change those fields without issue.

**Comment by JeffGoldner** [comment]
Found the -m option which lets the change take place.

**Comment by StarGeekSpaceNerd** [comment]
Can you provide a sample file that Phil can look at and decide if he needs to change something on the exiftool side or if a issue needs to be filed with Silverfast.

**Comment by boardhead** [comment]
I don't need a sample for this problem.  There are a number of makernote types that ExifTool doesn't understand.  This warning is due to a small chance that ExifTool could corrupt unknown maker notes when rewriting, but honestly I don't recall ever seeing any cases where this happens.
