### ISSUE TITLE
New Samsung GCamera XMP tags

### ISSUE THREAD

**Issue by doodspav** [exiftool/exiftool#254]
The following tags are used by Samsung's Motion Photo implementation in the App1 XMP:
- `GCamera:MotionPhoto`
- `GCamera:MotionPhotoVersion`
- `GCamera:MotionPhotoPresentationTimestampUs`

The extracted full [App1 segment](https://github.com/exiftool/exiftool/files/15017414/app1.xml.txt) from an image taken on a Samsung Galaxy Z Fold 5 is attached (with a `.txt` extension because GitHub wouldn't let me upload a `.xml` file).

Can these tags please be added to `exiftool`?
Also if it's possible to add the `Container` as well, but not sure how that would work.

**Comment by doodspav** [comment]
```pl
%Image::ExifTool::UserDefined = (

    # XMP tags for Samsung's Motion Photo
    'Image::ExifTool::XMP::GCamera' => {
        MotionPhoto =>                        { Writable => 'integer' },
        MotionPhotoVersion =>                 { Writable => 'integer' },
        MotionPhotoPresentationTimestampUs => { Writable => 'integer' },
    },

);

1;  # end
```

This is what I have right now in my config file, and it works.

**Comment by StarGeekSpaceNerd** [comment]
Any idea how it comes up with the `MotionPhotoPresentationTimestampUs`? The value of 2590122 isn't a date or time, nor is it a Unix time stamp.

The three you list should be easy enough to make a config file (and… you've gone and done it while I'm typing :D  )

The `XMP-Container:Directory` is a bit more complex as it is a structured tag and a list type tag.

**Comment by doodspav** [comment]
The `MotionPhotoPresentationTimestampUs` seems to be the offset of the key frame image from the start of the video.

**Comment by doodspav** [comment]
If `XMP-Container::Directory` is a structured tag and a list type tag, what type are the other tags I've mentioned so far? Also I read somewhere that if you write a list type tag twice, it writes the value twice rather than replacing the old one. So how would I replace the old value?

**Comment by boardhead** [comment]
Thanks.  I'll add these to the next release.  The "Us" in the timestamp tag name is likely microseconds. 

If you want to replace the old value of a list tag, just write it once.  If you write it twice, you replace the old value with two new values.

I had already generated the necessary code for the Container tags, but I won't impement it due to a conflict with other Google tags.  See here:

https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/XMP2.pl#L2108

- Phil

**Comment by doodspav** [comment]
So if I put this into my config file:

```pl
    'Image::ExifTool::XMP::Container' => {
        %xmpTableDefaults,
        GROUPS => { 1 => 'XMP-Container', 2 => 'Image' },
        NAMESPACE => 'Container',
        NOTES => 'Google Container namespace.',
        Directory => {
            Name => 'ContainerDirectory',
            FlatName => 'Directory',
            List => 'Seq',
            Struct => {
                STRUCT_NAME => 'Directory',
                Item => {
                    Namespace => 'Container',
                    Struct => {
                        STRUCT_NAME => 'Item',
                        NAMESPACE => { Item => 'http://ns.google.com/photos/1.0/container/item/'},
                        Mime     => { },
                        Semantic => { },
                        Length   => { Writable => 'integer' },
                        Label    => { },
                        Padding  => { Writable => 'integer' },
                        URI      => { },
                    },
                },
            },
        },
    },
```

(I'm assuming it's correct)
How do I set values for this via the command line?

**Comment by doodspav** [comment]
Wow yeah that does look complicated. I tried the config file, and you're right that it doesn't work out of the gate, but I'm stumped as to what to do to fix it / how to resolve the conflict.

For now I'll just skip the container when making my motion photos, and if Phil manages to come up with a solution, I'll incorporate that.

**Comment by boardhead** [comment]
I think the thing to do here is to just use a different namespace prefix instead of "Container".  This config file should work, and uses "GContainer" instead, so the ExifTool family 1 group name is XMP-GContainer, and this is the group name that must be used when writing.

`%Image::ExifTool::UserDefined = (
    'Image::ExifTool::XMP::Main' => {
        GContainer => {
            Name => 'GContainer',
            SubDirectory => { TagTable => 'Image::ExifTool::XMP::GContainer' },
        },
    },
);

%Image::ExifTool::XMP::GContainer = (
    %xmpTableDefaults,
    GROUPS => { 1 => 'XMP-GContainer', 2 => 'Image' },
    NAMESPACE => { GContainer => 'http://ns.google.com/photos/1.0/container/' },
    NOTES => 'Google Container namespace.',
    WRITABLE => 'string',
    Test => { },
    Directory => {
        Name => 'ContainerDirectory',
        FlatName => 'Directory',
        List => 'Seq',
        Struct => {
            STRUCT_NAME => 'Directory',
            Item => {
                Namespace => 'GContainer',
                Struct => {
                    STRUCT_NAME => 'Item',
                    NAMESPACE => { Item => 'http://ns.google.com/photos/1.0/container/item/'},
                    Mime     => { },
                    Semantic => { },
                    Length   => { Writable => 'integer' },
                    Label    => { },
                    Padding  => { Writable => 'integer' },
                    URI      => { },
                },
            },
        },
    },
);

1;  #end
`

- Phil

**Comment by StarGeekSpaceNerd** [comment]
Will this be included in upcoming releases, either as a separate config file or built-in? I'm trying to decide if this should be added to my notes.

**Comment by boardhead** [comment]
I hadn't decided, but I think it makes sense to implement this in ExifTool 12.87, so I'll go ahead and do that.

- Phil

**Comment by boardhead** [comment]
I just notice that the "Item" prefix also conflicts, so I'll make this "GItem".

- Phil
