### ISSUE TITLE
[Suggestion] New way of representing Palette in human-readable format

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#256]
E.g. "`#F00 #010203 ...`"

    Related:
    https://trac.ffmpeg.org/ticket/10919
    https://trac.ffmpeg.org/ticket/10918

    Does similar command make sense..?
    exiftool -U -ee3 -g3:5:2 -api "RequestAll=0" -api "ByteUnit=Binary" -api "LargeFileSupport" "https://upload.wikimedia.org/wikipedia/en/f/ff/NES_palette_sample_image.png"
    ^
    curl -L "https://upload.wikimedia.org/wikipedia/en/f/ff/NES_palette_sample_image.png" | exiftool -U -ee3 -g3:5:2 -api "RequestAll=0" -api "ByteUnit=Binary" -api "LargeFileSupport" -
    Probably needs better display for FileSize.

**Comment by StarGeekSpaceNerd** [comment]
Maybe [this thread on the exiftool forums](https://exiftool.org/forum/index.php?topic=15860.0), started by user blue-j, will extract PNG palette in a form you can use?

**Comment by MasterInQuestion** [comment]
Thanks for linking.
    Though my posts are mostly for theoretical enhancement, than looking for workaround.

    Clarification:
    The suggestion is more focused on printing.

**Comment by boardhead** [comment]
This is an interesting _theoretical_ suggestion, but I would rather not make changes like this unless there is a _real_ demand because it may break things for users already relying on the way this tag is decoded.

But I'll patch ExifTool 12.87 to avoid reporting FileSize for a pipe.

- Phil

**Comment by MasterInQuestion** [comment]
"(Binary data 768 bytes, use -b option to extract)"
<^>    The interpreted display is regardless susceptible to change.
    And this one would be mostly just verbatim copied.

    Perhaps displaying the parsed file size makes more sense.
