### ISSUE TITLE
Firmware Versions, Canon 7D (or - strangeness recovering certain data)

### ISSUE THREAD

**Issue by phut** [exiftool/exiftool#257]
Processing old photos from an obsolete canon 7D in exiftool gives warnings:

`Warning: Unrecognized CameraInfo7D firmware version`

 because:

`CanonFirmwareVersion            : Firmware Version 2.0.3`

Latest version from Canon Website is `2.0.6`. 

From the available data I have, all photos having 1.x.x firmware are not flagged. 
Firmware 2.x.x adds some useful functionality over 1.x.x

I don't know how many other intermediate 2.x.x minor version numbers were previously available.

**Comment by phut** [comment]
With further testing*, I am no longer sure the warning and tag CanonFirmwareVersion are linked.

* I used exiftool to copy a version number string from a "working" file to one that was producing warnings, and used exiftool again to make sure that it had applied correctly. The file still produces the same warning when scanned with exiftool.

**Comment by boardhead** [comment]
This warning isn't reported if ExifTool returns something useful unless the -v option is used.

If you could upload a sample file with firmware 2.0.6 I can add support for this version.

- Phil
