### ISSUE TITLE
[Enhancement] TIFF metadata stripping

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#258]
When doing ["-&#x2A;="](https://exiftool.org/exiftool_pod.html#Tag-operations) for TIFF, would it be rational to automatically attach "-CommonIFD0="?
    (I did so without observing any unwanted result)

    In addition, the following tags may be also removed:
    (yet needs manual specifying; maybe adding to [CommonIFD0](https://exiftool.org/TagNames/Shortcuts.html)?)
    |&#x2A;| Orientation
    |&#x2A;| ResolutionUnit
    |&#x2A;| XResolution
    |&#x2A;| YResolution

    Related: https://exiftool.org/faq.html#Q7

**Comment by MasterInQuestion** [comment]
When [Orientation](https://exiftool.org/TagNames/EXIF.html) = "Horizontal": stripping it should be alright.

**Comment by boardhead** [comment]
Adding -commonIFD0= would be an incomplete list of tags to delete.  Also, the tags to write/delete are determined before the file type is known, so adding more tags for a specific file type would be problematic.

I think it is best/safest to leave it up to the user to decide if/what they want to delete from IFD0 of a TIFF.

- Phil

**Comment by MasterInQuestion** [comment]
The CommonIFD0 name already indicated it shall overkill and possibly wreak havoc.
    Whatsoever, if "-*=" already included CommonIFD0: most wouldn't even bother knowing it.

    Many use ExifTool typically for file clean-up.
    And they just wanted to remove everything non-essential, without bother.

**Comment by boardhead** [comment]
I don't see any safe way of removing everything non-essential from a TIFF file.

**Comment by MasterInQuestion** [comment]
"-*=" probably wouldn't be expected as safe way whatsoever...
