### ISSUE TITLE
Add Character Count too? ("Document" type)

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#259]
[[
&gt; exiftool -U -ee3 -g3:5:2 -api "RequestAll=0" -api "ByteUnit=Binary" -api "LargeFileSupport" "!0.txt"
---- ExifTool ----
ExifTool Version Number         : 12.83
---- System:Other ----
File Name                       : !0.txt
Directory                       : .
File Size                       : 1495 bytes
File Permissions                : -rw-rw----
---- System:Time ----
File Modification Date/Time     : 1970:01:01 00:00:00+00:00
File Access Date/Time           : 1970:01:01 00:00:00+00:00
File Inode Change Date/Time     : 1970:01:01 00:00:00+00:00
---- TXT:Other ----
File Type                       : TXT
File Type Extension             : txt
MIME Type                       : text/plain
MIME Encoding                   : utf-8
---- TXT:Document ----
Byte Order Mark                 : No
Newlines                        : Windows CRLF
Line Count                      : 66
Word Count                      : 178
]]

**Comment by boardhead** [comment]
This is given by the FileSize.

**Comment by MasterInQuestion** [comment]
Somewhat derivable.
    But what about UTF-8? (1 ~ 4 Bytes per character)

**Comment by MasterInQuestion** [comment]
Specifically, this is likely of interest only to UTF-8.
    Consider add only for UTF-8?
    Perl-IO shall handle it.
    https://perldoc.perl.org/perlunifaq#What-is-the-difference-between-:encoding-and-:utf8
    https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Text.pm
