### ISSUE TITLE
Writing of MPG files is not yet supported

### ISSUE THREAD

**Issue by buraequete** [exiftool/exiftool#26]
I am using the tool to shift the create timestamp metadata of some .MPG files, but getting the following error;

```
======== MOV05461.MPG
Rewriting MOV05461.MPG...
  Error = Writing of MPG files is not yet supported
Error: Writing of MPG files is not yet supported - MOV05461.MPG
```

The command I am using is very simple;

```
./exiftool.exe "-AllDates+=0:0:445 13:06:00" -verbose *.MPG
```

Will the write feature be added soon? What other options do I have to achieve what I want?
Thanks

**Comment by boardhead** [comment]
MPG files are not very common any more, and don't contain much metadata, so there isn't much incentive to add the write ability for these files.

**Comment by buraequete** [comment]
> MPG files are not very common any more, and don't contain much metadata, so there isn't much incentive to add the write ability for these files.

I see, but I have hundreds of old .MPG files with shifted create date time metadata, can you suggest another tool that can help me with correcting them all, similar to exiftool?

**Comment by boardhead** [comment]
Sorry, I don't know much about the abilities of other tools.
