### ISSUE TITLE
"PNG-PrimaryChromaticities" "PNG-CICodePoints" alike not handled

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#263]
These tags mostly have no use.
    While ["-&#x2A;="](https://exiftool.org/exiftool_pod.html#TAG---VALUE) doesn't handle which.

    See also: https://trac.ffmpeg.org/ticket/11002

**Comment by boardhead** [comment]
Yes.  These tags are not deletable by ExifTool.

- Phil

**Comment by MasterInQuestion** [comment]
Why?
    And this somehow means ExifTool may not adequately clean-up PNG created by FFmpeg.

**Comment by boardhead** [comment]
I don't know if these tags should be considered metadata.  They look more like data related to the image rendering/display, and ExifTool shouldn't be deleting this type of information by default.

- Phil

**Comment by MasterInQuestion** [comment]
Comparable to ICC profiles.

**Comment by boardhead** [comment]
ExifTool shouldn't be deleting those either, but it is too late to change this.

**Comment by MasterInQuestion** [comment]
Well, what about such use case..?
    [ https://github.com/exiftool/exiftool/issues/258#issuecomment-2159609243](https://github.com/exiftool/exiftool/issues/258#issuecomment-2159609243)

    The existence of such post-rendering isn't much justifiable either:
    https://trac.ffmpeg.org/ticket/11002#comment:11
