### ISSUE TITLE
Update AFAreaMode for Canon

### ISSUE THREAD

**Issue by Wernfried** [exiftool/exiftool#268]
Hi Phil

I am now a proud owner of a new Canon EOS R7 camera. 
Looks like the [Canon AFInfo2 Tags](https://exiftool.org/TagNames/Canon.html#AFInfo2) are not yet up to date.

From [EOS R7 manual: AF Area](https://cam.start.canon/en/C005/manual/html/UG-05_AF-Drive_0070.html#AF-Drive_0070_1) some edit would be needed:

```
exiftool -AFAreaMode -AFAreaMode# *.jpg
======== IMGT0306.JPG
AF Area Mode                    : Spot AF
AF Area Mode                    : 9
-> OK

======== IMGT0307.JPG
AF Area Mode                    : Flexizone Single
AF Area Mode                    : 13
-> Named as "1-point AF" but "Flexizone Single" might be OK

======== IMGT0308.JPG
AF Area Mode                    : AF Point Expansion (4 point)
AF Area Mode                    : 8
-> Named as "Expand AF area" - actually 5 points

======== IMGT0309.JPG
AF Area Mode                    : AF Point Expansion (8 point)
AF Area Mode                    : 10
-> Named as "Expand AF area: Around" - actually 9 points

======== IMGT0310.JPG
AF Area Mode                    : Unknown (19)
AF Area Mode                    : 19
-> Named as "Flexible Zone AF 1"

======== IMGT0311.JPG
AF Area Mode                    : Unknown (20)
AF Area Mode                    : 20
-> Named as "Flexible Zone AF 2"

======== IMGT0312.JPG
AF Area Mode                    : Unknown (21)
AF Area Mode                    : 21
-> Named as "Flexible Zone AF 3"

======== IMGT0313.JPG
AF Area Mode                    : Unknown (22)
AF Area Mode                    : 22
-> Named as "Whole area AF"
```

I assume AF Area Mode 8,10 and 13 depends on the camera model and it would be difficult to cover every single model. However, 19, 20, 21, 22 should be worth being added to exiftool.

Kind Regards
Wernfried

**Comment by boardhead** [comment]
Thanks!  I'll add 19, 20, 21 and 22.

The "AF Point Expansion (4 point)" means 4 points are added around the central point, for a total of 5, which I think is what you are telling me.  The same for 8 -> 9 points.

- Phil
