### ISSUE TITLE
OOXML File Type Resolution

### ISSUE THREAD

**Issue by SheetJSDev** [exiftool/exiftool#27]
Context: https://github.com/SheetJS/js-xlsx/issues/1637

https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/ZIP.pm#L459

```perl
            if (not $status and $buff =~ /ContentType\s*=\s*(['"])([^"']+)\.main(\+xml)?\1/) {
```

This matches the first instance, which leads to false positives in files that SheetJS generates since we write the Default block first:

```xml
  <Default Extension="xml" ContentType="application/xml"/>
  <Default Extension="bin" ContentType="application/vnd.ms-excel.sheet.binary.macroEnabled.main"/>
```

The "right" way to do it is to look at the `_rels/.rels` file to determine the main xml.  A mostly correct and simpler approach would scan specifically for `xl/workbook.xml` / `word/document.xml` / `ppt/presentation.xml` and determine type based on the ContentType of that specific entry

**Comment by boardhead** [comment]
Thanks for this suggestion, however I don't have enough information to implement your .rels suggestion.  I would need to know how to select the main entry from all of the relationships, and have a list of mime types for each possible type of relationship.

Instead, would it be sufficient to ignore the "Default" entries in [Content_Types].xml?

Using the MIME types from [Content_Types].xml has the advantage that it can distinguish between DOCX and DOCM for example.

**Comment by boardhead** [comment]
Do you have a sample file that you could share?

**Comment by boardhead** [comment]
I wasn't liking your second suggestion of looking for a specific part name, but I'm happy doing this if I add some fallback conditions.  I think something like this may cover things nicely:

`                    # first look for the main document with the expected name
                if ($buff =~ m{\sPartName\s*=\s*['"](?:/ppt/presentation.xml|/word/document.xml|/xl/workbook.xml)['"][^>]*\sContentType\s*=\s*(['"])([^"']+)\.main(\+xml)?\1} or
                    # then look for the main part
                    $buff =~ /<Override[^>]*\sPartName[^<]+\sContentType\s*=\s*(['"])([^"']+)\.main(\+xml)?\1/ or
                    # finally, check the defaults for anything with a ".main"
                    $buff =~ /ContentType\s*=\s*(['"])([^"']+)\.main(\+xml)?\1/)
                {
                    $mime = $2;
                }
`

**Comment by SheetJSDev** [comment]
We have a [neat export demo](https://sheetjs.com/demos/table).  The attached file [SheetJSTableExport.xlsx](https://github.com/exiftool/exiftool/files/3691523/SheetJSTableExport.xlsx) was generated by clicking "Export to XLSX!"

```
$ exiftool SheetJSTableExport.xlsx | grep Type
File Type                       : XLSB
File Type Extension             : xlsb
MIME Type                       : application/vnd.ms-excel.sheet.binary.macroEnabled
```

The relevant tags can be found by grepping within the `[Content_Types].xml` file:

```
$ unzip -p SheetJSTableExport.xlsx \\\[Content_Types\\\].xml | xmllint --format - | grep \.main
```

... and the result looks like

```xml
  <Default Extension="bin" ContentType="application/vnd.ms-excel.sheet.binary.macroEnabled.main"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
```

What makes this XLSX is the `/xl/workbook.xml` part.  For a true XLSB (click "Export to XLSB!" in the demo), the root document is `/xl/workbook.bin`

**Comment by boardhead** [comment]
Thanks for the samples.  The new algorithm properly identifies these files.  This patch will be in place for ExifTool 11.70
