### ISSUE TITLE
Wrong value for DateTimeOriginal

### ISSUE THREAD

**Issue by bep** [exiftool/exiftool#270]
![geodegrees_as_string](https://github.com/exiftool/exiftool/assets/394382/9c5d7777-f12e-429b-8209-38ee4318ae4b)

```
exiftool -ver                                                                                     
12.76
```

Ref. attached image.

* Exiftool reports `DateTimeOriginal` to be  `2014:04:26 19:09:19`
* The `DateTimeOriginal` tag reports the value to be 19 bytes.
* One could argue that this file is malformed, but I don't think it's correct to make up values, so I would say that the correct would be to report this as `2014:04:26 19:09:1`

**Comment by StarGeekSpaceNerd** [comment]
As far as I can tell, exiftool isn't making up numbers. The last two characters for the `DateTimeOriginal` are `0x31` `0x39`, e.g. `1 9`
```
  | | 2)  DateTimeOriginal = 2014:04:26 19:09:19
  | |     - Tag 0x9003 (19 bytes, string[19]):
  | |         0130: 32 30 31 34 3a 30 34 3a 32 36 20 31 39 3a 30 39 [2014:04:26 19:09]
  | |         0140: 3a 31 39                                        [:19]
  | | 3)  ApertureValue = 2 (2048/1024)
```
The tag is missing the trailing null, but the value of `19:09:19` is correct.

That file has been very badly written. Using 
`exiftool -g1 -a -s -warning -validate 346590768-9c5d7777-f12e-429b-8209-38ee4318ae4b.jpg`
shows 45 warnings.  15 of those are `Missing required` EXIF tags, but the others are problematic.

**Comment by bep** [comment]
You are right, sorry for the noise.
