### ISSUE TITLE
latest master tests failing commit c3212b20e78e7a882bae5c61df84a0b2e731ab75

### ISSUE THREAD

**Issue by woss** [exiftool/exiftool#272]
Hi, 

I caught that tests are failing on this commit https://github.com/exiftool/exiftool/commit/c3212b20e78e7a882bae5c61df84a0b2e731ab75 v.12.90

<img width="813" alt="image" src="https://github.com/user-attachments/assets/aeedbcef-fe90-4c9e-893e-09bc3a5d8042">
<img width="652" alt="image" src="https://github.com/user-attachments/assets/29df564e-01c8-4aaf-ae2a-e9e9060cd5b4">

I've created the fork and added simple test action which fails, you can see it here https://github.com/woss/fork-exiftool/actions/runs/10079578158

If you are interested I can make a PR to include it to exiftool

**Comment by boardhead** [comment]
Thanks.  I don't know how I missed this in the release.  I'll have to check my release script.

- Phil

**Comment by boardhead** [comment]
Note that the release is perfectly good -- I just forgot to update these two test files.

**Comment by boardhead** [comment]
I've gone ahead and released 12.91 with the updated test files.

**Comment by woss** [comment]
Why not add the github actions? ExifTool is an open source project, you don't pay anything for them.
