### ISSUE TITLE
Shebang lines missing "-S" flag

### ISSUE THREAD

**Issue by cheneyni-451** [exiftool/exiftool#273]
exiftool fails to launch since version 12.90.

Caused by the shebang changes in c3212b20e78e7a882bae5c61df84a0b2e731ab75.

![Screenshot_2024-07-24-05-53-20](https://github.com/user-attachments/assets/0e803e5b-35e0-43e5-bdb9-261f70fefff0)

**Comment by boardhead** [comment]
Fixed in 12.92
