### ISSUE TITLE
Undefined subroutine Image::ExifTool::IsPC on every file

### ISSUE THREAD

**Issue by cafreo** [exiftool/exiftool#277]
I get the following error every time I want to use exiftool on a file:
`Undefined subroutine Image::ExifTool::IsPC called at /usr/share/perl5/site_perl/Image/ExifTool.pm line 5044`

Reinstalling exiftool or deleting the /usr/share/perl5 folder did not help, only downgrading to 12.93 solves this problem. Every newer version does not work.

Looking at the Exiftool.pm file at line 5044 it says

sub AUTOLOAD
{
    return DoAutoLoad($AUTOLOAD, @_);
}

If you need more information for troubleshooting, please let me know.

**Comment by StarGeekSpaceNerd** [comment]
Phil is currently AFK and won't be back for a couple of weeks. It will be a bit before he can look at this.

What OS are you using (Windows/Mac/Linux)? Can you provide an exact example command? Does this still happen with the latest version, 12.96?

This hasn't popped up at all on the exiftool forums.

Something else is strange. The line `sub AUTOLOAD` appears at line 5316 in exiftool version 12.88-12.93 and line 5365 in versions 12.94-12.96. Searching further back, the only version I have where it is at line 5044 is version 12.72, though it might also be in 12.73, I don't have a copy of that version. It's located at line 5047 in 12.74.

I suspect you have an older version of exiftool hiding on your system somewhere. Try searching your system for any other copies of `Exiftool.pm`.

**Comment by cafreo** [comment]
Thanks for the quick answer.

You were right. Running `exiftool -ver` indicated, that my library version is 12.73 but the program version is 12.96. I also assume, that this was caused by an older installation via source, probably a few months back. Now being installed via pacman the new version was preferring the old files somehow, which caused this error.

Thank you for the help, this solved the problem.

**Comment by stefanrueger** [comment]
I still see this problem under archliniux:
```
$ exiftool some.file
Undefined subroutine Image::ExifTool::IsPC called at /usr/share/perl5/site_perl/Image/ExifTool.pm line 5057

$ exiftool -ver
13.03 [Warning: Library version is 12.76]
```
What can I do?

**Comment by stefanrueger** [comment]
OK, those able to read have a clear advantage. :smile: 

> Try searching your system for any other copies of `Exiftool.pm`.

Indeed! There was an older version installed in `/usr/share/perl5/site_perl/` whereas the current version resides in `/usr/share/perl5/vendor_perl/Image/ExifTool.pm`. Deleting the older version helped:
```
# rm -rf /usr/share/perl5/site_perl/Image
```
I guess, but don;t know, that these were competing installations from cpan and pacman.

I was wondering how exiftool could improve that warning. Say more about the likely reason? Find the correct library itself?

**Comment by StarGeekSpaceNerd** [comment]
The first error is a Perl error and would probably be difficult at best to output a better response. The version check tells you the exact problem.

**Comment by stefanrueger** [comment]
> The version check tells you the exact problem

... *alas* not what the likely cause is nor what one can do about it.

It strikes me that the warning is less useful that it could be. In this case, exiftool fails, so the warning turns out to be fatal. How about outputting
```
13.03 [Warning: Library version is 12.76. If two versions of exiftool are installed delete the older version.]
```

Alternatively, given that exiftool *recognises* the conflict, could it not use the *right* library and ignore the wrong one? It's there after all!

**Comment by boardhead** [comment]
> Alternatively, given exiftool recognises the conflict, could it not use the right library and ignore the other? It's there after all!

No.  This would be very messy and only applicable for very specific installations.

- Phil

**Comment by boardhead** [comment]
I'll add a warning if the library version is incorrect.
