### ISSUE TITLE
using the ExifTool dlls in other languages

### ISSUE THREAD

**Issue by mschnell1** [exiftool/exiftool#279]
I am doing a Rust project that is supposed to insert EXIF tags in (many) existing JPEG images. 

I easily can do this by using the `exiftool.exe `executable (tested in a batch file, and when calling the executable in Rust by `std::process::Command`.

I understand that  `exiftool.exe ` does not much more than loading and calling a (huge) bunch of dlls. 

Of course it would be a lot more efficient when directly calling those dlls in the Rust code. 

In a perfect world, a Rust crate would encapsulate those calls with a native rust start. 
In a less perfect world, the `-stay_open` option can improve the performance ( -> https://github.com/a-roach/spawn_exiftool )

I found that some contributions in crates.io seem to make use of exiftool, but they seem not to be versatile enough. 

Thanks for listening !

**Comment by boardhead** [comment]
You are correct.  exiftool.exe effectively only runs "perl exiftool_files/exiftool.pl <args>" with the included vversion of Strawberry Perl.  The dll's are all from Strawberry Perl.

I don't know enough about rust help with your question.

- Phil

**Comment by mschnell1** [comment]
Hence I will build on the "spawn_exiftool" code.
Thanks !

**Comment by obetz** [comment]
The source code of the launcher is published on https://oliverbetz.de/wiki/Artikel/Portable-Perl-Applications
I didn't yet find the time to move it to GitHub
