### ISSUE TITLE
Extracting specific 1 of duplicate tags

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#280]
E.g. [ https://github.com/MasterInQuestion/talk/discussions/37#discussioncomment-10851555](https://github.com/MasterInQuestion/talk/discussions/37#discussioncomment-10851555)
    Extracting just specific 1 of the 2 "SamsungTrailer_0x0ba1":
    Currently there seems to be no way. (experimented several possible syntaxes; to no avail)
    [ There is: [ https://github.com/exiftool/exiftool/issues/280#issuecomment-2395248935](https://github.com/exiftool/exiftool/issues/280#issuecomment-2395248935) ]
    ; somewhat peculiar way...

    Somehow related:
    [ https://github.com/exiftool/exiftool/issues/165#issuecomment-1337301361](https://github.com/exiftool/exiftool/issues/165#issuecomment-1337301361)

    ----

    <&>Also I think ["-b"](https://exiftool.org/exiftool_pod.html#b---b--binary---binary) not implying ["-U"](https://exiftool.org/exiftool_pod.html#u--unknown) might be bug.
    (the example failed without "-U")</&> [ Pardon former mistake... ]

    Plus I still think outputting the parsed file size (for Pipe) makes more sense:
    [ https://github.com/exiftool/exiftool/issues/256#issuecomment-2159591051](https://github.com/exiftool/exiftool/issues/256#issuecomment-2159591051)

**Comment by StarGeekSpaceNerd** [comment]
Try using the `Group4` copy number (see the [`GetAllGroups` function](https://exiftool.org/ExifTool.html#GetAllGroups) for the various groups). In your example in your link, change   
`-g3:5:2`   
to   
`-g3:5:2:4`   
to get the copy numbers.

Then try this to access specific copies   
`-Copy1:SamsungTrailer_0x0ba1`
`-Copy2:SamsungTrailer_0x0ba1`

**Comment by MasterInQuestion** [comment]
Is "Copy#" guaranteed to sequentially increase from 1 for each duplicate?
    The output of "-g3:5:2:4" doesn't look quite sensible... (peculiar separation somewhat)

    You command has no "-U" related, I believe..?
    "-U" in the doc seemingly implied "binary".

**Comment by StarGeekSpaceNerd** [comment]
> Is "Copy#" guaranteed to sequentially increase from 1 for each duplicate?

Phil will have to answer that.

> "-U" in the doc seemingly implied "binary".

No, it does not. The docs on the [`-U` (`-unknown2`) option](https://exiftool.org/exiftool_pod.html#U--unknown2) say   
>Extract values of unknown tags  
 
This is the same as `-u`

> as well as unknown information from some binary data blocks  

Some binary data blocks, not necessarily unknown ones, might have more data embedded in them that exiftool can extract. This will extract unknown tags that might be in those blocks.  I could be wrong but I believe this is more applicable for use with the [`-ee` (`-extractEmbedded`) option](https://exiftool.org/exiftool_pod.html#ee-NUM--extractEmbedded), though it may also be for use with other embedded files, such as thumbnails or preview images.

**Comment by MasterInQuestion** [comment]
Indeed even my own commandlet vouches for that...

    For reference of "Copy#":
https://exiftool.org/ExifTool.html#GetGroup
    “Family 4 provides a method for differentiating tags when multiple tags exist with the same name in the same location.
    The primary instance of a tag (the tag extracted when the Duplicates option is disabled and no group is specified) has no family 4 group name:
    But additional instances have family 4 group names of "Copy1", "Copy2", "Copy3", etc.
    For convenience, the primary tag may also be accessed using a group name of "Copy0".”

**Comment by StarGeekSpaceNerd** [comment]
`-Copy1:SamsungTrailer_0x0ba1` is the way to use it

**Comment by MasterInQuestion** [comment]
I noted it yesterday and have updated the linked [E.g.](https://github.com/MasterInQuestion/talk/discussions/37#discussioncomment-10851555) accordingly.
    However there seems to be still several other issues about its usage.

**Comment by boardhead** [comment]
> Is "Copy#" guaranteed to sequentially increase from 1 for each duplicate?
> 
> Phil will have to answer that.

Yes, but not necessarily in the same order they were in the file.

- Phil

**Comment by MasterInQuestion** [comment]
I find current implementation maybe blindly counting all tags of the same name, regardless of their location (prefix): as "Copy#" instances.
    Such behavior probably doesn't really fit the description in documentation.

**Comment by boardhead** [comment]
Yes.  That is the ExifTool definition of a duplicate tag (ie. tag with the same name).

I thought that should be clear in the documentation.

- Phil

**Comment by MasterInQuestion** [comment]
A probable solution might be not touching the old "Copy#":
    Extending the syntax support for array index alike notation:
    Specifically for alike prefixed duplicate handling.
