### ISSUE TITLE
PGS Subtitle stream misdetected as Audio in M2TS

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#284]
"raw HDMV Presentation Graphic Stream subtitles" specifically: as "PGS Audio".
    https://trac.ffmpeg.org/ticket/10891#comment:5
    Verified with 12.99.

    `exiftool -U -ee3 -g3:5:2 -api "RequestAll=0" -api "ByteUnit=Binary" "00006.MTS" > "00006.MTS.txt"`
    See also: https://trac.ffmpeg.org/ticket/11002#comment:9

**Comment by boardhead** [comment]
I don't know if this is wrong, but certainly is misleading.  I'll change this to

"Presentation Graphics Stream (subtitle)"

- Phil

**Comment by boardhead** [comment]
Oh.  Actually this was wrong because ExifTool was picking up the "Audio" in the stream description and using it for the AudioStreamType.  Fixed.

- Phil

**Comment by MasterInQuestion** [comment]
I'm mostly also unsure of everything piled-up there...
    Best-effort, whatsoever.

**Comment by boardhead** [comment]
This will be fixed in 13.00
