### ISSUE TITLE
Question: WebAssembly version?

### ISSUE THREAD

**Issue by boustanihani** [exiftool/exiftool#285]
Just a question, are there any plans to offer a `WebAssembly` version of this library, so it can also run inside a browser, without the need for a server?

**Comment by StarGeekSpaceNerd** [comment]
I would say it is unlikely. Exiftool is written in Perl as that is what the author is most familiar with. It would probably be a difficult task to rewrite it in another language.

**Comment by boustanihani** [comment]
I thought maybe it could be simply compiled to `WebAssembly` with some glue-code and tweaking using a tool similar to those:
- https://developer.fermyon.com/wasm-languages/perl
- https://webperl.zero-g.net/
- https://perlwasm.github.io/
