### ISSUE TITLE
Viewing info of a PDF file with 'Binary data' takes too long.

### ISSUE THREAD

**Issue by MikZyth** [exiftool/exiftool#289]
Viewing info of a PDF file with *Binary data* takes too long to display the output (>1min).
At the end of `exiftool CUHYA-0080_Headset_QSG_US-CAN.pdf` output it shows something like:

    A To B0                         : (Binary data 89958 bytes, use -b option to extract)
    A To B2                         : (Binary data 89958 bytes, use -b option to extract)
    A To B1                         : (Binary data 89958 bytes, use -b option to extract)
    B To A0                         : (Binary data 145588 bytes, use -b option to extract)
    B To A1                         : (Binary data 145588 bytes, use -b option to extract)
    B To A2                         : (Binary data 145588 bytes, use -b option to extract)
    Gamut                           : (Binary data 37009 bytes, use -b option to extract)

Measuring time:

    $ time exiftool CUHYA-0080_Headset_QSG_US-CAN.pdf
    ...
    ...
    real    1m18,217s
    user    1m18,127s
    sys     0m0,021s

I'm not 100% sure if it's *Binary data* causing long load, but after checking several files I suspect that's the part to blame.
Also, `top` shows **perl** is using 100% CPU time during this.

Here is an example file:
https://secure.cdn.us.playstation.com/manuals/ps4/CUHYA-0080_Headset_QSG_US-CAN.pdf

Software:

    $ exiftool -ver
    13.02

    $ perl -v

    This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-gnu-thread-multi
    (with 44 registered patches, see perl -V for more detail)

    $ uname -srvpio
    Linux 6.8.0-48-generic #48-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 14:04:52 UTC 2024 x86_64 x86_64 GNU/Linux

**Comment by boardhead** [comment]
This cannot be considered a bug.  It is a design goal of PDF encryption -- to slow processing.  What I don't understand is why you would ever encrypt something with AES-128 encryption if the keys are included in the file.  Oh well.  It is the 500 kB of AES-128-encrypted data in this file that is causing the slow down.  See my comment here: https://github.com/exiftool/exiftool/blob/2218b0365311af26be63cede59ea9435efa85c40/lib/Image/ExifTool/AES.pm#L475

- Phil

**Comment by MikZyth** [comment]
Thanks for clearing this up.

**Comment by boardhead** [comment]
Thinking about this again there may be a way (possibly with the -fast option?) to avoid decrypting information of limited usefulness.

**Comment by MikZyth** [comment]
It would be nice to have such an option. Or even set it as a default behavior?
Having exiftool to stuck on a single file for 1 minute is somewhat unexpected (when we just want general meta info).

**Comment by boardhead** [comment]
OK.  The 500 kB encrypted data in this file was the ICC_Profile.  The XMP is also encrypted, but only 45 kB ("only" -- this is already pretty bloated).

ExifTool 13.03 will extract AES-encrypted XMP up to 100 kB normally, but above this, and above 10 kB for any other AES-encrypted data, a minor warning will be issued and the data won't be extracted.  You can use the -m option to ignore the warning and extract this data.

- Phil

**Comment by MikZyth** [comment]
> ExifTool 13.03 will extract AES-encrypted XMP up to 100 kB normally, but above this, and above 10 kB for any other AES-encrypted data, a minor warning will be issued and the data won't be extracted. You can use the -m option to ignore the warning and extract this data.

I think that's logical.
Can this warning still be suppressed with usual `-q -q` and thus silently skip decryption?

**Comment by boardhead** [comment]
Yes.

**Comment by MikZyth** [comment]
Thank you, Phil.
