### ISSUE TITLE
Some video (AVI, MP4) and audio (MP3) metadata edition support

### ISSUE THREAD

**Issue by urtzai** [exiftool/exiftool#29]
Hi! I would like to know why some format editing is not supported (AVI, MP4, MP3). Which are the obstacles to develop?

Thank you

**Comment by boardhead** [comment]
MP4 metadata editing is supported.  AVI is on the list, but I won't be able to do this until I have a lot of free time on my hands.  I attempted MP3 a long while back but abandoned the attempt because the ID3 specification is too ambiguous to to produce a reliable implementation.
