### ISSUE TITLE
Cannot transfer all exif from GeoTIFF to a COG (cloud optimised Geotiff)

### ISSUE THREAD

**Issue by luipir** [exiftool/exiftool#292]
**Describe the bug**
cannot transfer all Exif from a Geotiff to it's COG version

**To Reproduce**

1) get a generic GeoTIFF
2) convert in COG "format" generated with:
```gdal_translate source.tif destination.tif -of GTiff -co COMPRESS=DEFLATE -co TILED=YES```
or with:
```rio cogeo create source.tif destination.tif```
3) transfer tags from source to destination with:
```exiftool -tagsfromfile sopurce.tif -GeoTiffDirectory -GeoTiffDoubleParams -GeoTiffAsciiParams  destination.tif```
4) verify that not all tags are transferred from source to destination

**Expected behavior**
- destination.tif containe all the exif available into source
- verify that is stil a valid COG with rio cogeo validate destination.tif

**Desktop (please complete the following information):**
Ubuntu 24.04.1 LTS
0.27.6 (installed via apt)

**Comment by boardhead** [comment]
I don't know what a COG format is.  Could you upload some sample files?  (generic GeoTIFF and the converted COG file)

- Phil

**Comment by luipir** [comment]
Hi @boardhead a COG is a normal GeoTiff reorganised to optimise HTTP get of portion of image or metadata. in this way the image can be served via HTTP without to download all the image and servig only the visible part.
It is documente here: https://guide.cloudnativegeo.org/cloud-optimized-geotiffs/intro.html#:~:text=Cloud%2DOptimized%20GeoTIFF%20(COG),for%20display%20or%20data%20reading.

You can get any geotiff e.g. from https://github.com/mommermi/geotiff_sample
and convert to COG as in stap 2) e.g. you need to install GDAL or rio-cogeo. I would suggest GDAL.

**Comment by luipir** [comment]
hi @boardhead  Here two test images, the same one is GeoTiff and the other COG transformed.
NOTE the images are really small and not clear to me if the issue depend also on size of the image. I would use these test data but also a relatively big image to be sure to point correctly into tag directaories 
[samples.zip](https://github.com/user-attachments/files/17777808/samples.zip)

**Comment by boardhead** [comment]
WIth these samples, template_cog.tif contains geotiff metadata and template_nocog.tif doesn't.  I am able to copy the geotiff from one to the other.

```
% exiftool -geotiff:all .
======== ./template_cog.tif
Geo Tiff Version                : 1.1.0
GT Model Type                   : Projected
GT Raster Type                  : Pixel Is Area
GT Citation                     : WGS 84 / UTM zone 33N
Geog Citation                   : WGS 84
Geog Angular Units              : Angular Degree
Projected CS Type               : WGS84 UTM zone 33N
Proj Linear Units               : Linear Meter
======== ./template_nocog.tif
    1 directories scanned
    2 image files read
% exiftool -tagsfromfile template_cog.tif -GeoTiffDirectory -GeoTiffDoubleParams -GeoTiffAsciiParams template_nocog.tif 
    1 image files updated
% exiftool -geotiff:all .
======== ./template_cog.tif
Geo Tiff Version                : 1.1.0
GT Model Type                   : Projected
GT Raster Type                  : Pixel Is Area
GT Citation                     : WGS 84 / UTM zone 33N
Geog Citation                   : WGS 84
Geog Angular Units              : Angular Degree
Projected CS Type               : WGS84 UTM zone 33N
Proj Linear Units               : Linear Meter
======== ./template_nocog.tif
Geo Tiff Version                : 1.1.0
GT Model Type                   : Projected
GT Raster Type                  : Pixel Is Area
GT Citation                     : WGS 84 / UTM zone 33N
Geog Citation                   : WGS 84
Geog Angular Units              : Angular Degree
Projected CS Type               : WGS84 UTM zone 33N
Proj Linear Units               : Linear Meter
    1 directories scanned
    2 image files read
```

- Phil

**Comment by luipir** [comment]
let me give you a working case hopefully without to share  a big image

**Comment by luipir** [comment]
hmmm... seems that -tagsfromfile works also for most of the tags, I've only an issue when a tag is duplicated

e.g. if I've two repeated tags e.g.
Exif.Image.Software val1
Exif.Image.Software val2
Xmp.tiff.Software val1

for some reason (Sorry I'm not an exif or tag expert), after transfer, remain only:

Exif.Image.Software val2
Xmp.tiff.Software val2

e.g. the latest value and xmp updated with the latest value

**Comment by boardhead** [comment]
There shouldn't be 2 EXIF:Software tags in the same location.  Use this command to see the locations:

```exiftool -a -G1 -s FILE```

If they are in different locations, you can copy them both with -all:software, or by specifying both with their specific locations.

- Phil

**Comment by luipir** [comment]
works :), now trying to find the way to do this via python api (if any)
