### ISSUE TITLE
CLI vs API mismatch behaviour

### ISSUE THREAD

**Issue by luipir** [exiftool/exiftool#293]
**Describe the bug**
API behaviour (e.g. accepted parameter format) do not follow the same rule as CLI

**To Reproduce**
probably my lack of knowledge of the use of the API. I'm updating tags in a Tiff (COG formatted) and most of tags are updated correctly but some are ignored:
I did manually a test and this is the mismatch
```
In [10]: with ExifTool() as et:
    ...:     et.execute('-Exif:GPSLatitude="41 55 24"', "./notag_cog.tif")    <--- try to update the value via API
    ...: 

In [11]: !exiv2 -pt  notag_cog.tif| grep -i GPSLatitude
Warning: Directory Image3 has an unexpected next pointer; ignored.
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  40deg 54' 23"    <--- remain the old value

In [12]: !exiftool -Exif:GPSLatitude="41 55 24"  notag_cog.tif                <--- update it via CLI with same parameter as API
    1 image files updated

In [13]: !exiv2 -pt  notag_cog.tif| grep -i GPSLatitude
    ...: 
Warning: Directory Image3 has an unexpected next pointer; ignored.
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  41deg 55' 24"        <--- and via CLI it works
```

any hint?
I tried to change from "41 55 24"" to "41deg 55min 24sec" but behaviour does not change. 

p.s. sorry to use exiv2, just because allow me to write less parameters ;)

**Expected behavior**
API and CLI would be fine to have the same syntax management

**Desktop (please complete the following information):**
Ubuntu 24.04.1 LTS
0.27.6 (installed via apt)

**Comment by luipir** [comment]
ok, more debug

```
In [20]: with ExifTool() as et:
    ...:     et.execute(*['-Exif:GPSLatitude="41 55 23"', "./notag_cog.tif"])
    ...:     print(et.last_stderr)
    ...: 
Warning: Argument ""41 55 23"" isn't numeric in abs in GPS:GPSLatitude (ValueConvInv)
Nothing to do.
```

**Comment by luipir** [comment]
e.g. in this case I've to convert value in a float number!
in fact this works
```
In [25]: with ExifTool() as et:
    ...:     et.execute('-Exif:GPSLatitude=41.555', "./notag_cog.tif")
    ...:     print(et.last_stderr)
    ...: 


In [26]: !exiv2 -pt  notag_cog.tif| grep -i GPSLatitude
Warning: Directory Image3 has an unexpected next pointer; ignored.
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  41deg 33' 18"
```

is there a reason to have this different behaviour respect CLI use? or better question, is there a way to align use of API to CLI adding some more parameter?

**Comment by luipir** [comment]
Adapted the code to the behaviour and overridden this "issue" (if any). BTW I leave open the ticket as a form to add documentation.

**Comment by StarGeekSpaceNerd** [comment]
Copy/Paste from [my response on the exiftool forums](https://exiftool.org/forum/index.php?msg=89932)

`et.execute` isn't an exiftool API command. See the [Image::ExifTool Perl Library Module](https://exiftool.org/ExifTool.html).

It sounds like you're using [PyExifTool](https://github.com/sylikc/pyexiftool). This was created by a 3rd party and isn't supported by the author of exiftool.

I did find [this StackOverflow answer](https://stackoverflow.com/questions/50938662/) which seems like it might apply to your problem.

**Comment by StarGeekSpaceNerd** [comment]
Ah, good catch Phil.

From the [PyExiftool docs](https://sylikc.github.io/pyexiftool/examples.html#input-parameters)   
>Parameters which need to be quoted on the command line generally do not need to be quoted in the parameters to PyExifTool. In fact, quoting may have unintended behavior.

**Comment by luipir** [comment]
Houch! so sorry @StarGeekSpaceNerd @boardhead , I didn't realised that pyexiftool was not belonging to the project!
