### ISSUE TITLE
Default output timestamps format in ISO 8601?

### ISSUE THREAD

**Issue by MasterInQuestion** [exiftool/exiftool#298]
E.g. in: [ https://github.com/exiftool/exiftool/issues/288#issue-2639125299](https://github.com/exiftool/exiftool/issues/288#issue-2639125299)
    It would be "2024-08-25T06:03:45Z" alike.
    Refer also:
    https://github.com/orgs/community/discussions/5972#discussioncomment-10731225

    Such shall improve general interoperability.

    Related:
    [ https://github.com/exiftool/exiftool/issues/182](https://github.com/exiftool/exiftool/issues/182)
    https://exiftool.org/forum/?topic=1654;all#msg7223
    https://exiftool.org/forum/?topic=11436;all
    https://exiftool.org/forum/?topic=16480;all#msg88511
    https://exiftool.org/forum/?topic=3956;all#msg18493
    https://exiftool.org/forum/?topic=11914;all#msg64291
\
\
    Off-Topic:
    Is there a "standard" date renaming?
    https://exiftool.org/forum/?topic=15639;all
    .
    My practice: https://trac.ffmpeg.org/ticket/11139#comment:12
    See also: [ https://github.com/MasterInQuestion/talk/discussions/3#discussioncomment-9584627](https://github.com/MasterInQuestion/talk/discussions/3#discussioncomment-9584627)

**Comment by StarGeekSpaceNerd** [comment]
Exiftool uses the EXIF standard for date/time values. Forcibly changing it would break innumerable scripts and commands that have been made over the 21-year lifespan of exiftool.

You can change the output format for your own use by using the [`-d` (`-dateFormat`) option](https://exiftool.org/exiftool_pod.html#d-FMT--dateFormat) in a command or by setting a default [`DateFormat` option](https://exiftool.org/ExifTool.html#DateFormat) in your `.exiftool_config` file, under the `%Image::ExifTool::UserDefined::Options` section (see the [`example.config` file](https://exiftool.org/config.html)).

**Comment by MasterInQuestion** [comment]
Such is somewhat like the &#x60;ls&#x60; parsers question...
    For any proper script: it should reasonably handle the potential formats.
    (fragile scripts break regardless)

    Fundamentally also because how the general datetime representation in history has been ill-defined.
    And leading to such havocs...

    Good to see the workaround, however.
