### ISSUE TITLE
Lens Distortion info

### ISSUE THREAD

**Issue by photopea** [exiftool/exiftool#3]
[This CR2 file](http://www.rawsamples.ch/raws/canon/RAW_CANON_G7X.CR2)  stores raw data with "Lens distortion" (Rectilinear warp, Fisheye warp) - Straight lines (which don't go through the center) are not straight - https://i.imgur.com/pzErgWp.jpg.

When this CR2 image is converted into a DNG image with Adobe tool, the distortion parameters are added to the DNG file (in form of Opcode - WarpRectilinear), which allow the DNG viewer to "straighten" the image (when you convert this image to DNG and open it e.g. in [Photopea.com](https://www.Photopea.com), lines are straightened according to the Opcode - https://i.imgur.com/ZA9J4S3.png).

Do you thing such distortion parameters are present in a CR2 file (or could they be computed from the present parameters)? Or an extra database of lenses and their parameters is needed?

**Comment by exiftool** [comment]
I don't know of any stored distortion correction parameters other than an intensity stored by the canon software.  Likely they use a lookup table.

**Comment by photopea** [comment]
One parameter is usually enough to describe a distortion. Is this "Intensity" stored in a CR2 file? I can not see it in https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Canon.html

In DNG, they use multiple parameters, but they are related (like an approximation with a polynomial).

**Comment by boardhead** [comment]
It is written by canon software here:  http://owl.phy.queensu.ca/~phil/exiftool/TagNames/CanonVRD.html

**Comment by photopea** [comment]
Ok, thanks!
