### ISSUE TITLE
arabic language issue

### ISSUE THREAD

**Issue by 0xFTA** [exiftool/exiftool#302]
if the file or file path names contain arabic characters the tool don't work at all
![image](https://github.com/user-attachments/assets/1a7d2af0-c6da-4900-ad62-8b5fe354e377)

**Comment by StarGeekSpaceNerd** [comment]
See [FAQ #18, problems with special characters on the Windows command line](https://exiftool.org/faq.html#Q18).

**Comment by 0xFTA** [comment]
thanks

**Comment by MasterInQuestion** [comment]
Refer also:
    [ https://github.com/microsoft/vscode/issues/11770#issuecomment-2460541088](https://github.com/microsoft/vscode/issues/11770#issuecomment-2460541088)
    ; the Bi-Disorder...
