### ISSUE TITLE
exiftool switches height and width values

### ISSUE THREAD

**Issue by pixelgun-dev** [exiftool/exiftool#34]
Running exiftool on a directory with tif images will rotate them counter clockwise, basically switching width and height.

```bash
exiftool -tagsfromfile profile.xmp -ext tif test_data/TIFF/
```

![image](https://user-images.githubusercontent.com/58492680/72913566-2c3a6c80-3cf2-11ea-9835-af9eec9c6be0.png)

Before I forget, I am on a linux box running Ubuntu 18.

**Comment by boardhead** [comment]
ExifTool doesn't do image manipulation, so it won't rotate the image.  But if you are copying the Orientation tag then it may be displayed as rotated by some image viewers.

- Phil

**Comment by pixelgun-dev** [comment]
Hello,

I tested it again to make sure that I don't see ghosts. Here is my XMP file and the test tif files as well  (before and after).

```bash
exiftool -tagsFromFile AL006_POLO_C01_1612.xmp testing_03.tif
```


[test_imgs.zip](https://github.com/exiftool/exiftool/files/4111494/test_imgs.zip)

[xmp_file.zip](https://github.com/exiftool/exiftool/files/4111484/xmp_file.zip)

**Comment by boardhead** [comment]
`> exiftool tmp/test_imgs -orientation
======== tmp/test_imgs/test_img.tif
Orientation                     : Horizontal (normal)
======== tmp/test_imgs/test_img_2.tif
Orientation                     : Rotate 270 CW
    1 directories scanned
    2 image files read
> exiftool tmp/AL006_POLO_C01_1612.xmp -orientation
Orientation                     : Rotate 270 CW`

**Comment by pixelgun-dev** [comment]
Thank you for having a look at it.
