### ISSUE TITLE
Ability to update preview images in raw files

### ISSUE THREAD

**Issue by whatdoineed2do** [exiftool/exiftool#35]
I had raised a query in exiv2 (#48) a few years ago asking if this was supported but they said no.

Does exiftool have any support to change/replace embedded previews in raw files like .nef files?

The discontinued Nikon capture nx2 was the only thing I was aware of that supported this and wonder if this can be supported or technically possible

**Comment by boardhead** [comment]
ExifTool may be used to replace any JPEG preview in an NEF file.

**Comment by boardhead** [comment]
Closing this because I don't think it is an issue with ExifTool
