### ISSUE TITLE
What does "Missing expected box" mean?

### ISSUE THREAD

**Issue by ebekebe** [exiftool/exiftool#37]
I generated a HEIC file with the libheif's included `heif-enc` utility. When I try to copy over the meta data from the original PNG file like so...

```sh
exiftool -overwrite_original_in_place -tagsFromFile input.tif output.heic
```

... I get the following warning:

```
Warning: Can't create EXIF. Missing expected box - output.heic
    0 image files updated
```

I tried it with a HEIC that was generated with `sips` and it worked as expected. However, I want to use the 10-bit color-depth functionality of `heif-enc`, so using `sips` is not an option. What does this warning tell me? Is it a bug in exiftool or libheif?

OS: Mac OS 10.15.3
Exiftool: 11.85
Libheif: 1.6.2

**Comment by boardhead** [comment]
Could you send me the file so I can take a look?  (philharvey66 at gmail.com)

ExifTool expects there to be iiref, iref and iloc boxes in an HEIC file, and relies on these in order to add EXIF and XMP information.  It is likely that this is a valid HEIC file, but it appears I may have to add the ability to add these boxes if they are missing.

**Comment by ebekebe** [comment]
@boardhead Thanks, I just sent it to your email address.

**Comment by boardhead** [comment]
Thanks.  This image is missing the iref box.  I'll have to sort through my references to see if this is legal.

**Comment by boardhead** [comment]
It seems that this is legal.  I have patched Exiftool and released version 11.86 with the ability to add the iref box if it is missing.

Thanks for this report, and for the sample HEIC file.

**Comment by ebekebe** [comment]
Thank you for this very timely fix. 😀

**Comment by boardhead** [comment]
I see you are a kiteboarder.  Nice.  I'm jealous.  Looks like a lot of fun.

**Comment by ebekebe** [comment]
> I see you are a kiteboarder. Nice. I'm jealous. Looks like a lot of fun.

It is a lot of fun, but don't tell anyone otherwise the spots become even more crowded. 😉
