### ISSUE TITLE
Why MPF data is readable but not writable?

### ISSUE THREAD

**Issue by jeankvd** [exiftool/exiftool#4]
I am trying to do something with Facebook 3D Photos and while I can extract the data with Exiftool I can't add it. MPF tag seems to be read only. Is there any reason for this limitation?

**Comment by boardhead** [comment]
It would be difficult to add this ability, and there is very little demand to write this (ie. you are the only one so far to request this).

**Comment by jeankvd** [comment]
Ahh thankyou, i was wondering if I was doing something wrong.
