### ISSUE TITLE
Warning: Can't create EXIF. No primary item reference

### ISSUE THREAD

**Issue by aikinai** [exiftool/exiftool#43]
Hello,

I'm trying to create HEIC files with FFMPEG and MP4Box and then update the metadata with ExifTool, but I'm getting Warning: `Can't create EXIF. No primary item reference`. This seems very similar to the issue you fixed in #37 (I was actually getting that issue first until I updated to the latest ExifTool).

Here are the commands I'm using to generate my HEIC file:
`ffmpeg -i input.tif -vf "crop=trunc(iw/2)*2:trunc(ih/2)*2" -pix_fmt yuv420p -f hevc tmp.hvc`
`MP4Box -add-image tmp.hvc -ab heic -new output.heic`

Based on your response in #37, I'll go ahead and email you a sample file.

And by the way, thanks a lot for the incredible software! I've enjoyed using exiftool for many many years.

Thank you!

**Comment by boardhead** [comment]
I got the sample, thanks.  I'll see what I can do.

**Comment by aikinai** [comment]
Wow, thanks for the super fast response!

Actually I couldn't stop myself from digging in more and I happened to notice that MP4Box has a `-set-primary` option. I don't understand it at all, but since the terminology matched, I tried a shot in the dark with `-set primary 1` and it worked!

I'll leave this open though, just in case the version without a primary item reference is also valid and worth adding to ExifTool as well.

Thank you!

**Comment by boardhead** [comment]
The first thing I have to do is consult the specification (which I don't have handy ATM) to see if a missing primary item reference box is legal.  However, since there was only one item in the file you sent, it is fairly obvious which one was the primary item.  But I may have to add one when adding the EXIF item.

**Comment by boardhead** [comment]
I've just released ExifTool 11.93.  This version should add a PrimaryItemReference if it is missing.

**Comment by aikinai** [comment]
Great, thanks again for the super fast response!
