### ISSUE TITLE
Prevent rational calculation from taking place when writing value

### ISSUE THREAD

**Issue by lackac** [exiftool/exiftool#44]
I'm using exiftool to annotate PDF invoices with information extracted from the documents. One of the attributes I'm writing is the Invoice Number which is supposed to be an arbitrary string. The problem happens when this value happens to be two numbers separated by a slash (e.g. `2020/0042`). In this case `exiftool` calculates the flowing point value of the rational number and stores that in the metadata.

Is there a way to avoid this type of calculation? I tried setting the type of the attribute in the config explicitly to `string` but that didn't help. I also tried quoting the value or escaping the slash, but those also changed the value which I would like to avoid.

**Comment by boardhead** [comment]
ExifTool converts unknown tags that look like fractions to a real number when reading if the XMPAutoConv API option is set (which is the default).

But ExifTool won't do this when writing unless the tag's Writable type is set to 'rational'.

If you are having problems when writing then please post your config file and an example command so I can reproduce this here.

**Comment by lackac** [comment]
OK, here's a complete example:

#### `exiftool.config`

```
%Image::ExifTool::UserDefined = (
  'Image::ExifTool::XMP::Main' => {
    InvoiceData => {
      SubDirectory => {
        TagTable => 'Image::ExifTool::UserDefined::InvoiceData',
      },
    },
  },
);

%Image::ExifTool::UserDefined::InvoiceData = (
  GROUPS => { 0 => 'XMP', 1 => 'XMP-InvoiceData', 2 => 'Document' },
  NAMESPACE => { 'InvoiceData' => 'https://ns.100starlings.com/InvoiceData/1.0/' },
  WRITABLE => 'string',

  InvoiceNumber1 => {},
  InvoiceNumber2 => { Writable => 'string' },
);
```

#### commands

```
❯ exiftool -config exiftool.config invoice.pdf -InvoiceNumber1=2020/0042 -InvoiceNumber2=2020/0042
    1 image files updated

❯ exiftool invoice.pdf -XMP-InvoiceData:all
Invoice Number 1                : 48.0952380952381
Invoice Number 2                : 48.0952380952381
```

**Comment by lackac** [comment]
I also tried disabling `XMPAutoConv` with no luck:

```
❯ exiftool invoice.pdf -XMP-InvoiceData:all=
    1 image files updated

❯ exiftool invoice.pdf -XMP-InvoiceData:all

❯ exiftool -config exiftool.config invoice.pdf -api XMPAutoConv=0 -InvoiceNumber1=2020/0042 -InvoiceNumber2=2020/0042
    1 image files updated

❯ exiftool invoice.pdf -XMP-InvoiceData:all
Invoice Number 1                : 48.0952380952381
Invoice Number 2                : 48.0952380952381
```

**Comment by lackac** [comment]
```
❯ exiftool -ver
11.85
```

**Comment by boardhead** [comment]
As I said, ExifTool converts fractions to real numbers for unknown tags when reading if XMPAutoConv is set.  So either use your config file or "-api xmpautoconv=0" when reading the file back again:

`> exiftool invoice.pdf -XMP-InvoiceData:all
Invoice Number 1                : 48.0952380952381
Invoice Number 2                : 48.0952380952381
> exiftool -config exiftool.config invoice.pdf -XMP-InvoiceData:all 
Invoice Number 1                : 2020/0042
Invoice Number 2                : 2020/0042
> exiftool invoice.pdf -XMP-InvoiceData:all -api xmpautoconv=0
Invoice Number 1                : 2020/0042
Invoice Number 2                : 2020/0042
`

**Comment by lackac** [comment]
@boardhead you are right, of course. I didn't read you message carefully enough. Now I understand. Thank you for your help and patience!
