### ISSUE TITLE
Warning: Bad IFD0 directory in HEIF/HEIC file

### ISSUE THREAD

**Issue by ao2** [exiftool/exiftool#45]
HI,

I am learning about Exif and HEIF files and I came a cross a file in the `heif_conformance` suite from Nokia that should contain Exif data but gives an error in exiftools:

```
$ exiftool -ver
11.94
$ exiftool -Exif:all C034.heic 
substr outside of string at /usr/share/perl5/Image/ExifTool.pm line 7054.
Warning: Bad IFD0 directory - C034.heic
```

The test file can be retrieved from here:  https://github.com/nokiatech/heif_conformance/blob/master/conformance_files/C034.heic

Is the file wrong? Or is exiftool missing something?

Thanks, Antonio

**Comment by boardhead** [comment]
Hi Antonio,

Thanks for this report, and for the sample.  Whatever wrote this file is not following the standard technique for writing Exif in the HEIC file.  The Exif is missing the required header.  I will patch ExifTool 11.95 to issue a warning for Exif like this and process it anyway.

**Comment by boardhead** [comment]
This issue should be resolved with ExifTool 11.95

**Comment by ao2** [comment]
Thanks a lot Phil, the change is this one, isn't it?
https://github.com/exiftool/exiftool/commit/467a6ed62c4a1c6e88cfe29a58d2256c13bcac11#diff-8b1034931c1b78ef21092364e9ded354R8232

**Comment by boardhead** [comment]
Yes, the change was in 11.95.
