### ISSUE TITLE
Missing TIFF tags flagged as required despite having default values

### ISSUE THREAD

**Issue by marhop** [exiftool/exiftool#47]
ExifTool version: 11.99

Running `exiftool -validate -warning -a` on the [attached file](https://github.com/exiftool/exiftool/files/4631226/example.zip) ([source](https://github.com/marhop/literate-binary/blob/master/examples/tiff/bilevel-tiff.md)) raises two warnings:

* Missing required TIFF IFD0 tag 0x0102 BitsPerSample
* Missing required TIFF IFD0 tag 0x0128 ResolutionUnit

However, this is a very simple bilevel (black/white) TIFF file where the default values for BitsPerSample (1) and ResolutionUnit (2 = inch) given in the [TIFF 6.0 specification](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf) are appropriate. According to the spec (pages 21, 26) in this case it is permitted to omit these tags.

What do you think? Are these tags really required for (bilevel) TIFF files?

Thanks,
Martin

**Comment by boardhead** [comment]
Hi Martin,

Great, thanks!  This will be fixed in version 12.00

- Phil

**Comment by marhop** [comment]
Nice, thank you for the quick reply! And for ExifTool in general, by the way. ;-) I've been using it for years, there's nothing better.

Best,
Martin

**Comment by boardhead** [comment]
Version 12.00 is out
