### ISSUE TITLE
Nikon D850 AF points data

### ISSUE THREAD

**Issue by flexphperia** [exiftool/exiftool#48]
When the focus mode is phase detect, the focus point cannot be saved by exiftool.

For example in this file: [image](https://2.img-dpreview.com/files/p/sample_galleries/5682971467/6430118548.jpg)
The `PrimaryAFPoint ` tag value is `C12`. Changing this tag with ExifTool does not change the focus point by viewing in Nikon Capture NX-D so the active focus point is saved elsewhere.
I can't find AF data in any other tag, does anyone have any idea?

**Comment by boardhead** [comment]
I've finally found time to look into this, and have posted my analysis here: https://exiftool.org/forum/index.php?topic=11190.msg60324#msg60324
