### ISSUE TITLE
Nikon NEF MakerNote:  D4 Crop information

### ISSUE THREAD

**Issue by photopea** [exiftool/exiftool#5]
These raw Nikon NEF files: https://www.photographyblog.com/reviews/nikon_d4_review/sample_images  have resolution of 4992 x 3292, but need to be cropped to 4928 x 3280, the area is located 8 pixels form the left and 6 pixels form the top.

ExifTool can not detect this cropping information yet. Is there anybody, who could look into it and find this information in the file? I tried to look for it in all MakerNote entries, as both Big and Little-endian Uint16, but did not find it, so maybe it is encrypted somehow.

**Comment by boardhead** [comment]
The crop information written by the D4 is:

Crop Hi Speed                   : Off (4992x3292 cropped to 4992x3292 at pixel 0,0)

However, the AFImageWidth/AFImageHeight is 4928/3280.  Maybe you could use this.

**Comment by boardhead** [comment]
I'm closing this since I don't see any action to take here.
