### ISSUE TITLE
Copying metadata from MP4 does not seem to update target file metadata

### ISSUE THREAD

**Issue by iburunat** [exiftool/exiftool#50]
I am trying to copy creation date from one MP4 file to another using several ways:

```
exiftool -tagsFromFile video.mp4 -MediaCreateDate videoNEW.mp4
exiftool -tagsFromFile video.mp4 videoNEW.mp4
exiftool -all= -tagsfromfile video.mp4 -exif:all videoNEW.mp4
```
I always get:

`  1 image files updated`

However, the creation date in the target file (videoNEW.mp4) remains unchanged.
I wonder if I am doing something wrong. I read through the documentation.
Thanks for your help!

**Comment by boardhead** [comment]
Add [tt]-v3[/tt] to get more details about what ExifTool is doing.

But I think the crux of the matter is this statement:

_"the creation date in the target file (videoNEW.mp4) remains unchanged"_

How are you determining this?  Did you verify using ExifTool that MediaCreateDate is changed after your first command?  If so, what creation date are you talking about?  Try this command to see them all:

`exiftool -time:all -a -G1 -s FILE`

**Comment by iburunat** [comment]
> But I think the crux of the matter is this statement:
> 
> "the creation date in the target file (videoNEW.mp4) remains unchanged"
> 
> How are you determining this? Did you verify using ExifTool that MediaCreateDate is changed after your first command? If so, what creation date are you talking about? Try this command to see them all:

My bad. I was looking at the _system_ creation date (!). All works perfect. Exif info is copied successfully.
