### ISSUE TITLE
Sony lenses missing

### ISSUE THREAD

**Issue by Beep6581** [exiftool/exiftool#54]
Hey

RawTherapee uses ExifTool and I noticed that some Sony lenses are no longer identified correctly.

Sample raw file:
http://rawtherapee.com/shared/test_images/chicken.arw

The lens is identified correctly when I use ExifTool 11.55, 11.56 and current `master` (12.01) from the command line:
```
~/programs/code-exiftool $ git checkout 11.55
HEAD is now at 3574005 Update to 11.55
~/programs/code-exiftool $ ./exiftool ~/downloads/chicken.arw | grep "Sony FE 70-200mm F4 G OSS"
Lens Type 3                     : Sony FE 70-200mm F4 G OSS
Lens Type 2                     : Sony FE 70-200mm F4 G OSS
Lens ID                         : Sony FE 70-200mm F4 G OSS
~/programs/code-exiftool $ git checkout 11.56
Previous HEAD position was 3574005 Update to 11.55
HEAD is now at ce3280c Update to 11.56
~/programs/code-exiftool $ ./exiftool ~/downloads/chicken.arw | grep "Sony FE 70-200mm F4 G OSS"
Lens Type 3                     : Sony FE 70-200mm F4 G OSS
Lens Type 2                     : Sony FE 70-200mm F4 G OSS
Lens ID                         : Sony FE 70-200mm F4 G OSS
~/programs/code-exiftool $ git checkout master
Previous HEAD position was ce3280c Update to 11.56
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
~/programs/code-exiftool $ ./exiftool ~/downloads/chicken.arw | grep "Sony FE 70-200mm F4 G OSS"
Lens Type 3                     : Sony FE 70-200mm F4 G OSS
Lens Type 2                     : Sony FE 70-200mm F4 G OSS
Lens ID                         : Sony FE 70-200mm F4 G OSS
```

I found that the XML dump from ExifTool 11.55 has these lenses, while they are missing from 11.56 onward:
```
~/programs/code-exiftool $ git checkout 11.55
HEAD is now at 3574005 Update to 11.55
~/programs/code-exiftool $ xmlstarlet sel -T -t -m "taginfo/table/tag[@name='LensType']/values/key" -v "concat(@id,'       ',val)" -n < <(~/programs/code-exiftool/exiftool -listx -sony:all) | sort -fuV | grep -i "Sony FE 70-200mm F4 G OSS"
6553.25 Sony FE 70-200mm F4 G OSS
65535.25        Sony FE 70-200mm F4 G OSS
~/programs/code-exiftool $ git checkout 11.56
Previous HEAD position was 3574005 Update to 11.55
HEAD is now at ce3280c Update to 11.56
~/programs/code-exiftool $ xmlstarlet sel -T -t -m "taginfo/table/tag[@name='LensType']/values/key" -v "concat(@id,'       ',val)" -n < <(~/programs/code-exiftool/exiftool -listx -sony:all) | sort -fuV | grep -i "Sony FE 70-200mm F4 G OSS"
~/programs/code-exiftool $ git checkout master
Previous HEAD position was ce3280c Update to 11.56
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
~/programs/code-exiftool $ xmlstarlet sel -T -t -m "taginfo/table/tag[@name='LensType']/values/key" -v "concat(@id,'       ',val)" -n < <(~/programs/code-exiftool/exiftool -listx -sony:all) | sort -fuV | grep -i "Sony FE 70-200mm F4 G OSS"
```

`LensType2` and `LensType3` in `master` still list the lens but with a different ID: 32810 instead of 6553.25 or 65535.25.

Some source code grepping:
```
git checkout 11.55
HEAD is now at 3574005 Update to 11.55
grep -rni "sony fe 70-200mm f4" *
html/TagNames/Sony.html:1654:</tr><tr><td>6553.25</td><td>= Sony FE 70-200mm F4 G OSS</td>
html/TagNames/Sony.html:1896:</tr><tr><td>65535.25</td><td>= Sony FE 70-200mm F4 G OSS</td>
html/TagNames/Sony.html:4977:</tr><tr><td>32810</td><td>= Sony FE 70-200mm F4 G OSS</td>
html/TagNames/Minolta.html:609:</tr><tr><td>65535.25</td><td>= Sony FE 70-200mm F4 G OSS</td>
lib/Image/ExifTool/Sony.pm:111:    32810 => 'Sony FE 70-200mm F4 G OSS', #JR   # VX9126
lib/Image/ExifTool/Minolta.pm:569:   '65535.25' => 'Sony FE 70-200mm F4 G OSS',       #JR (32810 - SEL70200G)

git checkout 11.56
Previous HEAD position was 3574005 Update to 11.55
HEAD is now at ce3280c Update to 11.56
grep -rni "sony fe 70-200mm f4" *
html/TagNames/Sony.html:4762:</tr><tr><td>32810</td><td>= Sony FE 70-200mm F4 G OSS</td>
lib/Image/ExifTool/Sony.pm:111:    32810 => 'Sony FE 70-200mm F4 G OSS', #JR   # VX9126
```

Could someone shed some light on what's going on?

**Comment by boardhead** [comment]
I'm confused.  You say that some lenses are no longer identified correctly, then show an example where the lenses are identified correctly.  Can you provide a sample file where they are not?  11.56 removed duplicate lens entries from Minolta.pm, but that change should have affected the lens identification.  If it did, please send a sample.  If you can't post it here you can email it to me (philharvey66 at gmail.com)

**Comment by Beep6581** [comment]
@boardhead the lens in the sample raw file is identified correctly when I use ExifTool via CLI. However, when I dump the data or look through the source, I see many lenses were removed. Where can I read more about where these IDs come from and how they work (6553.25 vs 65535.25 vs 32810??), why there are several entries for a single lens, and why some entries were removed and not others?

**Comment by boardhead** [comment]
I see.  You mean the -listx XML output (ie. the ExifTool database) and the way these are handled in the source code.  Before version 11.56, Sony E-type lenses were duplicated in both Minolta.pm and Sony.pm, which was a bit of a pain.  So instead, LensType 65535 is handle specially for Sony NEX and ICLE models, and the sonyLensType2 list is used instead: https://exiftool.org/TagNames/Sony.html#LensType2

**Comment by aradzie** [comment]
This bug also affects me.

I am trying to import raw files from my camera into RawTherapy, but it is unable to obtains lens info from Exif data. On the meta tab it displays Exif->MakerNote->LensID: Unknown (35mm f1.8). And the result is that on the Transform tab it is unable to automatically select lens profile.

- RawTherapee version: **5.8**
- Camera Name: **Sony Alpha 6400**
- Camera Id: **ILCE-6400**
- Camera firmware version: **2.0**
- Lenses: **Sony E 35mm F1.8 OSS** and **Sony E PZ 16-50mm F3.5-5.6 OSS**

Taking metadata with `exiv2`:

```
exiv2 -pv DSC00149.ARW | grep -i lens
0xb027 Sony2        LensID                      Long        1  65535
```

Taking metadata with `exiftool`:

```
exiftool DSC00149.ARW | grep -i lens
Lens Type                       : E-Mount, T-Mount, Other Lens or no lens
Lens Spec                       : E 35mm F1.8 OSS
Lens Zoom Position              : 0%
Lens Mount 2                    : E-mount
Lens Type 3                     : Sony E 35mm F1.8 OSS
Lens E-mount Version            : 1.20
Lens Firmware Version           : Ver.01.000
Lens Mount                      : E-mount
Lens Format                     : APS-C
Lens Type 2                     : Sony E 35mm F1.8 OSS
Lens Spec Features              : E OSS
Lens Info                       : 35mm f/1.8
Lens Model                      : E 35mm F1.8 OSS
Lens ID                         : Sony E 35mm F1.8 OSS
```

**Comment by boardhead** [comment]
This appears to be a RawTherapy problem because ExifTool identifies the lenses correctly.

**Comment by Beep6581** [comment]
Yes, it certainly is.

Do you know of any other groups of lenses affected by similar cleanups since 11.55? ExifTool's git commit messages are unfortunately unhelpful.

**Comment by boardhead** [comment]
Check the revision history in the Changes file for a complete list of changes, but I think that was the only place where lens ID's were consolidated.
