### ISSUE TITLE
STDOUT vs. STDERR for "image files created" message

### ISSUE THREAD

**Issue by marhop** [exiftool/exiftool#56]
Hi Phil,

ExifTool (on Linux/Bash) seems to choose different output streams for messages depending on the input format.

* The command `exiftool a.jpg -Subject=foo` writes "1 image files created" to _STDOUT_.
* The command `exiftool a.jpg -json=meta.json` writes the same answer to _STDERR_. (FTR, `meta.json` contains `[{ "Subject": "foo" }]`.)

Is this intentional?

Cheers,
Martin

**Comment by boardhead** [comment]
It was intentional to write the summary messages to stderr when using -json output format (so you can pipe the JSON to a file).  The fact that it also does this when writing with -json=JSONFILE is I suppose not necessary, but I don't know if it is worthwhile changing this.  (This is the same for the -csv option.)

**Comment by marhop** [comment]
Ah I see.

> but I don't know if it is worthwhile changing this

Probably not, particularly if sending those messages to STDERR in case of JSON *output* would still be necessary.

Some background FYI, this behavior is a little confusing in combination with the `-stay_open` option. With "regular" input you get both the summary message and the `{ready}` string via STDOUT, while with JSON input the summary message goes to STDERR but the `{ready}` string still goes to STDOUT. Knowing this is intentional I can work around this though.

Thanks,
Martin

**Comment by boardhead** [comment]
I should probably document the way that some options change the output of the summary messages.  But yes, the "{ready}" messages should consistently go to stdout (which _is_ documented).
