### ISSUE TITLE
Writing metadata to .djvu files

### ISSUE THREAD

**Issue by iamashwin99** [exiftool/exiftool#57]
I am trying to modify metadata for some books (lots of them) and currently, I am using ExifTool to handle all the pdf. However, I see that write capability to Djvu files is limited. I request for a write capability for DjVu files. I haven't used Perl, so I can help you with the testing part.

**Comment by boardhead** [comment]
There isn't much demand for this.  There is a work-around:  If you want to write XMP to DjVu, you can use ExifTool to write the XMP file, then use the DjVu utility to add it to the image.

**Comment by iamashwin99** [comment]
Could you please help me out with an example,
I tried 
`exiftool -Title="Sometitle" -Author="someone" -Year="2000" -Publisher="someoneelse" -SeriesName="infinite" op.xmp`
which generated 
```
<?xpacket begin='' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='Image::ExifTool 12.00'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>

 <rdf:Description rdf:about=''
  xmlns:Iptc4xmpExt='http://iptc.org/std/Iptc4xmpExt/2008-02-29/'>
  <Iptc4xmpExt:Series rdf:parseType='Resource'>
   <Iptc4xmpExt:Name>infinite</Iptc4xmpExt:Name>
  </Iptc4xmpExt:Series>
 </rdf:Description>

 <rdf:Description rdf:about=''
  xmlns:dc='http://purl.org/dc/elements/1.1/'>
  <dc:publisher>
   <rdf:Bag>
    <rdf:li>someoneelse</rdf:li>
   </rdf:Bag>
  </dc:publisher>
  <dc:title>
   <rdf:Alt>
    <rdf:li xml:lang='x-default'>Sometitle</rdf:li>
   </rdf:Alt>
  </dc:title>
 </rdf:Description>

 <rdf:Description rdf:about=''
  xmlns:pdf='http://ns.adobe.com/pdf/1.3/'>
  <pdf:Author>someone</pdf:Author>
 </rdf:Description>
</rdf:RDF>
</x:xmpmeta>
<?xpacket end='w'?>
```

and then I tried 

`djvused a.djvu -e 'set-meta op.xmp' -s `


but then when I try adding to calibre, it doesn't detect these metadata.


Infact `djvused a.djvu -e ' print-meta'`
returns just : 

```
<rdf:li "xml:lang='x-default'>Sometitle</rdf:li>"
<rdf:Description        "rdf:about=''"
<rdf:RDF        "xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>"
<x:xmpmeta      "xmlns:x='adobe:ns:meta/' x:xmptk='Image::ExifTool 12.00'>"
<?xpacket       "end='w'?>"
<Iptc4xmpExt:Series     "rdf:parseType='Resource'>"

```

Am I missing any step?

**Comment by boardhead** [comment]
I don't remember how to use djvused and no longer have this utility installed.  Does ExifTool see the XMP after embedding it?  If it does, then you have done it correctly.

**Comment by boardhead** [comment]
I found this, but it doesn't mention the djvused command:

https://exiftool.org/forum/index.php?topic=2779.0

**Comment by iamashwin99** [comment]
>Does ExifTool see the XMP after embedding it? If it does, then you have done it correctly.

I tried `exiftool -xmp:all a.djvu`
and it replies with 
```
XMP Toolkit                     : Image::ExifTool 12.00
Series Name                     : infinite
Publisher                       : someoneelse
Title                           : Sometitle
Author                          : someone

```

Does that mean it is embedding it correctly? 

If so then I need to figure out why calibre isn't reading this metadata. I must say, writing metadata is more complicated than it seems.

**Comment by boardhead** [comment]
> Does that mean it is embedding it correctly?

Yes.  My guess is that Calibre doesn't read XMP from DjVu images.
