### ISSUE TITLE
Example/Use case: process files older than N days

### ISSUE THREAD

**Issue by rvalle** [exiftool/exiftool#59]
I am trying to get around a conditional expression that will process files older than 30 days.

I think it is a very interesting use case that could be documented as an example. The use case is to move old photos out of the phones and send them to a photo application with the help of Syncthing. 

But my perl-fu is very very weak. I am arriving to something like:

time()-30*24*60*60 > $createDate

would something like that work? is createDate a timeStamp in seconds or a string? 

In the documentation there are some date comparison samples but I suspect it is actually strings been compared, is that correct?

How could I implement this conditional with exiftool?

**Comment by boardhead** [comment]
What you have done should work with the appropriate -d option:

`exiftool -if 'time()-302460*60 > $createDate' -d %s DIR`

- Phil

**Comment by rvalle** [comment]
@boardhead I can see your point.

using %s the date is returned seconds since epoch and thus the conditional work.

however, -d is also being used to move/rename the file.

**Comment by boardhead** [comment]
See the DateFmt function of [the advanced formatting feature](https://exiftool.org/exiftool_pod.html#Advanced-formatting-feature) for a way to use 2 different date/time formatting options in the same command.

**Comment by rvalle** [comment]
Yes! that is it.
In case someone wants to implement this same use case, the following expression will rename/move only the pictures that are older than 30 days:

```
  exiftool -v -r -o . -d "DEST_DIR/%Y-%m/%%f%%-c.%%e" "-filename<createDate" -if 'time() - 30*86400 > ${createdate#;DateFmt("%s")}' SOURCE_DIR 
```
