### ISSUE TITLE
Olympus Live Composite mode and 0x101c 

### ISSUE THREAD

**Issue by junkyardsparkle** [exiftool/exiftool#61]
Hi, I recently diffed some ORF files to find information related to the Live Composite feature (discussion [here](https://www.mu-43.com/threads/live-composite-image-details.109198/)), before realizing that a recent commit had addressed this. Just thought it was worth mentioning that in the process I noticed that using Live Composite mode on my E-PL7 creates a similar value in the "Multiple Exposure Mode" tag as it does in the "Stacked Image" tag already reported:
```
0x101c Multiple Exposure Mode  : 1 16
0x0804 Stacked Image           : 1 16
```

**Comment by boardhead** [comment]
Thanks!

Sorry for the delay in responding, I was on vacation.

This new value for MultipleExposureMode will appear in ExifTool 12.06.

 - Phil

**Comment by junkyardsparkle** [comment]
Thanks, closing!
