### ISSUE TITLE
`-all=` wipes colour profile information

### ISSUE THREAD

**Issue by dpk** [exiftool/exiftool#63]
If you save a JPEG image with colour profile information (I used Apple Photos.app and saved in Display P3 for this test), the colour profile information gets stored in EXIF metadata. Wiping all metadata is commonly done in order to protect privacy when posting images online (so as not to include sensitive personal info like location or even camera model), but if you do this the ‘easy’ way with `exiftool -all= file.jpg`, the colour profile information is wiped too, meaning the image renders incorrectly.

Since using exiftool for privacy reasons is fairly common, it would be nice to have an easy way to only wipe sensitive metadata without breaking the colour space information.

Two possible solutions:

1. add an alternative to `-all=` which only wipes EXIF data which is actually privacy-sensitive/doesn’t affect actual visual rendering of the image. (I could imagine the EXIF rotation tags pose similar issues.)
2. change `-all` to not affect colour profile information, and other information relevant to the actual rendering of the image, unless it's explicitly asked to

**Comment by boardhead** [comment]
This is a good point.  I've thought about this before but haven't received many complaints about this.  While I don't like changing the existing behaviour, maybe it makes sense in this case.  I'll have to think about this a bit more.  One complication is there are other EXIF tags which also contain color space information, and preserving these when deleting all EXIF would be a significant change.  So it is likely that if I do something in this direction (ie. preserve all color information), it won't be a universal solution.

- Phil

**Comment by jeremydmoore** [comment]
Hi Phil,

I’ve run into this issue too with art my reproduction/digitization work,
but now I’m not making color accurate derivatives from our master files so
I haven’t had to do this in a while.

I use Python and ended up making a call to exiftools to get all of the
color profile data into a variable, then I would strip the image and apply
the color profile data back to the image. As you said, there ended up being
multiple locations in the metadata I needed to retain.

Maybe if the image has a color profile, exiftools spits out a warning when
strip all is used about this and mentions a new option to retain color
data?

— Jeremy

**Comment by boardhead** [comment]
Note that there is a work-around for this as mentioned in the exiftool application documentation:

> A tag name of C<All> is equivalent to C<*> (except that it doesn't require
> quoting, while arguments with wildcards do on systems with shell globbing),
> and is often used when deleting all metadata (ie. C<-All=>) or an entire
> group (eg. C<-XMP-dc:All=>, see note 4 below).  Note that not all groups are
> deletable, and that the JPEG APP14 "Adobe" group is not removed by default
> with C<-All=> because it may affect the appearance of the image.  However,
> **color space information is removed**, so the colors may be affected (but this
> **may be avoided by copying back the tags defined by the ColorSpaceTags
> shortcut**). 

- Phil

**Comment by boardhead** [comment]
OK.  What I propose is to just add a warning when the ICC_Profile is deleted.  With the above work around, I think this should be sufficient.

- Phil

**Comment by boardhead** [comment]
This warning was added in ExifTool 12.11
