### ISSUE TITLE
Accept new IGC spec HFDTEDATE:DDMMYY,NN breaking HFDTE format

### ISSUE THREAD

**Issue by FlyingBird22** [exiftool/exiftool#64]
The new **IGC** [specification](https://www.fai.org/sites/default/files/igc_-_fr_specification_with_al5_2019-10-30.pdf) (search for **DTE** in spec) breaks the **HFDTE** format by changing it to **HFDTEDATE**:_DDMMYY,NN_

The new date format is defined since end of 2015 and replaced the old date format for newer igc files.

--> Please (also) provide **igc** input file format with this **_new date format_** in next version of **exiftool**. _(See [**Geotag.pm**](https://github.com/exiftool/exiftool/blob/master/lib/Image/ExifTool/Geotag.pm), code line 220.)_

_Further information:_
- [New IGC spec breaks HFDTE format](https://github.com/vicb/VisuGps/issues/11)
- [FAI FAQ](http://vali.fai-civl.org/faq.html) (search for **HFDTEDATE** in _FAQ_) and see:

"...
_Developer: What about latest 2015/09 changes on FAI-IGC FlightRecorder spec for the DTE record ? Which one to use now ?
new spec is:
**HFDTEDATE: DD MM YY , NN CRLF**
instead of former old IGC spec:
**HFDTE DD MM YY CRLF**
For the first year (after this change at the IGC specification), we recommend to stay with the old HFDTE format, and develop both within your software (as a configuration option). Now since 2017, we recommend for any new implementation the new HFDTEDATE format, as we believe that the used PC software and online contests should have implemented the new date format in the meantime._
..."

**Comment by boardhead** [comment]
Can you provide a sample file which uses this new format?

- Phil

**Comment by FlyingBird22** [comment]
Of course! Here it is. (I had to change the file suffix from .igc to .txt for uploading.)
[2020-10-09-XCT-DMA-01.txt](https://github.com/exiftool/exiftool/files/5371135/2020-10-09-XCT-DMA-01.txt)

You can find an almost unlimited number of current **igc** files on this server - some containing old **HFDTE** format others new **HFDTEDATE** format:
[https://www.xcontest.org/world/en/flights/daily-score-pg](https://www.xcontest.org/world/en/flights/daily-score-pg/)

Just press on red magnifier icon in info column of tracklog list to get "flight detail" of a tracklog and there on "IGC file" (download tracklog in IGC format).

Thanks for all your work and for this great project!
- Dave

**Comment by boardhead** [comment]
Thanks.  ExifTool 12.08 will support this new format.

- Phil
