### ISSUE TITLE
Write support for webp?

### ISSUE THREAD

**Issue by SheIITear** [exiftool/exiftool#65]
Hey I need a program to write webp files metadata, but apparently only reading is supported.
Is there any plans to support writing of webp files or any other way I could use to achieve writing the metadata?

**Comment by boardhead** [comment]
I already have a request for this feature, and plan to look into this in the winter when I have more time at the computer.

**Comment by SheIITear** [comment]
Thanks, I'll be waiting for that :).

**Comment by boardhead** [comment]
I'll leave this open so I won't forget...

**Comment by SheIITear** [comment]
Any success?

**Comment by boardhead** [comment]
No, sorry.  Write support is a lot of work, and I haven't had the time to do this.

**Comment by csolisr** [comment]
Sorry for necroposting, but I'm trying to add a description tag to a series of WebP files and it turns out that EXIFTool still has read-only access. Is this still planned? Are there any CLI tools I can use instead in the meanwhile?

**Comment by boardhead** [comment]
I don't know about other tools, but "planned" is a loose term.  It is on the list of things to do, but not likely to get done soon.

**Comment by StarGeekSpaceNerd** [comment]
I haven't tried it but there is [webpmux](https://developers.google.com/speed/webp/) which seems to indicate in the docs that it can edit EXIF and XMP data in a webp.  If you're on Windows and use Chocolatey, there's an [install package](https://community.chocolatey.org/packages/webp) for it.

**Comment by trevorld** [comment]
I think write support for webp was added to `exiftool` in https://github.com/exiftool/exiftool/commit/94d281ce058c8c2b909effc4f620a617220702b2

**Comment by StarGeekSpaceNerd** [comment]
Yes, in [version 12.46](https://exiftool.org/history.html#v12.46)

**Comment by boardhead** [comment]
Right.  Issue closed.
