### ISSUE TITLE
CRAW Canon EOS R5

### ISSUE THREAD

**Issue by neo22s** [exiftool/exiftool#66]
Hello,

CRAW from EOS R was working. It does not work with EOS R5 CRAW files.

**Comment by boardhead** [comment]
Can you provide a sample?  You can mail it to me:  philharvey66 at gmail.com

- Phil

**Comment by boardhead** [comment]
I've located an EOS R5 CRAW sample myself, and ExifTool works just fine extracting metadata from this file.  What exactly do you mean by "It does not work"?

**Comment by neo22s** [comment]
Sorry you are 100% correct the problem it's in the libraw
