### ISSUE TITLE
Question: persistent resolution with exiftool -all=

### ISSUE THREAD

**Issue by JayBrown** [exiftool/exiftool#74]
Maybe this is a stupid question. I'm removing metadata with `exiftool -all= -filename=bar foo`, but on macOS this also converts Retina resolution images (e.g. screenshots) from 144 ppi to 72 ppi, for example 840x280 px @ 144 ppi into 840x280 px @ 72 ppi.

Is this conversion related to the removal of all metadata, which would include resolution info? And is there a way around it, i.e. remove all metadata, but forgo any ppi conversion?

**Comment by boardhead** [comment]
The resolution information is in the metadata.  You can do this if you want:

`exiftool -all= -tagsfromfile @ "-all:*resolution*" FILE`

- Phil

**Comment by JayBrown** [comment]
Worked! Thank you very much!
