### ISSUE TITLE
PNG cHRM have only 4 decimal points

### ISSUE THREAD

**Issue by ValZapod** [exiftool/exiftool#75]
These ones: https://github.com/exiftool/exiftool/blob/3c3b0aff8521aaf6a8d1a60686df8173ee44bd86/lib/Image/ExifTool/PNG.pm#L371-L378

See: 
http://www.fnordware.com/j2k/relax-orig.png
Obviously this is 1.8008 Apple RGB gamma without piecewise stuff and cHRM almost from NTSC BT.601-5.

These are wrong:

```
White Point X                   : 0.3127
White Point Y                   : 0.32899
Red X                           : 0.62502
Red Y                           : 0.34001
Green X                         : 0.28
Green Y                         : 0.595
Blue X                          : 0.155
Blue Y                          : 0.07001

```

0.32899 should be 0.3290, for example. Etc.

**Comment by boardhead** [comment]
ExifTool is just reporting the values that were written.  If they are wrong, this is a fault of the software that wrote the image.

**Comment by ValZapod** [comment]
Oh, okay. You are right, I found another file with actual (and -v does show the difference)
**White Point Y                   : 0.329**

Closing.
