### ISSUE TITLE
VRex extension for .jps file

### ISSUE THREAD

**Issue by abakum** [exiftool/exiftool#78]
Please add VRex extension for .jps file.
Look:
* [Stereo Pair Image File Format](http://paulbourke.net/stereographics/stereoimage)
* [FFmeg](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/mjpegdec.c#L1963)

For test:
`ffmpeg -hide_banner -i test.jps -vf showinfo -f null - 2>&1|find /i "stereoscopic"`

Samples made by [StereoPhotoView](https://stereophotoview.bitbucket.io/) from FujiFilm.mpo:
* FujiFilmAB jps 
![FujiFilmAB jps](https://user-images.githubusercontent.com/18271863/117435804-ed581680-af36-11eb-92d7-1cec4bd6d78c.jpg)
* [FujiFilmLR jps 
![FujiFilmLR jps](https://user-images.githubusercontent.com/18271863/117435809-ef21da00-af36-11eb-8fe3-e5f549298ca8.jpg)
* FujiFilmRL jps 
![FujiFilmRL jps](https://user-images.githubusercontent.com/18271863/117435814-efba7080-af36-11eb-80c1-8b690da001ef.jpg)

**Comment by abakum** [comment]
```
C:\ins>ffmpeg -hide_banner -i 117435814-efba7080-af36-11eb-80c1-8b690da001ef.jpg -vf showinfo -f null - 2>&1|find /i "stereoscopic"
[Parsed_showinfo_0 @ 0000025dd4549e40]   side data - stereoscopic information: type - side by side (inverted)

C:\ins>ffmpeg -hide_banner -i 117435809-ef21da00-af36-11eb-8fe3-e5f549298ca8.jpg -vf showinfo -f null - 2>&1|find /i "stereoscopic"
[Parsed_showinfo_0 @ 000001b930ea9e40]   side data - stereoscopic information: type - side by side

C:\ins>ffmpeg -hide_banner -i 18271863/117435804-ed581680-af36-11eb-92d7-1cec4bd6d78c.jpg -vf showinfo -f null - 2>&1|find /i "stereoscopic"

C:\ins>ffmpeg -hide_banner -i 117435804-ed581680-af36-11eb-92d7-1cec4bd6d78c.jpg -vf showinfo -f null - 2>&1|find /i "stereoscopic"
[Parsed_showinfo_0 @ 000001c84fbd9d80]   side data - stereoscopic information: type - top and bottom```

**Comment by boardhead** [comment]
Thanks for this suggestion.  ExifTool 12.26 will support JPS images.

**Comment by abakum** [comment]
Thanks!
exiftool.exe -ver -app3:all 117435804-ed581680-af36-11eb-92d7-1cec4bd6d78c.jpg
12.39
JPS Separation                  : 0
JPS Flags                       : Left field first
JPS Layout                      : Over Under
JPS Type                        : Stereo

exiftool.exe -ver -app3:all 117435814-efba7080-af36-11eb-80c1-8b690da001ef.jpg
12.39
JPS Separation                  : 0
JPS Flags                       : (none)
JPS Layout                      : Side By Side
JPS Type                        : Stereo

exiftool.exe -ver -app3:all 117435809-ef21da00-af36-11eb-8fe3-e5f549298ca8.jpg
12.39
JPS Separation                  : 0
JPS Flags                       : Left field first
JPS Layout                      : Side By Side
JPS Type                        : Stereo
