### ISSUE TITLE
Wrong MIME-type for macro-enabled office documents

### ISSUE THREAD

**Issue by mstroecker-4ap** [exiftool/exiftool#79]
Hi,

when I create a macro-enabled Office document, (e.g. `.xlsm`), the ExifTool reports MIME-type `application/vnd.ms-excel.sheet.macroEnabled`. 

The Windows Details report `application/vnd.ms-excel.sheet.macroEnabled.12`. When searching for that MIME-type I could also just find it **with** the `.12` suffix. The `marcoEnabled` MIME-types without the `.12` suffix do not seem to exist at all.

Is the ExifTool mistaken and could it be fixed?

- https://www.iana.org/assignments/media-types/media-types.xhtml

Thanks for your help

**Comment by boardhead** [comment]
Thanks.  This will be fixed in version 12.27

**Comment by mstroecker-4ap** [comment]
Good stuff, thank you very much.
