### ISSUE TITLE
Writing cyrillic text to PDF metadata fields

### ISSUE THREAD

**Issue by Korb** [exiftool/exiftool#81]
When trying to write Russian text into PDF metadata, only question marks appear in the corresponding fields of documents. Numbers and Latin letters are processed normally.

Use commands like:

exiftool.exe [-charset filename=""](https://exiftool.org/exiftool_pod.html#WINDOWS-UNICODE-FILE-NAMES) filename.pdf -Title="пример"
exiftool.exe -charset filename="" filename.pdf -Creator="пример"
exiftool.exe -charset filename="" filename.pdf -AuthorsPosition="пример"
exiftool.exe -charset filename="" filename.pdf -Description="пример"
exiftool.exe -charset filename="" filename.pdf -CaptionWriter="пример"
exiftool.exe -charset filename="" filename.pdf -Subject="пример"
exiftool.exe -charset filename="" filename.pdf -WebStatement="https://дети.рф"

Whether cmd.exe or powershell.exe is used, I did not notice the difference.

exiftool 12.2.5.0
Microsoft Windows 10.0.19043.1083 x64

**Comment by boardhead** [comment]
Reading FAQ's 10 and 18 may help explain this:

https://exiftool.org/faq.html#Q10

https://exiftool.org/faq.html#Q18

- Phil

**Comment by Korb** [comment]
Thank you, in Windows Terminal Preview 1.9.1445.0, metadata in Russian is correctly entered into PDF through the use of external text files in UTF8 encoding and command

`& '.\exiftool(-k).exe' -charset filename="" -Creator<="Creator.txt" -Subject<="Subject.txt" -WebStatement<="WebStatement.txt" -Wext PDF -r -ext PDF -overwrite_original "<path to PDF files>"`

It is a pity that the solution was not so obvious and easy to use.
