### ISSUE TITLE
Remove group info  some special tag

### ISSUE THREAD

**Issue by 781545872** [exiftool/exiftool#82]
Hello!I try to remove adobe group info but preserve some special tags.
`exiftool -all= -adobe:all= -tagsfromfile @ -adobe:APP14Flags0 base.jpeg`
The error info shows bellow.
`Sorry, adobe:app14flags0 doesn't exist or isn't writable`
Is there any way to solve this problem? It seems that no-writable tags don't work.

**Comment by boardhead** [comment]
You can write back unwritable tags.  To do what you want, you need to exclude the whole group from the delete.

I don't understand what you are trying to do.  The Adobe APP14 segment has a fixed structure.  I don't see how you can delete it and try to add back only one of the binary fields.

**Comment by 781545872** [comment]
Thanks for your reply!
