### ISSUE TITLE
Canon CR3 format: Sigma 30 mm F1.4 DC DN (EFM) wrongly identified

### ISSUE THREAD

**Issue by dheijl** [exiftool/exiftool#83]
Camera: Canon M50
Lens: "Sigma 30mm F1.4 DC DN | Contemporary 016" (EF-M version) as reported by Canon DPP 4

Both exiftool and exiv2 wrongly identify the lens as the "Sigma 56mm f/1.4 DC DN", although the focal length is correctly reported as 30mm.

Example CR3 file attached.
[IMG_2362.zip](https://github.com/exiftool/exiftool/files/6830541/IMG_2362.zip)

**Comment by boardhead** [comment]
Thanks!  I'll add support for this in ExifTool 12.30

**Comment by dheijl** [comment]
Thank *you* !

**Comment by boardhead** [comment]
ExifTool 12.30 is now available so I am closing this issue.  Feel free to re-open it if it doesn't work as expected.
