### ISSUE TITLE
Strange WAV Behavior

### ISSUE THREAD

**Issue by enricozb** [exiftool/exiftool#85]
Hi,

Thank you so much for writing and maintaining exiftool, I have heavily depended on it for many of my personal tools.

Recently I learned that it also supports audio files, so I wanted to test it out on some songs I have.

I have a [wav file](https://drive.google.com/file/d/12yQ9tBf89m8DYlpSE4EB6rcaznxpUBK5/view?usp=sharing) that is causing some unexpected behavior from exiftool. I'm just trying to read tags, but I'm confused with the output. If I use `mutagen-inspect` on it to see the RIFF tags, I get:
```
$ mutagen-inspect 'plotinus.wav'
-- plotinus.wav
- 2 channel RIFF @ 352800 bps, 44100 Hz, 456.52 seconds (audio/wav)
APIC=cover front,  (image/jpeg, 68496 bytes)
TALB=Hello Everything
TIT2=Plotinus
TPE1=Squarepusher
TRCK=10
```
Which is what I expect. I'm specifically only focusing on the title, album, artist, and track number.

However if we use `exiftool`, we get:
```
$ plotinus.wav'
ExifTool Version Number         : 12.29
File Name                       : plotinus.wav
Directory                       : .
File Size                       : 77 MiB
File Modification Date/Time     : 2021:06:26 15:17:12-10:00
File Access Date/Time           : 2021:07:31 16:06:47-10:00
File Inode Change Date/Time     : 2021:06:26 15:17:12-10:00
File Permissions                : -rw-r--r--
File Type                       : WAV
File Type Extension             : wav
MIME Type                       : audio/x-wav
Encoding                        : Microsoft PCM
Num Channels                    : 2
Sample Rate                     : 44100
Avg Bytes Per Sec               : 176400
Bits Per Sample                 : 16
Title                           : Plotinus
Artist                          : Squarepusher
Product                         : Hello Everything
Duration                        : 0:07:37
```

I notice a few things:
  - The album tag `TALB` is again not mentioned in the exiftool docs, and appears under the tag `Product` in exiftool's output.
  - The `TRCK` tag is mentioned in the exiftool docs, but it does not appear in the exiftool output.
  - The title tag is `TIT2` but the exiftool docs [here](https://exiftool.org/TagNames/RIFF.html) make no mention of `TIT2`, so I'm unsure how it's reading this.

So my questions basically are: why is the album under `Product` and why is the `TrackNumber` missing?

Thanks again for taking a look at this.

**Comment by boardhead** [comment]
Take a look at the ExifTool -v3 optput.  ExifTool is reading the native RIFF information, but there are other tags stored in an id3 chunk that ExifTool isn't reading.  I'll look into adding support for this.

**Comment by boardhead** [comment]
ExifTool 12.30 (to be released today or tomorrow) will decode this ID3 information.

**Comment by boardhead** [comment]
ExifTool 12.30 is now available so I am closing this issue.  Feel free to re-open it if it doesn't work as expected.

**Comment by enricozb** [comment]
Thank you so much!
