### ISSUE TITLE
Meta: ExifTool.org website should clarify which issue tracker to use/prefer

### ISSUE THREAD

**Issue by porg** [exiftool/exiftool#87]
I noticed a bug, which right after this meta issue, I reported as #88.

What I usually do before reporting is go to the official software website and look for a section like "Report bugs, give feedback, Contact" etc.

On https://exiftool.org your section "Additional Documentation and Resources" mentions: GitHub, CPAN and SourceForge as bullet points of similar value. States no preferred issue tracker.

Now before I submit a bug report, I usually search the tracker. But  searching n issue trackers is n times more effort for me your willing contributor. And I imagine you as the maintainer also need to manage multiple channels, sort out duplicate reports over multiple channels, etc.

So for your interested audience please provide clear instructions what is the correct/preferred channel for what type of involvement. Thanks!

**Comment by boardhead** [comment]
Any or all of these channels are equally OK.

**Comment by porg** [comment]
1) Thanks for that information.
2) Ok, that this is ok for you.
3) Nevertheless you should be aware that this puts an extra burden on your diligent community members who need to check multiple places in order to avoid duplicate reporting. Can you give that some thought maybe?

**Comment by boardhead** [comment]
So far, in the 17+ years of ExifTool, you have been the only diligent community member.  ;)

**Comment by boardhead** [comment]
But seriously.  Duplicating issues hasn't been a problem so far because I usually take care of issues before anybody else notices them.

**Comment by porg** [comment]
Ok, very clear prof that things work out for you as they are!

Just a last point to consider: You may never know if people hesitated to report something because the user journey towards the feedback channel was not very guided and then skipped their intent to report something. That's of course a dark figure hard to determine.

But I really think from what you are saying, that it works out fine for you and the project as it is.

You reply very quickly - kudos! - that's also a quality which ensures engagement of a software development community!

Carry on the good work! Thanks!
