### ISSUE TITLE
exiftool "-alldates<filecreatedate" falsely sets creation & modification dates to now (on macOS with APFS)

### ISSUE THREAD

**Issue by porg** [exiftool/exiftool#88]
## Environment
* exiftool 12.26
* macOS 11.4 Big Sur
* APFS ([Apple File System](https://en.wikipedia.org/wiki/Apple_File_System))

## About the sourcefiles
With ImageMagick I batch converted from a directory of PNGs to a directory with JPGs:

    mogrify -verbose -define preserve-timestamp=true -format jpg -quality 60% -path ./output/ ./input/*.png

* The PNG source files have no EXIF header.
* Nevertheless setting the flag `preserve-timestamp=true` successfully preserved the creation + modification dates in the filesystem ([APFS](https://en.wikipedia.org/wiki/Apple_File_System)) for the freshly created files.
* All that was missing for was to also preserve the timestamp in an EXIF header.
  * Maybe **ImageMagick** could also do this.
  * Anyways I choose to do it with **exiftool** and detected a bug.

## Reproduction
    exiftool "-alldates<filecreatedate" ./output/

## Expected
* The creation-date and modification-date of each processed file is recreated in the filesystem and also in the EXIF header.

## Actual
* ❌ Creation-date and modification-date are falsely set to the current date and time.
* ✅ At least EXIF header gets correctly created from the creation date.
  * Compared the backup directory with the new output directory:
    * 300 bytes more for 12 files = 25 bytes more per each file.
    * Also inspected the files with a hex editor and the backup files do not have the EXIF timestamps whereas the converted files have them, and they were correctly copied from the fileystem's creation date.

**Comment by boardhead** [comment]
The FileCreateDate/FileModifyDate are updated to the current date/time when the file is edited.  This is normal for any application with respect to FileModifyDate.  FileCreateDate is also changed because a new file is created, and the original file is preserved with a "_original" added to the name.  Use the "-overwrite_original_in_place" option to preserve the FileCreateDate, and the -P option to preserve the FileModifyDate.

**Comment by porg** [comment]
Halleluja! Works like a charm! Added this whole workflow as a Q&A at:
https://superuser.com/questions/1668881/how-to-batch-convert-pngs-to-jpegs-and-preserve-timestamps-in-filesystem-exif/
