### ISSUE TITLE
Google Pixel depth map issue

### ISSUE THREAD

**Issue by ghotz** [exiftool/exiftool#89]
In the past, I was able to extract a depth map jpg from Pixel 2 images using the `depthmap.config` config file like this:
```
exiftool -config depthmap.config -b -depthmap -w %f_depthmap.jpg examplepic.jpg
```
This stopped working at some point in 2020 when Google seems to have changed again the format, I tried poking around with it but don't have enough knowledge of *trailers* and jpg internals.

FWIW I'm able to extract the map using this workaround found in the Exiftool forum:
```
exiftool -trailer -b examplepic.jpg | exiftool - -trailer -b > depthmap.jpg
```
but I preferred the other method as it allowed me to work directly with tags like this:
```
exiftool -config depthmap.config -P -overwrite_original -b -if "$depthmap or $Data" "-Keywords+=HasDepthMap" -ext jpg *
```

I'm attaching a test image if anyone wants to play with it:
[PXL_20210808_082657420.PORTRAIT.zip](https://github.com/exiftool/exiftool/files/6984074/PXL_20210808_082657420.PORTRAIT.zip)

**Comment by boardhead** [comment]
I can probably write a config file that will do what you want.  It will involve a Composite tag based on the Trailer.  But I won't be able to do this for a few days.

- Phil

**Comment by ghotz** [comment]
Sure, thanks, if/whenever you have time :-)

**Comment by boardhead** [comment]
Here you go.  You can extract this type of trailer with a command like this and the attached config file:

`exiftool -config mydepthmap.config -mydepthmap -b -w %f_depthmap.jpg FILE`

[mydepthmap.config.txt](https://github.com/exiftool/exiftool/files/6999984/mydepthmap.config.txt)
