### ISSUE TITLE
DICOM string tags have a extra white space (and have even length)

### ISSUE THREAD

**Issue by bersbersbers** [exiftool/exiftool#9]
Hi,
exiftool is awesome! One thing that I have noticed, however, is that DICOM tags often have a trailing space. Here's how to see that:

- Download ttfm.dcm from https://medistim.com/dicom/ (http://medistim.com/wp-content/uploads/2016/07/ttfm.dcm)
- Run exiftool.exe -php ttfm.dcm

This is what I am getting:
```
Array(Array(
  "SourceFile" => "C:/Users/me/Downloads/ttfm.dcm",
  "ExifToolVersion" => 11.26,
  "FileName" => "ttfm.dcm",
  "Directory" => "C:/Users/me/Downloads",
  "FileSize" => "341 kB",
  "FileModifyDate" => "2019:02:14 13:57:42+01:00",
  "FileAccessDate" => "2019:02:14 13:57:41+01:00",
  "FileCreateDate" => "2019:02:14 13:57:41+01:00",
  "FilePermissions" => "rw-rw-rw-",
  "FileType" => "DICOM",
  "FileTypeExtension" => "dcm",
  "MIMEType" => "application/dicom",
  "FileMetaInfoGroupLength" => 158,
  "FileMetaInfoVersion" => "0 1",
  "MediaStorageSOPClassUID" => "Ultrasound Multi-frame Image Storage",
  "MediaStorageSOPInstanceUID" => "2.16.840.1.114488.0.4.123489834087.1330071425.2",
  "TransferSyntaxUID" => "JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14-1)",
  "ImplementationClassUID" => "1.2.840.114236",
  "SpecificCharacterSet" => "ISO_IR 100",
  "ImageType" => "\\SECONDARY\\INTRAOPERATIVE ",
  "SOPClassUID" => "Ultrasound Multi-frame Image Storage",
  "SOPInstanceUID" => "2.16.840.1.114488.0.4.123489834087.1330071425.2",
  "StudyDate" => "2011:08:24",
  "SeriesDate" => "2011:08:24",
  "ContentDate" => "2011:08:24",
  "StudyTime" => "09:48:36.214743984",
  "SeriesTime" => "09:48:36.214743984",
  "ContentTime" => "10:04:51.214743816",
  "AccessionNumber" => "",
  "Modality" => "US",
  "Manufacturer" => "Medistim",
  "InstitutionName" => "Hospital Name ",
  "InstitutionAddress" => "Hospital Address or Department",
  "ReferringPhysicianName" => "",
  "StationName" => "VERIQ ",
  "StudyDescription" => "",
  "PerformingPhysicianName" => "CA Prof. Debus",
  "ManufacturersModelName" => "VeriQ C ",
  "RecommendedDisplayFrameRate" => "1 ",
  "PatientName" => "Femoral trombenarterectomy^Case Report: ",
  "PatientID" => "Case Report 1 ",
  "PatientBirthDate" => "",
  "PatientSex" => "M ",
  "PatientSize" => "0 ",
  "PatientWeight" => "0 ",
  "PatientComments" => "See case report on www.medistim.com ",
  "CineRate" => "1 ",
  "EffectiveDuration" => "1 ",
  "DeviceSerialNumber" => "0 ",
  "SoftwareVersion" => "3.3.0 RC0 built 02/23/12  09:50:45",
  "FrameTime" => 1000,
  "PreferredPlaybackSequencing" => 0,
  "SequenceOfUltrasoundRegions" => "",
  "StudyInstanceUID" => "2.16.840.1.114488.0.4.123489834087.1330071425.0",
  "SeriesInstanceUID" => "2.16.840.1.114488.0.4.123489834087.1330071425.1",
  "StudyID" => "",
  "SeriesNumber" => "1 ",
  "InstanceNumber" => "1 ",
  "PatientOrientation" => "",
  "Laterality" => "",
  "ImageComments" => "",
  "SamplesPerPixel" => 3,
  "PhotometricInterpretation" => "RGB ",
  "PlanarConfiguration" => 0,
  "NumberOfFrames" => " 1",
  "FrameIncrementPointer" => "0018,1063",
  "Rows" => 768,
  "Columns" => 1024,
  "BitsAllocated" => 8,
  "BitsStored" => 8,
  "HighBit" => 7,
  "PixelRepresentation" => "Unsigned",
  "LossyImageCompression" => "00",
  "PixelData" => "(Binary data 0 bytes, use -b option to extract)",
  "StartOfItem" => "(Binary data 347414 bytes, use -b option to extract)",
  "EndOfSequence" => ""
));
```

Take an extra-close look at this section:
```
  "PerformingPhysicianName" => "CA Prof. Debus",
  "ManufacturersModelName" => "VeriQ C ",
  "RecommendedDisplayFrameRate" => "1 ",
  "PatientName" => "Femoral trombenarterectomy^Case Report: ",
  "PatientID" => "Case Report 1 ",
```

It is remarkable that all of these strings have an even number of characters due to the extra space. Is that a coincidence?

Either way, the manual says 
> that trailing spaces are removed from extracted values for most output text formats,

so I believe this should be fixed.

**Comment by bersbersbers** [comment]
I believe this is due to DICOM being inherently 16-bit based. According to `dcmdump` from DCMTK, the strings *are* reserved as an even number of bytes. Nonetheless, their values does not include the trailing space according to `dcmdump`:

```
(0008,1010) SH [VERIQ]                                  #   6, 1 StationName
(0008,1030) LO (no value available)                     #   0, 0 StudyDescription
(0008,1050) PN [CA Prof. Debus]                         #  14, 1 PerformingPhysicianName
(0008,1090) LO [VeriQ C]                                #   8, 1 ManufacturerModelName
(0008,2144) IS [1]                                      #   2, 1 RecommendedDisplayFrameRate
(0010,0010) PN [Femoral trombenarterectomy^Case Report:] #  40, 1 PatientName
(0010,0020) LO [Case Report 1]                          #  14, 1 PatientID
```

**Comment by bersbersbers** [comment]
One workaround it to use `${InstanceNumber;s/ $//}` instead of `$InstanceNumber`. Awesome!

**Comment by boardhead** [comment]
Thanks for this report.

ExifTool 11.29 will have a patch to remove this trailing space.

**Comment by boardhead** [comment]
Resolved by ExifTool 11.29

**Comment by bersbersbers** [comment]
Looks good, thank you!

By the way, do you know why I do not get any notifications for exiftool releases despite watching the github project for "releases only"? I do that for dozens of projects and have never missed a notification. For exiftool I do not get any. Are you maybe suppressing notifications when adding new releases? (I doubt that, but I want to be sure...)

**Comment by boardhead** [comment]
Notifications are active in the github exiftool/exiftool settings, but I'm not very familiar with how this works so I don't know what the problem could be.

**Comment by bersbersbers** [comment]
> Notifications are active in the github exiftool/exiftool settings, but I'm not very familiar with how this works so I don't know what the problem could be.

I believe my misunderstanding was based on this, after an exchange with the GitHub support: `exiftool` does not have any formal releases, only tags - which do appear on the "releases" page, but do not trigger a release notification. Yes, I find this counterintuitive as well ;)

**Comment by boardhead** [comment]
I guess I have to figure out how to do a release.  If there is a way to do this remotely from the command line then I can add it to my "publish" script.  Otherwise, it may not be worth the trouble.

**Comment by boardhead** [comment]
I looked into this, and there is a command-line interface:

https://developer.github.com/v3/repos/releases/#create-a-release

So maybe this is a possibility, but some questions need to be answered:

1. I need to figure out the exact syntax to issue the POST command for exiftool.

2. If I do this, will the version show up twice on the releases page since the tag already appears there?

**Comment by bersbersbers** [comment]
There sure is a way, see here if interested:
- https://developer.github.com/v3/repos/releases/#create-a-release
You can even upload binaries ("assets") that way, if that's something you like to do.

In action:
- https://github.community/t5/How-to-use-Git-and-GitHub/How-to-create-full-release-from-command-line-not-just-a-tag/td-p/6895
- https://stackoverflow.com/questions/21214562/how-to-release-versions-on-github-through-the-command-line

**Comment by boardhead** [comment]
Further discussion about this here: #13
