### ISSUE TITLE
How to choose the Tag with include space character? (For example: Modify Date)

### ISSUE THREAD

**Issue by tzabcd** [exiftool/exiftool#93]
How to choose the Tag with include space character? 
For example: 
Modify Date 
Create Date

I try to write like this:
exiftool   Modify Date=0000:00:00 00:00:00   
but it's not work.

thanks

**Comment by boardhead** [comment]
This is FAQ number 2:  https://exiftool.org/faq.html#Q2

**Comment by tzabcd** [comment]
> This is FAQ number 2: https://exiftool.org/faq.html#Q2

thanks,when I try to write command like this:    exiftool  -TagHaveSpace=  1.mp4     ,but it's return  Tag 'TagHaveSpace' is not defined.  
when I use command like this:   exiftool 1.mp4   ,the tag show me like this:

Tag Have Space    

how to choose this tag ?

**Comment by boardhead** [comment]
ExifTool can only write tags which have been defined.  If it isn't one of the 5922 built-in tags then you must create a user-defined tag to be able to write it.  See the example config file for examples:  https://exiftool.org/config.html

**Comment by tzabcd** [comment]
> ExifTool can only write tags which have been defined. If it isn't one of the 5922 built-in writable tags then you must create a user-defined tag to be able to write it. See the example config file for examples: https://exiftool.org/config.html

thanks very much. I try to rebuild exiftool in windows command shell like this :    perl exiftool  -NewEXIFTag=1 1.mp4
but that's script  still return :  Warning: Tag 'NewEXIFTag' is not defined   
I found this new tag added in file of  example.config ,  how can I use what command or arguments let example.config is valid?
I can't find any help description with let user defined tag become valid.

**Comment by tzabcd** [comment]
> ExifTool can only write tags which have been defined. If it isn't one of the 5922 built-in writable tags then you must create a user-defined tag to be able to write it. See the example config file for examples: https://exiftool.org/config.html

Thanks very much. I  try to use this command :   exiftool -NewEXIFTag=1  1.mp4   
but command return:   
 0 image files updated
 1 image files unchanged
it seems new tag NewEXIFTag in .ExifTool_config file is usefull ,but it can not add new tag "NewEXIFTag"  in 1.mp4 file.
i will add new tag 'NewEXIFTag'  in exif of 1.mp4, how can i do ?  thanks.

**Comment by boardhead** [comment]
The MP4 specification doesn't support EXIF-formatted metadata.  For this, I suggest using XMP.

- Phil
