### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by cmckni3** [exiftool/exiftool#95]
<img width="1440" alt="2021-09-20_11-28-27" src="https://user-images.githubusercontent.com/735717/134038927-def30fe4-3629-4064-a4f4-ce10837fc6c9.png">

**Comment by boardhead** [comment]
Yes.  Dreamhost shut it down again due to high load. :(

It is up again now

**Comment by boardhead** [comment]
I've taken more steps to prevent this from happening again.  It's been a few months since the last shutdown, so I suppose we won't know if I was successful in fixing this for about a year or so.

**Comment by cmckni3** [comment]
Good to see it's up again. Thanks!
